### PR TITLE
fix(editor): Mark workflow dirty after debug pinData changes

### LINKED ISSUE #28621: Can't copy to editor previous executions
## Describe the problem/error/question
When trying to reproduce a previously executed execution from the list, after clicking on it, and confirming "Unpin" on the message box that appears, data from the trigger node doesn't actually update if previous data from another execution was already pinned. Visually, it appears that new data is there, but when executing on test mode, all the execution goes through using the previously stored data.

## Please share your workflow/screenshots/recording

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
⚠️ WARNING ⚠️ If you have sensitive data in your workflow (like API keys), please remove it before sharing.
```

### core

- n8nVersion: 2.16.1
- platform: docker (cloud)
- nodeJsVersion: 24.14.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: enterprise (sandbox)

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 720 hours
- maxCount: 25000 executions

### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/147.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2026-04-17T13:24:39.601Z

### PR DESCRIPTION
**Pull request by RicardoE105**
## Summary

When using "Copy to Editor" on a previous execution, the debug flow pins execution data on trigger nodes but doesn't mark the workflow state as dirty. This causes the workflow save to be skipped before the next execution, so the backend loads stale pinData from the database.

For webhook triggers, this results in the webhook listener starting instead of using the pinned data. The user sees the correct data visually in the editor, but the execution ignores it.

### Root cause

`applyExecutionData()` in `useExecutionDebugging.ts` calls `pinNodeData()` / `unpinNodeData()` directly on the document store without calling `uiStore.markStateDirty()`. Compare to the normal UI pin flow in `usePinnedData.ts` which always calls `markStateDirty()` after pin/unpin operations.

The execution flow in `useRunWorkflow.ts` only saves the workflow when the state is dirty:
```typescript
if (uiStore.stateIsDirty || !workflowsStore.isWorkflowSaved[workflowsStore.workflowId]) {
    await workflowSaving.saveCurrentWorkflow();
}
```

Since the state wasn't dirty, the save was skipped, and the backend loaded the workflow from the DB with stale (or empty) pinData.

### Fix

Added `markStateDirty()` after the pinning loop in `applyExecutionData()`, consistent with how `usePinnedData` handles pin/unpin operations.

### How to reproduce

1. Import this workflow:
```json
{
  "nodes": [
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "test-pin-data",
        "options": {}
      },
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2.1,
      "position": [-288, 128],
      "id": "6f950303-3282-4dad-b7c1-a025edf84488",
      "name": "Webhook",
      "webhookId": "2cdc3007-cbdf-469f-bc82-455e104d5dec"
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "16f832b5-3239-4660-8d78-6c3a4728a88a",
              "name": "execution",
              "value": "={{ $json.body.execution }}",
              "type": "number"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [0, 0],
      "id": "873069b5-596a-4c2b-a9af-b4728020699e",
      "name": "Edit Fields"
    }
  ],
  "connections": {
    "Webhook": {
      "main": [
        [
          {
            "node": "Edit Fields",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "instanceId": "894084186bca4f16af77f7175316424e63f4c0365fc176b0fa2c7cf1b1be23c7"
  }
}
```

2. Activate the workflow and send two POST requests with different bodies:
```bash
curl -X POST http://localhost:5678/webhook/test-pin-data \
  -H "Content-Type: application/json" \
  -d '{"execution": 1, "value": 100}'

curl -X POST http://localhost:5678/webhook/test-pin-data \
  -H "Content-Type: application/json" \
  -d '{"execution": 2, "value": 999}'
```

3. **Scenario A — Copy to Editor then Execute:**
   1. Go to **Executions** tab → click on execution 1 → click **"Copy to Editor"**
   2. Click **"Execute Workflow"**
   3. Open the **Edit Fields** node output
   4. **Before fix:** Webhook starts listening for events instead of using pinned data
   5. **After fix:** Execution runs immediately and the Edit Fields node output shows `execution: 1`

4. **Scenario B — Switch between executions (verify correct data is used):**
   1. Go to **Executions** tab → click on execution 1 (value: 100) → click **"Copy to Editor"**
   2. Go back to **Executions** tab → click on execution 2 (value: 999) → click **"Copy to Editor"**
   3. Confirm **"Unpin"** in the dialog
   4. Click **"Execute Workflow"**
   5. Open the **Edit Fields** node output
   6. **Before fix:** Edit Fields output shows `execution: 1` — it used execution 1's stale pinned data
   7. **After fix:** Edit Fields output shows `execution: 2` — it correctly uses execution 2's data

## Related Linear tickets, Github issues, and Community forum posts

- https://linear.app/n8n/issue/ADO-5088
- Closes https://github.com/n8n-io/n8n/issues/28621

## Review / Merge checklist

- [x] I have seen this code, I have run this code, and I take responsibility for this code.
- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
- [ ] PR Labeled with `Backport to Beta`, `Backport to Stable`, or `Backport to v1` (if the PR is an urgent fix that needs to be backported)
- [x] I have seen this code, I have run this code, and I take responsibility for this code.

### CODE REVIEW

File: packages/frontend/editor-ui/src/features/execution/executions/composables/useExecutionDebugging.ts [hunk 1]
```diff
@@ -130,6 +131,10 @@ export const useExecutionDebugging = (providedWorkflowState?: WorkflowState) =>
 			}
 		});
 
+		// Mark workflow dirty so it gets saved before execution.
+		// Without this, the backend loads stale pinData from the DB.
+		markStateDirty();
```
Comment (MiloradFilipovic) [inline packages/frontend/editor-ui/src/features/execution/executions/composables/useExecutionDebugging.ts]: Should we maybe check if there is data to pin (like `innings > 0 || matchingPinnedNodeNames.length > 0`) so we don't mark workflows as dirty unnecessarily. For example, if you rename a node in the text example and try to copy execution that uses old name to the editor, nothing gets pinned but the workflow still gets set as dirty (no big harm, but maybe worth addressing)

**Review by MiloradFilipovic — DISMISSED** [review]
Looks and works good. I left a minor comment so take a look if it makes sense

**Review by MiloradFilipovic — DISMISSED** [review]
Nice, thanks for addressing

**Review by MiloradFilipovic — APPROVED** [review]
