### PR TITLE
fix(WhatsApp Business Cloud Node): Include whatsapp id in contact properties

### LINKED ISSUE #14460: WhatsApp Business - Send Message - Type Contact
### Bug Description

When attempting to send a message of type contacts, the node is sending an incorrect JSON payload.

The phones array currently includes multiple objects with a type field, which does not align with the [WhatsApp Business API specification](https://developers.facebook.com/docs/whatsapp/api/messages#contacts-object). It uses this incorrect structure:

However, according to the official API documentation, the correct format for a phone entry is a single object that includes both phone and optionally wa_id, like this:

    "messaging_product": "whatsapp",
    "contacts": [
        {
            "name": {
                "formatted_name": "NAME",
                "first_name": "NAME",
                "last_name": "",
                "middle_name": "",
                "suffix": "",
                "prefix": ""
            },
            "phones": [
                {
                    "type": "wa_id",
                    "phone": "551100000000"
                },
                {
                    "type": "CELL",
                    "phone": "+551100000000"
                }
            ]
        }
    ],
    "type": "contacts",
    "to": "551100000000"
}

    "messaging_product": "whatsapp",
    "to": "{{Recipient-Phone-Number}}",
    "type": "contacts",
    "contacts": [
        {
            "name": {
                "formatted_name": "Sarah Tavares",
                "first_name": "Sarah"
            },
            "phones": [
                {
                    "phone": "+551100000000",
                    "wa_id": "551100000000"
                }
            ]
        }
    ]
}

### To Reproduce

1 - Send WhatsApp Message with type Contact
2- Fill Additional Fields Phones
3- Fill Type - WhatsApp ID
4- Fill Type - Phone

### Expected behavior

Expected (Correct) Payload:
{
"messaging_product": "whatsapp",
"to": "{{Recipient-Phone-Number}}",
"type": "contacts",
"contacts": [
{
"name": {
"formatted_name": "Sarah Tavares",
"first_name": "Sarah"
},
"phones": [
{
"phone": "+551100000000",
"wa_id": "551100000000"
}
]
}
]
}

### Operating System

Ubutnu 24

### n8n Version

1.86.0

### Node.js Version

0

### Database

PostgreSQL

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by yehorkardash**
## Summary

This PR introduces and new version of the node where the wa_id contact type is removed and instead a new optional field "WhatsApp User ID" is added to all contact types. [Docs](https://developers.facebook.com/docs/whatsapp/cloud-api/messages/contacts-messages)

image

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-2822/community-issue-whatsapp-business-send-message-type-contact

closes #14460 

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/WhatsApp/MessagesDescription.ts [hunk 1]
```diff
@@ -596,6 +601,45 @@ export const messageTypeFields: INodeProperties[] = [
 									},
 								},
 							},
+							{
+								displayName: 'Type',
+								name: 'type_v11',
```
Comment (michael-radency) [inline packages/nodes-base/nodes/WhatsApp/MessagesDescription.ts]: do not rename parameter name as this is breaking change and without changes in code would be useless, this should be just `type` for both versions

**Review by michael-radency — CHANGES_REQUESTED** [review]

**Review by michael-radency — APPROVED** [review]
LGTM

**Comment by Joffcom** [comment]
Got released with [`n8n@1.114.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.114.0)
