### PR TITLE
fix(Extract from File Node): Detect file encoding 

### LINKED ISSUE #10950: Extract from text file corrupts non-UTF8 files
### Bug Description

If you're using the "Extract from text file" node to convert binary data into JSON, it will corrupt the data if it's not UTF8.

### To Reproduce

1. create a file, put `S0FSTE9WScSGICA=` **after having base64-decoded it** into it, this contains `Karlović` encoded using Windows-1250
2. read it with Read file
3. extract it with Extract from text file
4. it gets corrupted

If I use this in the following code node without it, it works:

```js
const body = iconv.decode(await this.helpers.getBinaryDataBuffer($itemIndex, 'file_0'), 'cp1250');
```

If I use the Extract node, it gets corrupted.

### Expected behavior

Non-UTF8 encodings also work

### Operating System

Docker image n8nio/n8n

### n8n Version

1.59.3

### Node.js Version

v20.17.0

### Database

PostgreSQL

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by dana-gill**
## Summary

Unless users sets the encoding themselves, we automatically assume that the file being passed in is `utf8` encoding, which is not always true. In this PR, we will use `chardet` to detect file encodings.

Recommended workflow for testing:

```
{
  "nodes": [
    {
      "parameters": {},
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        0,
        0
      ],
      "id": "64686c0a-64a4-4a33-9e70-038c9d23c25b",
      "name": "When clicking ‘Test workflow’"
    },
    {
      "parameters": {
        "operation": "text",
        "options": {}
      },
      "type": "n8n-nodes-base.extractFromFile",
      "typeVersion": 1,
      "position": [
        460,
        -40
      ],
      "id": "aaac18d3-1e99-4c47-9de8-2dc8bf95abd7",
      "name": "Extract from File"
    },
    {
      "parameters": {
        "fileSelector": "/Users/dana/Dana/bugs/utf_8_bug",
        "options": {}
      },
      "type": "n8n-nodes-base.readWriteFile",
      "typeVersion": 1,
      "position": [
        220,
        -40
      ],
      "id": "5f3d6bcd-1290-4444-85ef-49fea0b3caa7",
      "name": "Read/Write Files from Disk"
    }
  ],
  "connections": {
    "When clicking ‘Test workflow’": {
      "main": [
        [
          {
            "node": "Read/Write Files from Disk",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Extract from File": {
      "main": [
        []
      ]
    },
    "Read/Write Files from Disk": {
      "main": [
        [
          {
            "node": "Extract from File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-1767/community-issue-extract-from-text-file-corrupts-non-utf8-files
Closes https://github.com/n8n-io/n8n/issues/10950

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Files/ExtractFromFile/actions/moveTo.operation.ts [hunk 1]
```diff
@@ -121,8 +122,8 @@ export async function execute(
 
 			if (!value) continue;
 
-			const encoding = (options.encoding as string) || 'utf8';
 			const buffer = await this.helpers.getBinaryDataBuffer(itemIndex, binaryPropertyName);
+			const encoding = (options.encoding as string) || (chardet.detect(buffer) as string);
```
Comment (netroy) [inline packages/nodes-base/nodes/Files/ExtractFromFile/actions/moveTo.operation.ts:126]: considering how many other nodes do something similar, my preference would be to add a `this.helpers.detectBinaryEncoding` in core. 
Also, there might be couple of places in core that could also benefit from having auto-detect for encoding.

**Review by netroy — DISMISSED** [review]
🎉

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.73.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.73.0)
