### PR TITLE
fix(core): Use proxy for all npm commands

### LINKED ISSUE #24162: Bug: HTTP proxy environment variables not passed through in executeNpmCommand()
## Bug Description

The `executeNpmCommand()` method in the Community Packages Service does not pass through HTTP proxy environment variables, preventing npm commands from working behind corporate proxies. This affects the `/settings/community-nodes` endpoint functionality when checking for package updates.

The method explicitly sets a limited environment object that only includes `NODE_PATH`, `PATH`, `APPDATA`, and `NODE_ENV`, excluding proxy-related environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` and lowercase variants).

**File:** `packages/cli/src/modules/community-packages/community-packages.service.ts` (lines 166-175)

## To Reproduce

1. Deploy n8n behind a corporate HTTP proxy
2. Set proxy environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, etc.)
3. Navigate to Settings > Community Nodes (`/settings/community-nodes`)
4. See error in UI:
   ```
   Problem fetching installed packages
   
   There may be a problem with your internet connection or your n8n instance
   Request failed with status code 502
   ```

## Expected behavior

The `executeNpmCommand()` method should pass through proxy environment variables so npm commands work correctly behind corporate proxies, similar to how `downloadPackage()` in the same file inherits the full parent process environment.

## Workaround

Configure npm proxy settings globally via `.npmrc` or npm config:

```bash
docker exec n8n npm config set proxy http://proxy.example.com:3128
docker exec n8n npm config set https-proxy http://proxy.example.com:3128
```

## Debug Info

N/A - Code-level bug identified through source review

## Environment

- **Operating System:** Any (affects all deployments behind HTTP proxy)
- **n8n Version:** Current (verified against master branch)
- **Node.js Version:** Any
- **Database:** Any
- **Execution mode:** Any
- **Hosting:** Self-hosted (behind corporate proxy)

## Affected Code

Two operations use the deprecated `executeNpmCommand()` method:

1. **Checking for package updates** - `community-packages.controller.ts:172-174`
2. **Pruning dependencies** - `community-node.command.ts:140`

### PR DESCRIPTION
**Pull request by yehorkardash**
## Summary

This PR refactors all `npm` usages on backend to use a single helper method. It fixes issues when some npm commands that were using deprecated `executeNpmCommand` would not use proxy configuration because not all envs were passed to the command.

How to test:
- install tinyproxy
- use default configuration from their [website](https://tinyproxy.github.io/)
- set `HTTP_PROXY=http://127.0.0.1:port` and `HTTPS_PROXY=http://127.0.0.1:port` in n8n env variables
- Verify that requests to npm registry go through proxy

image

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-4197/community-issue-bug-http-proxy-environment-variables-not-passed
closes #24162 

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/cli/src/modules/community-packages/community-packages.controller.ts [hunk 1]
```diff
@@ -169,9 +170,7 @@ export class CommunityPackagesController {
 		let pendingUpdates: CommunityPackages.AvailableUpdates | undefined;
 
 		try {
-			await this.communityPackagesService.executeNpmCommand(['outdated', '--json'], {
-				doNotHandleError: true,
-			});
+			await executeNpmCommand(['outdated', '--json'], { doNotHandleError: true });
```
Comment (elsmr) [inline packages/cli/src/modules/community-packages/community-packages.controller.ts]: I noticed updates not showing up, is there a missing `cwd` argument here? maybe also double check the other callsites for `executeNpmCommand`

Comment (yehorkardash) [reply packages/cli/src/modules/community-packages/community-packages.controller.ts]: Good catch. That was the only place without cwd, others already had it

File: packages/cli/src/modules/community-packages/community-packages.service.ts [hunk 2]
```diff
@@ -549,8 +495,7 @@ export class CommunityPackagesService {
 
 		// TODO: make sure that this works for scoped packages as well
 		// if (packageName.startsWith('@') && packageName.includes('/')) {}
-		const { stdout: tarOutput } = await asyncExecFile(
-			'npm',
+		const tarOutput = await executeNpmCommand(
```
[the remark this answers is not in the document]
Comment (yehorkardash) [reply packages/cli/src/modules/community-packages/community-packages.service.ts:498]: Fixed

**Review by elsmr — APPROVED** [review]
