### PR TITLE
fix: Improve dev mode output and command reliability in `n8n-node` CLI

### LINKED ISSUE #21115: n8n-node dev initial run timeout issue
### Bug Description

I am working on developing community nodes on n8n and I have just started using `n8n-node` cli tool for the development cycle. When running `n8n-node dev` for the first time I see that it is downloading some dependencies. 

The issue is that I work at the library and connect my laptop to my mobile internet which is not the fastest. The cli tool fails to install deps in **120 seconds** causing the tool to timeout. I tried the same command at home with fast internet and it worked fine.

### To Reproduce

1. Have slow internet
2. Run the `n8n-node dev` for the first time triggering dep installation
3. If your internet is slow enough it will time out

### Expected behavior

To wait until the dependency installation is completed

### Debug Info

run `n8n-node dev` command

### Operating System

Windows

### n8n Version

"@n8n/node-cli": "*",

### Node.js Version

22.x

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by elsmr**
## Summary

Improved the `@n8n/node-cli` dev command with better output formatting and more reliable command execution:

- `n8n-node dev`
  - Shows output from `tsc` and `n8n` side-by-side in separate panels
  - Added `q` to quit and `o` to open n8n in browser during dev mode
  - Replaced package linking with direct symlinks (less error prone)
  - Added command headers, status indicators, and improved output organization
- Fixed timeout issues and improved process cleanup (fixes #21115)
- All commands now show CLI version, could help with bug reports
- Add lint rule to forbid `console` logging

### Installing n8n (initial run)

image

### After n8n started, developing

image

### Testing notes

1. Build the node-cli package and `pnpm link` to install it globally as `n8n-node`
2. Run `n8n-node new` to generate a new node
3. Run `n8n-node dev` in the generated node and/or other commands

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/@n8n/node-cli/src/utils/child-process.ts [hunk 1]
```diff
@@ -66,10 +67,14 @@ export async function runCommand(
 		});
 
 		child.on('close', (code, signal) => {
-			printOutput();
 			if (code === 0) {
+				// Only print output on success if alwaysPrintOutput is true
+				if (opts.alwaysPrintOutput) {
```
[the remark this answers is not in the document]
Comment (elsmr) [reply packages/@n8n/node-cli/src/utils/child-process.ts:72]: This was a bug, not restoring this

**Comment by yehorkardash** [comment]
Minor: 
I noticed that at least n8n-node dev doesn't clear the screen and lock it in one place, instead it appends new output each time. And maybe, if it's not difficult, to resize terminal UI, when a terminal is resized.
Also, I see that it outputs CLI version at the top, but because of this issue it's not visible, because it just stays on top of the output history

https://github.com/user-attachments/assets/9dd1c03c-eee3-4d95-abfb-c337ac20bf59

I don't have a lint rule for `console.log`, instead there's a Typescript error. I think people would still like to use console.log for debugging. Or maybe include logger.log in example 

изображение


More serious:
Entering `q` or `Ctrl+C` doesn't kill tsc and n8n at least on Windows, so they hang as background processes and starting n8n-node dev does not work, because the port is being used. The node-cli starts jumping wildly and server output doesn't show the error.

изображение

https://github.com/user-attachments/assets/a7aa2d09-59fc-4577-b909-d79a09dde33b

File: packages/@n8n/node-cli/src/commands/dev/utils.ts [hunk 2]
```diff
@@ -1,148 +1,413 @@
...
+}
 
-	const handleSignal = (signal: 'SIGINT' | 'SIGTERM'): void => {
-		if (isShuttingDown) {
-			// Second signal - force kill immediately
-			console.log('\nForce killing processes...');
-			forceKillAllChildren();
-			return;
+export function openUrl(url: string): void {
+	const command =
```
Comment (yehorkardash) [inline packages/@n8n/node-cli/src/commands/dev/utils.ts]: nit: not a fan of nested ternaries, maybe create getUrlOpenCommand = () => {} instead

File: packages/@n8n/node-cli/src/commands/dev/utils.ts [hunk 3]
```diff
@@ -1,148 +1,413 @@
...
+	};
 
-	const stripAnsiCodes = (input: string): string =>
-		input
-			.replace(/\x1Bc/g, '') // Full reset
-			.replace(/\x1B\[2J/g, '') // Clear screen
-			.replace(/\x1B\[3J/g, '') // Clear scrollback
-			.replace(/\x1B\[H/g, '') // Move cursor to top-left
-			.replace(/\x1B\[0?m/g, ''); // Reset colors
+	process.on('SIGINT', handleSignal);
```
Comment (yehorkardash) [inline packages/@n8n/node-cli/src/commands/dev/utils.ts:444]: Windows is tricky with signals so I am not 100% sure handleSignal is even called on windows. I saw some stackoverflow answers saying that it works, but nodejs docs say that it doesn't

изображение

File: packages/@n8n/node-cli/src/commands/dev/utils.ts [hunk 4]
```diff
@@ -1,148 +1,413 @@
...
-		(text: string): void => {
-			if (allowOutput && !allowOutput(text)) return;
+	const startRenderLoop = (): void => {
+		if (renderInterval !== null) return;
 
-			const prefix = name ? (color ? color(`[${name}]`) : `[${name}]`) : '';
-			console.log(prefix ? `${prefix} ${text}` : text);
-		};
+		if (process.stdin.isTTY) {
+			process.stdin.setRawMode(true);
```
Comment (yehorkardash) [inline packages/@n8n/node-cli/src/commands/dev/utils.ts]: Could it be caused by [this](https://nodejs.org/api/process.html#signal-events)?

> 'SIGINT' from the terminal is supported on all platforms, and can usually be generated with Ctrl+C (though this may be configurable). It is not generated when [terminal raw mode](https://nodejs.org/api/tty.html#readstreamsetrawmodemode) is enabled and Ctrl+C is used.

**Comment by yehorkardash** [comment]
Works really well! 🚀

However, I've noticed that next steps section suggests this command: `cd ./n8n-nodes-my-app && npm run dev`.
It doesn't use the new node-cli and Ctrl+C does not do anything. Not sure if that's in the scope of this PR


image

**Comment by elsmr** [comment]
Hey! I think it's expected because if you run `npm run dev` it uses `@n8n/node-cli` published on npm, that still has the old version of the `dev` command. This will be fixed once this version of the CLI is published.

**Review by yehorkardash — APPROVED** [review]
