### PR TITLE
fix(core): Use editor base URL for workflow and execution links

### LINKED ISSUE #22285: Workflow and past execution urls in context data use webhook url instead of editor url
### Bug Description

When setting up n8n with different webhook and editor urls, context data for past execution url in `error trigger` and link to workflow in `slack send message` use the webhook url instead of the editor url. This causes the links to not be usable for the end users, as it leads not found page instead of editor UI.

Also found those two things in n8n code that could be related: see [here](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/execution-lifecycle/execute-error-workflow.ts#L34) and [here](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/workflow-execute-additional-data.ts#L401)

Environment infos below are from local reproduction example, but same also happens on our self-hosted n8n v1.119.2 on Ubuntu 24.04

### To Reproduce

1. Set up n8n with different webhook and editor base urls, e.g.
```
docker run -it --rm \
 --name n8n \
 -p 5678:5678 \
 -e GENERIC_TIMEZONE="Europe/Berlin" \
 -e TZ="Europe/Berlin" \
 -e N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true \
 -e N8N_RUNNERS_ENABLED=true \
 -e WEBHOOK_URL="webhook.example.com" \
 -e N8N_EDITOR_BASE_URL="example.com" \
 -v n8n_data:/home/node/.n8n \
 docker.n8n.io/n8nio/n8n
```

2. Create a error workflow, e.g.
[Error Workflow.json](https://github.com/user-attachments/files/23746628/Error.Workflow.json)

3. Create a workflow that definitely fails, add the error workflow in settings, and activate it e.g.
[My workflow.json](https://github.com/user-attachments/files/23746633/My.workflow.json)

4. Trigger the workflow

5. Check execution logs of error workflow and see the `url` parameter uses the webhook url domain.
Image

Same happens for slack send message node when enabling the `Include Link to Workflow` option. The workflow link added to the slack message also uses webhook url.

### Expected behavior

urls use the editor base url, so accessing past execution or linked workflows also works when having different webhook and editor base urls.

### Debug Info

# Debug info

## core

- n8nVersion: 1.121.2
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-11-25T12:25:34.941Z

### Operating System

MacOS Tahoe 26.1

### n8n Version

1.121.2 

### Node.js Version

22.21.0

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by majiayu000**
## Summary

- Uses `getInstanceBaseUrl()` instead of `getWebhookBaseUrl()` for workflow execution URLs in error context data
- Ensures `instanceBaseUrl` in additional data uses the editor URL, not webhook URL
- Fixes links to workflows and past executions when webhook and editor URLs differ

## Test plan

- [x] Unit tests added for `executeErrorWorkflow` to verify correct URL construction
- [x] Updated existing tests for `getBase` to verify `instanceBaseUrl` uses editor URL
- [x] All existing tests pass
- [x] TypeScript checks pass
- [x] Linting passes

Fixes #22285

### CODE REVIEW

File: packages/cli/src/workflow-execute-additional-data.ts [hunk 1]
```diff
@@ -473,7 +467,7 @@ export async function getBase({
 		credentialsHelper: Container.get(CredentialsHelper),
 		executeWorkflow,
 		restApiUrl: urlBaseWebhook + globalConfig.endpoints.rest,
-		instanceBaseUrl: urlBaseWebhook,
+		instanceBaseUrl,
```
Comment (tomi) [inline packages/cli/src/workflow-execute-additional-data.ts]: This included the trailing slash before, but now when it comes from `getInstanceBaseUrl`, it no longer has it. This can break parts in the codebase where this is assumed (at least [here](packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts)). To keep this backwards compatible, let's ensure it still has the trailing `/`

**Review by tomi — CHANGES_REQUESTED** [review]
Thank you for your PR @majiayu000 

I left one comment that should be addressed before this can be merged

**Review by tomi — DISMISSED** [review]
LGTM now 👌 Thank you for addressing this 🫶

**Comment by tomi** [comment]
@majiayu000 there's a type error in the test file. Would you mind fixing that 🙏

**Comment by majiayu000** [comment]
Fixed the test type error in e5231b0 by adding the required `storedAt` field to the `IRun` fixtures.

Local checks passed:
- `pnpm turbo typecheck --filter=n8n`
- `pnpm --filter n8n test -- src/execution-lifecycle/__tests__/execute-error-workflow.test.ts --runInBand`

**Review by tomi — APPROVED** [review]
