### PR TITLE
fix(editor): Fix icon color on 'Call n8n Workflow Tool' node

### LINKED ISSUE #13538: The color of the Call n8n Workflow Tool icon has turned gray.
### Bug Description

In dark mode, the color of the Call n8n Workflow Tool icon has turned gray, whereas in previous older versions, it was white and very noticeable. The demonstration below illustrates this.

Image

### To Reproduce

1.see demo

### Expected behavior

it was white

### Operating System

windows 10

### n8n Version

1.81.0

### Node.js Version

18.16

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by Cadiac**
## Summary

On the v2 version of `Call n8n Workflow Tool` the color of the `Call n8n Workflow Tool` had changed dark on dark mode. The reason was missing `iconColor` on the new version of the node.

Before fix
image

With fix
image

## Related Linear tickets, Github issues, and Community forum posts

Linear issue: https://linear.app/n8n/issue/ADO-3286/community-issue-the-color-of-the-call-n8n-workflow-tool-icon-has
Fixes #13538

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/versionDescription.ts [hunk 1]
```diff
@@ -8,6 +8,7 @@ export const versionDescription: INodeTypeDescription = {
 	displayName: 'Call n8n Workflow Tool',
 	name: 'toolWorkflow',
 	icon: 'fa:network-wired',
+	iconColor: 'black',
```
Comment (netroy) [inline packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/versionDescription.ts:11]: please move these to `packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts` instead, and remove these lines from `packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v1/versionDescription.ts` as well.

**Review by netroy — CHANGES_REQUESTED** [review]

File: packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/versionDescription.ts (hunk 1 above)
Comment (Cadiac) [reply packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/versionDescription.ts]: Nice, moved `icon` and `iconColor` on the base node, seemed to work.

**Review by netroy — APPROVED** [review]
🎉

**Comment by janober** [comment]
Got released with [`n8n@1.82.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.82.0)
