### PR TITLE
Restore i18n post-UM

### LINKED ISSUE #3015: i18n locales loading is broken
**Describe the bug**
From the 0.165.0 version ([this](https://github.com/n8n-io/n8n/pull/2720) commit) is not working i18n localization files loading.
My localization file is placed in `packages/editor-ui/src/plugins/i18n/locales` directory as well. 
With the same environment and settings a localization loading is working in previous n8n versions (0.164.0 and lower)  
[Link](https://github.com/n8n-io/n8n/pull/2720#issuecomment-1073824020) to my comment from PR with my investigations.

**To Reproduce**
1. clone n8n `git clone https://github.com/n8n-io/n8n.git`
2. install all dependencies` lerna bootstrap --hoist`
3. copy localization file to `packages/editor-ui/src/plugins/i18n/locales`
4. set `N8N_DEFAULT_LOCALE=ja` to env
5. `npm run build`
6. `npm run start`

**Expected behavior**
n8n editor ui with settled language.

**Environment:**
 - OS: MacOS Catalina 10.15.7
 - n8n Version 0.165.0
 - Node.js Version -  v14.18.0
 - Additional ENVs - N8N_DEFAULT_LOCALE=ja

### PR DESCRIPTION
**Pull request by ivov**
To close #3015

### CODE REVIEW

File: packages/editor-ui/src/App.vue [hunk 1]
```diff
@@ -79,7 +80,7 @@ export default mixins(
 			}
 		},
 		logHiringBanner() {
-			if (!this.isHiringBannerEnabled && this.$route.name !== VIEWS.DEMO) {
+			if (this.isHiringBannerEnabled && this.$route.name !== VIEWS.DEMO) {
```
Comment (mutdmour) [inline packages/editor-ui/src/App.vue:83]: why did you change logic here?

File: packages/editor-ui/src/App.vue [hunk 2]
```diff
@@ -160,6 +161,9 @@ export default mixins(
 
 			this.trackPage();
 		},
+		'$store.getters.defaultLocale'(newLocale) {
```
Comment (mutdmour) [inline packages/editor-ui/src/App.vue:164]: did this not work?
```suggestion
		defaultLocale(newLocale) {
```

File: packages/editor-ui/src/plugins/i18n/locales/en.json [hunk 3]
```diff
@@ -1,1093 +1,717 @@
...
+	"tagsTable.createTag": "Create tag",
+	"tagsTable.deleteTag": "Delete tag",
+	"tagsTable.editTag": "Edit Tag",
+	"tagsTable.name": "@:reusableBaseText.name",
+	"tagsTable.noMatchingTagsExist": "No matching tags exist",
+	"tagsTable.saveChanges": "Save changes?",
+	"tagsTable.usage": "Usage",
+	"tagsTableHeader.addNew": "Add new",
+	"tagsTableHeader.searchTags": "Search Tags",
+	"tagsView.inUse": "{count} workflow | {count} workflows",
```
Comment (mutdmour) [inline packages/editor-ui/src/plugins/i18n/locales/en.json:543]: love that I can simply search for this now

File: packages/editor-ui/src/plugins/i18n/docs/ADDENDUM.md [hunk 4]
```diff
@@ -2,27 +2,33 @@
 
 ## Base text
```
Comment (mutdmour) [inline packages/editor-ui/src/plugins/i18n/docs/ADDENDUM.md:3]: thanks for updating the guide. can you also update section that says we should use first words of a message? I think I saw this in a previous PR. Instead names should be more descriptive.

File: packages/editor-ui/src/views/NodeView.vue [hunk 5]
```diff
@@ -2746,12 +2737,8 @@ export default mixins(
...
 
 				if (this.defaultLocale !== 'en') {
-					try {
-						const headers = await this.restApi().getNodeTranslationHeaders();
-						addHeaders(headers, this.defaultLocale);
-					} catch (_) {
-						// no headers available
-					}
+					const headers = await this.restApi().getNodeTranslationHeaders();
+					if (headers) addHeaders(headers, this.defaultLocale);
```
Comment (mutdmour) [inline packages/editor-ui/src/views/NodeView.vue:2741]: should not this be moved to App.vue? otherwise, won't apply if you load other pages

File: packages/editor-ui/src/App.vue (hunk 1 above)
Comment (ivov) [reply packages/editor-ui/src/App.vue:83]: With the original implementation, `export N8N_HIRING_BANNER_ENABLED=false` does not disable the banner.

File: packages/editor-ui/src/App.vue (hunk 2 above)
Comment (ivov) [reply packages/editor-ui/src/App.vue:164]: The watcher cannot read from the mapped getter directly:

image


Either using the full store path as I did, or adding an extra getter just for the watcher.

```js
defaultLocale(): string {
	return this.$store.getters.defaultLocale;
},
```

File: packages/editor-ui/src/plugins/i18n/locales/en.json (hunk 3 above)
Comment (ivov) [reply packages/editor-ui/src/plugins/i18n/locales/en.json:543]: :)

File: packages/editor-ui/src/plugins/i18n/docs/ADDENDUM.md (hunk 4 above)
Comment (ivov) [reply packages/editor-ui/src/plugins/i18n/docs/ADDENDUM.md:3]: That section was in [the other PR](https://github.com/n8n-io/n8n/pull/2693/files) that was not merged. I intentionally left that part out.

File: packages/editor-ui/src/views/NodeView.vue (hunk 5 above)
Comment (ivov) [reply packages/editor-ui/src/views/NodeView.vue]: I moved the headers up because they are used in credentials modal → `Details` → `Allow use by`. Otherwise they wouldn't be fetched if you look at this modal without first going through the canvas.

However, this surfaced an issue that the checkboxes after `Allow use by` are not getting shown if going directly from `/templates` to credentials modal and then to `Details`. I'm seeing this issue in English and non-English locales, so looks unrelated to i18n. Fix here or separately?

image
image

Comment (ivov) [reply packages/editor-ui/src/views/NodeView.vue]: Templates bug so will be fixed separately.

**Review by mutdmour — APPROVED** [review]

**Review by mutdmour — APPROVED** [review]

File: packages/cli/src/Server.ts [hunk 6]
```diff
@@ -1503,10 +1503,13 @@ class App {
 				async (req: express.Request, res: express.Response): Promise<object | void> => {
 					const packagesPath = pathJoin(__dirname, '..', '..', '..');
 					const headersPath = pathJoin(packagesPath, 'nodes-base', 'dist', 'nodes', 'headers');
+
+					if (!existsSync(`${headersPath}.js`)) return;
```
[the remark this answers is not in the document]
Comment (ivov) [reply packages/cli/src/Server.ts]: Thanks, switched to promisified `access`, still working:

image

[the remark this answers is not in the document]
Comment (janober) [reply packages/cli/src/Server.ts]: Great thanks for the fast fix!

**Comment by janober** [comment]
Got merged with #3097

**Comment by janober** [comment]
Thanks a lot. Got merged.
