### PR TITLE
fix(Notion (Beta) Node): Fix create database page fails if relation param is empty/undefined

### LINKED ISSUE #5050: Notion: Create page node fails when relation is empty
`n8n version : 0.209.3`

Hello, I am encoutering an issue with the Notion node to create a new database page.

## What I am trying to do

In my workflow, I need to create pages in a database in notion. This database has a field that is a `relation` to another database. The value for the relation is set using an expression as the data comes from another node. Sometimes that expression might result in `null`, `undefined` or an `empty array` as the relation id might not be available. I expect the page to be created without the relation to the other database.

## Issue

When the expression inside `Relation IDs` is not a valid UUID, the node throws an error and the page is not created. 

After some investigation, I understood that the problem was related to [this line of code ](https://github.com/n8n-io/n8n/blob/26e2321a710d7b42559492a6605cef3a248d918e/packages/nodes-base/nodes/Notion/GenericFunctions.ts#L287
).

``` javascript
value.relationValue.reduce((acc: [], cur: any) => {
    return acc.concat(cur.split(',').map((relation: string) => ({ id: relation.trim() })));
}, [])
```

When the expression is `null` or `undefined`, it is the piece of code above that throws an exception as the `cur` object is not a string. Calling the `split` function is impossible.

When the expression results in an `empty string` or an `empty array`, it is the call to the notion API that fails due to payload validation error: ```body failed validation: body.properties.Category.relation[0].id should be a valid uuid, instead was `""` ```
This is because in the piece of code above, the `split` function will always return an array with at least one empty string inside. Which will be tuned by the `map` function call to something like `{id: ""}` which is invalid for the API.

In both cases, the node will fail and the page will not be created. 

## Desired behaviour

The [notion API documentation](https://developers.notion.com/reference/property-value-object#relation-property-values) specifies that if the relation is empty, the value of that property should be an `empty array`. 

To fix this issue, you can modify the implementation of the Notion node as follows:
``` javascript
value.relationValue.reduce((acc: [], cur: any) => {
    // Check if cur is a string before calling split
    if (typeof cur === 'string') {
        return acc.concat(cur.split(',').map((relation: string) => ({ id: relation.trim() })));
    }
    // Return an empty array if cur is not a string
    return acc;
}, [])
```
This modification will check if the `cur` object is a string before calling the `split` function. If it is not a string, it will return an `empty array` instead of attempting to call split on it. This should prevent the error from occurring when the `Relation IDs` expression returns `null`, `undefined`, or an `empty array`.

### PR DESCRIPTION
**Pull request by maspio**
fixes: https://github.com/n8n-io/n8n/issues/5050

### CODE REVIEW

**Review by michael-radency — DISMISSED** [review]

File: packages/nodes-base/nodes/Notion/GenericFunctions.ts [hunk 1]
```diff
@@ -25,6 +26,22 @@ import moment from 'moment-timezone';
...
+	if (uuidValidate(value)) return true;
+	if (value.length == 32) {
+		//prettier-ignore
+		const strWithDashes = `${value.slice(0, 8)}-${value.slice(8, 12)}-${value.slice(12, 16)}-${value.slice(16, 20)}-${value.slice(20)}`;
+		if (uuidValidate(strWithDashes)) return true;
+	}
+	throw new NodeOperationError(
+		this.getNode(),
+		`The relation id "${value}" is not a valid uuid with optional dashes.`,
+	);
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Notion/GenericFunctions.ts:40]: throwing error here, instead returning false, could be breaking change for some workflows, in case of reported issue it would break user's workflow in case when relations are optional

**Review by michael-radency — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.212.1`
