### PR TITLE
fix(AI Agent Node): Fix tool calling when tools run in a loop

### LINKED ISSUE #14032: Tool Agent in the Loop using only first item
## Describe the problem/error/question
The agent retains or uses only the first index at the loop's prompt. The results the agent returns are always the same.

## What is the error message (if any)?
There is no error message.

## Please share your workflow/screenshots/recording

Image

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
⚠️ WARNING ⚠️ If you have sensitive data in your workflow (like API keys), please remove it before sharing.
```

### core

- n8nVersion: 1.82.3
- platform: npm
- nodeJsVersion: 20.18.3
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

### pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

### client

- userAgent: mozilla/5.0 (x11; linux x86_64) applewebkit/537.36 (khtml, like gecko) chrome/134.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-03-18T05:42:48.845Z}

### PR DESCRIPTION
**Pull request by ggozad**
## Summary

This PR fixes a long-standing issue of tools executed from an AI agent inside a loop (or with multiple invocations) always being passed the first item of the loop as args.

A workflow from @OlegIvaniv that covers related use cases is attached below:
[Agent_in_the_loop_Oleg.json](https://github.com/user-attachments/files/20119968/Agent_in_the_loop_Oleg.json)

Once this PR is merged the workflow should be included in the workflow tests.

## Related Linear tickets, Github issues, and Community forum posts

Closes #14032 
Resolves https://linear.app/n8n/issue/AI-917/community-issue-agent-in-the-loop
Resolves https://linear.app/n8n/issue/AI-927/bug-ai-agent-tool-logs-not-ordered-correctly-in-loops

## Review / Merge checklist

- [X] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [X] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/core/src/execution-engine/node-execution-context/supply-data-context.ts [hunk 1]
```diff
@@ -167,16 +167,18 @@ export class SupplyDataContext extends BaseExecuteContext implements ISupplyData
 		return super.getInputItems(inputIndex, connectionType) ?? [];
 	}
 
+	getLatestRunIndex(): number {
```
Comment (CharlieKolb) [inline packages/core/src/execution-engine/node-execution-context/supply-data-context.ts:170]: [I think I picked this, so doubly-sorry for the nit] I guess `nextRunIndex` is more accurate? Latest sounds like it might refer to the last one that already ran, rather than what will be the next one

File: packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts [hunk 2]
```diff
@@ -28,18 +28,22 @@ import type { ExecuteContext, WebhookContext } from '../../node-execution-contex
...
 	contextFactory: (runIndex: number) => ISupplyDataFunctions,
 	node: INode,
 	nodeType: INodeType,
+	runExecutionData: IRunExecutionData,
 ) {
 	/**
 	 * This keeps track of how many times this specific AI tool node has been invoked.
 	 * It is incremented on every invocation of the tool to keep the output of each invocation separate from each other.
 	 */
-	let toolRunIndex = 0;
```
Comment (CharlieKolb) [inline packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:40]: It occurs to me only now, but this might reintroduce the parallel execution issue I fixed a bit ago, albeit much more theoretically:

If two executions are triggered in parallel (as they do in one of the workflows I provided), we may end up using the same runIndex here if there is a time frame where the second run reaches this code before the first run is started - I don't know how realistic this is, or how to avoid it though.

My previous problematic version only incremented the runIndex after execution, which was much more trivially incorrect.

Comment (CharlieKolb) [reply packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:40]: Maybe `let toolRunIndex = getPreviousRunIndex();` outside the arrow function and then incrementing it from there is the best combination? One could still construct an example where this goes wrong, with multiple agents, some in a loop, running the same tool.

Comment (ggozad) [reply packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:40]: All my test cases (including your workflows) would pass fine, but it looks safer with your update. Let me know if you think something else is required here.

File: packages/core/src/execution-engine/node-execution-context/supply-data-context.ts [hunk 3]
```diff
@@ -167,16 +167,18 @@ export class SupplyDataContext extends BaseExecuteContext implements ISupplyData
 		return super.getInputItems(inputIndex, connectionType) ?? [];
 	}
 
+	nextRunIndex(): number {
```
Comment (CharlieKolb) [inline packages/core/src/execution-engine/node-execution-context/supply-data-context.ts:170]: Ah sorry, I meant `getNextRunIndex`, I could have been clearer 👉 👈 😓

File: packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts (hunk 2 above)
Comment (CharlieKolb) [reply packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:40]: @netroy please take a look here as well 🙏

Comment (netroy) [reply packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:40]: > If two executions are triggered in parallel

each execution gets a new instance of `WorkflowExecute`. Did you mean parallel invocation of a tool within a single execution?

File: packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts [hunk 4]
```diff
@@ -28,19 +28,28 @@ import type { ExecuteContext, WebhookContext } from '../../node-execution-contex
 // eslint-disable-next-line import/no-cycle
 import { SupplyDataContext } from '../../node-execution-context/supply-data-context';
 
+function getNextRunIndex(runExecutionData: IRunExecutionData, nodeName: string) {
```
Comment (netroy) [inline packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:31]: can we avoid this duplication and use `getNextRunIndex` from the context instead?

**Review by netroy — CHANGES_REQUESTED** [review]
some of these changes can be reverted https://github.com/n8n-io/n8n/compare/ai-917-community-issue-agent-in-the-loop...pr-15250-suggestions?expand=1

File: packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts (hunk 2 above)
Comment (CharlieKolb) [reply packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:40]: Yes, sorry, two node invocations.

File: packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts (hunk 4 above)
Comment (ggozad) [reply packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts:31]: I am not sure how, it looks to me like a chicken-and-the-egg problem :)
I tried to do something like 
```js
	const tempContext = new SupplyDataContext(
		{} as Workflow,
		node,
		{} as IWorkflowExecuteAdditionalData,
		'internal' as WorkflowExecuteMode,
		runExecutionData,
		0,
		[] as INodeExecutionData[],
		{} as ITaskDataConnections,
		NodeConnectionTypes.AiTool,
		{} as IExecuteData,
		[] as CloseFunction[],
	);
	let runIndex = tempContext.getNextRunIndex();
```
but that just looks sad :( 

Happy to remove the function (it's really only called in here) and do 
```js
let runIndex = runExecutionData.resultData.runData[node.name]?.length ?? 0;
```

but is there another way?

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.94.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.94.0)
