### PR TITLE
fix: Remove SystemCredentials source check during AWS role assume

### LINKED ISSUE #21961: AWS (Assume Role) Credential Not Working in Workflows
### Bug Description

This is in relation to the new AWS (Assume Role) Credential introduced in this PR and became available in 1.119.0:

https://github.com/n8n-io/n8n/pull/20626

When creating the credential when using AWS System Credentials to assume the IAM Role, the credential "test" passes and the provided IAM Role is properly assumed. However, when the credential is actually used in a workflow node, the credential **attempts to directly use the AWS System Credential** rather than using the System Credential to assume the role.

**There are also internal security implications for this**, because this means that n8n users of an instance can use this credential to access the AWS system credential. This means if the admin has, for example, configured the n8n AWS instances/containers to access things like Secrets Manager or S3 for binary data in workflows, n8n users could configure a credential and then be able to access items they should not be able to (for example, binary data from any workflow in the s3 bucket configured in the n8n instance).

### To Reproduce

1. Configure n8n instance with AWS System Credentials with permission to assume another IAM Role
2. Create a new AWS (Assume Role) Credential
3. Select the "Use System Credentials" option
4. Configure AWS IAM Role that can be assumed by the AWS System Credentials with an External ID (should be able to use the AWS IAM Role Wizard for this
5. Save the credential and make sure the Connection Test passes
6. Configure a workflow with a node like S3->Download File
7. You should see an error like `AccessDeniedUser: <arn_for_system_cred_role_session> is not authorized to perform ...`

### Expected behavior

The error outlined in 7.) above indicates that the node is attempting to use the AWS System Credential directly. The IAM Role configured in the credential is not being assumed before trying to run the actual action.

The expected behavior is that the system credential should assume the provided role, not be used directly to attempt to perform the action.

### Debug Info

# Debug info

## core

- n8nVersion: 1.119.1
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: postgres
- executionMode: scaling (multi-main)
- concurrency: -1
- license: enterprise (production)
- consumerId: c8093090-c197-434f-847b-d1b2c756f509

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: s3

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-11-17T19:52:50.052Z

### Operating System

Docker

### n8n Version

1.119.1

### Node.js Version

22.21.0

### Database

PostgreSQL

### Execution mode

queue

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by onyxraven**
## Summary

This removes the 'source === "environment"' check done during the role assume for AWS SystemCredentials.

In every case of the SystemCredentials usage for AWS, it is supposed to assume the role required during credential setup (with the given externalId as well). The previous conditional would only do that assume if it was via environment. This left out the (recently added) pod, container, and instance sources, and those would return the system credentials instead (unintended, I think, and a **potential security risk**). These sources should act the same way.

I added a test using one of the other sources, and red-green tested. I've also tested this "in practice" along with my other PR (#22316) in our environment.

## Related Linear tickets, Github issues, and Community forum posts

Fixes #21961

(https://linear.app/n8n/issue/GHC-5527)

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/credentials/common/aws/system-credentials-utils.ts [hunk 1]
```diff
@@ -3,15 +3,15 @@ import { Container } from '@n8n/di';
 import { ApplicationError } from 'n8n-workflow';
 
 type Resolvers = 'environment' | 'podIdentity' | 'containerMetadata' | 'instanceMetadata';
-type RetrunData = {
+type ReturnData = {
```
Comment (onyxraven) [inline packages/nodes-base/credentials/common/aws/system-credentials-utils.ts:7]: While stepping through understanding, noticed this misspelling. This type is not exported and only used below.

File: packages/nodes-base/credentials/common/aws/utils.test.ts [hunk 2]
```diff
@@ -113,6 +113,82 @@ describe('assumeRole', () => {
 			);
 		});
 
+		it('should successfully assume role using system credentials by instanceMetadata', async () => {
```
Comment (onyxraven) [inline packages/nodes-base/credentials/common/aws/utils.test.ts:116]: Ultimately, this could (should?) iterate through each source type and ensure it behaves as intended.

**Comment by onyxraven** [comment]
This has been rebased against n8n master as of today.

* [x] pnpm build 
* [x] (cd packages/node-base; pnpm test)

**Comment by darkgoldxp** [comment]
Hello @onyxraven 

I habe a problem with EKS Pod Identity.
I test that since https://github.com/n8n-io/n8n/pull/21584 is merged in version 2.1.0

All my conf is OK and I can assume role on the pod using CLI but not on n8n (Failed to assume role: System AWS credentials are required for role assumption. Please ensure AWS credentials are available via environment variables, instance metadata, or container role.)

Logs in the pod-identity-agent is : 
{"client-addr":"<IP>:<PORT>","cluster-name":"<CLUSTER_NAME>","level":"info","msg":"handling new request request from <IP>:<PORT>","time":"2025-12-23T14:16:38Z"}
{"client-addr":"<IP>:<PORT>","cluster-name":"<CLUSTER_NAME>","level":"error","msg":"Error fetching credentials: Service account token cannot be parsed: token is malformed: could not base64 decode header: illegal base64 data at input byte 6","time":"2025-12-23T14:16:38Z"}

For validate assume role is OK in CLI I do : 
export EKS_TOKEN_CLEAN=$(cat $AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE | tr -d ' \n\r')
curl -v -H "Authorization: $EKS_TOKEN_CLEAN" http://169.254.170.23/v1/credentials

Your pull request can fix my problem ?

**Review by ShireenMissi — APPROVED** [review]
Tested locally and it works as expected ✅

**Review by ShireenMissi — DISMISSED** [review]

**Review by shortstacked — DISMISSED** [review]

**Review by shortstacked — APPROVED** [review]

**Review by shortstacked — APPROVED** [review]
