### PR TITLE
fix(AWS DynamoDB Node): Incorrect parameter names

### LINKED ISSUE #14625: AWS DynamoDB Node Incorrect Parameter Case (ExpressionAttributeNames)
### Bug Description

When using the AWS DynamoDB node, the parameter ExpressionAttributeNames is incorrectly set in lowercase (expressionAttributeNames), causing AWS errors when performing DynamoDB operations such as get, delete, and upsert. 

The AWS API expects the casing as defined in the [AWS DynamoDB documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html).

### To Reproduce

1. Create a DynamoDB node operation (get, delete, or upsert) in n8n. **NOTE: GetAll/Get Many is working.**
2. Provide ExpressionAttributeNames in the additional fields (e.g. Key: #n Value: name ) and referencing them in the Projection Expression(e.g #n)
3. Execute the node.

### Expected behavior

The DynamoDB node should correctly set the parameter as ExpressionAttributeNames.

### Operating System

Docker Image  n8nio/n8n:latest

### n8n Version

1.88.0

### Node.js Version

v20.19.0

### Database

PostgreSQL

### Execution mode

queue

### PR DESCRIPTION
**Pull request by RomanDavydchuk**
## Summary

Update the AWS DynamoDB Node to use the proper parameter names (`ExpressionAttributeNames` instead of `expressionAttributeNames`). Fix the reference to `additionalFields.conditionExpression` and the names of "Expression Attribute Values" fields

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-3105/community-issue-aws-dynamodb-node-incorrect-parameter-case
Closes #14625

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts [hunk 1]
```diff
@@ -404,7 +404,7 @@ export const itemFields: INodeProperties[] = [
 			},
 			{
 				displayName: 'Expression Attribute Values',
-				name: 'expressionAttributeUi',
+				name: 'eavUi',
 				description:
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts]: renaming attribute is breaking change, I would suggest to leave names unchanged and fix this in code, otherwise you would need to version this change

File: packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts [hunk 2]
```diff
@@ -417,8 +417,8 @@ export const itemFields: INodeProperties[] = [
 				},
 				options: [
 					{
-						name: 'expressionAttributeValues',
-						displayName: 'Expression Attribute Vaue',
+						name: 'eavValues',
+						displayName: 'Expression Attribute Value',
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts]: same here

**Review by michael-radency — CHANGES_REQUESTED** [review]

File: packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts (hunk 1 above)
Comment (RomanDavydchuk) [reply packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts]: Fixed

**Review by michael-radency — APPROVED** [review]
LGTM

**Comment by janober** [comment]
Got released with [`n8n@1.100.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.100.0)

**Comment by jakefromstatefarm-ig** [comment]
Kelseyntay or kelseyandjenorkelseylisatay
