### PR TITLE
fix(editor): Stop listening button not working in NDV

### LINKED ISSUE #6810: Triggers in manual mode hang if event is never emitted
**Describe the bug**
For triggers that implement `trigger(this: ITriggerFunctions)`, when you run them in manual mode (eg for testing while building a workflow), they normally run until a single event is emitted and then stop. If you instead click "Stop Listening" in the UI, the app hangs waiting for the single event to come, when instead it should probably call `closeFunction()` and exit.

**To Reproduce**
1. Create a new workflow
2. Create a `Local File Trigger`
3. Select `Changes to a specific file` and enter any file path
4. Click `Listen for Event`
5. Click `Stop Listening`
6. Nothing happens - the workflow hangs waiting for a event

**Expected behavior**
I expect the trigger to stop listening and go back to edit mode.

**Environment (please complete the following information):**

- OS: maxOS 13.5
- n8n Version [e.g. 1.0.1]: master commit 7832e9c12d680229ed7b59df8d6b053877c14210 (July 31)
- Node.js Version [e.g. 18.16.0]: v18.15.0
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]: Postgres
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]: main

**Additional context**
This seems to be true across multiple Triggers - I just used Local File Trigger because it's easy to test with.

### PR DESCRIPTION
**Pull request by MiloradFilipovic**
## Summary
The `Stop Listening` button in trigger panel click wasn't wired to anything (was emitting an event that wasn't handled anywhere).
This PR extracts the logic to stop the current execution into the composable which is then used by buttons on Node View and Trigger panel.

## Related tickets and issues
Fixes #6810 
Fixes ADO-955

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

File: packages/editor-ui/src/views/NodeView.vue [hunk 1]
```diff
@@ -1930,67 +1929,8 @@ export default defineComponent({
...
-					this.showMessage({
-						title: this.$locale.baseText('nodeView.showMessage.stopExecutionCatch.title'),
-						message: this.$locale.baseText('nodeView.showMessage.stopExecutionCatch.message'),
-						type: 'success',
-					});
-				} else {
-					this.showError(error, this.$locale.baseText('nodeView.showError.stopExecution.title'));
-				}
-			}
+			await this.stopCurrentExecution();
```
Comment (mutdmour) [inline packages/editor-ui/src/views/NodeView.vue:1932]: thank you for refactoring this out

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.36.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.36.0)
