### PR TITLE
fix(Google BigQuery Node): Prevent infinite loop on job fail

### LINKED ISSUE #17095: BigQuery node can run endless and workflow timeout is ignored
### Bug Description

I discovered that my generated queries once run the node forever, ignores the workflow timeout and filled my queue 

... leaving no space for any other executions ... disaster, you imagine  :(

My generated query has an issue in the field description part of a create table. Executing this in BigQuery via console, reports an error.

```sql
CREATE OR REPLACE TABLE `<dataset>.bq_issue`
  # Case 1: undefined type
  # (
  # id undefined OPTIONS(description="Issue wrong type but no error, runs forever"),
  # )
  # Case 2: not matching results
  # (
  # id INTEGER OPTIONS(description=""),
  # not_in_select INTEGER OPTIONS(description="Issue wrong number of results but no error, runs forever"),
  # )
  OPTIONS (
    description = "Issue Table"
  )
AS
  SELECT
    id,
  FROM 
    UNNEST([1, 2, 3]) AS id

```

### To Reproduce

1. Create a workflow
2. In setting configure an error workflow and set timeout to 2 minutes or so
3. Add manual trigger 
4. Add a big query node, set valid the credentials and a project 
5. Paste above query
6. Execute node

# Debug info

## core

- n8nVersion: 1.100.1
- platform: docker (self-hosted)
- nodeJsVersion: 22.16.0
- database: postgres
- executionMode: scaling (single-main)
- concurrency: -1
- license: enterprise (production)

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 0 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/605.1.15 (khtml, like gecko) version/18.5 safari/605.1.15
- isTouchDevice: false

Generated at: 2025-07-08T06:56:51.319Z

### Expected behavior

I would expect:
1) node stops with error and calls error workflow
2) even if a node runs endless it **must** respect the workflow timeout and call an error to release the queue

### Operating System

Ubuntu Linux

### n8n Version

1.100.1

### Node.js Version

22.16.0

### Database

PostgreSQL

### Execution mode

queue

### PR DESCRIPTION
**Pull request by yehorkardash**
## Summary

This PR fixes an infinite loop issue, which occurred when the node was using "Continue on fail" and the error happened in try..catch block that handles jobs. `completedJobs` never got updated and the node got into infinite loop.

### How to test
1. Prepare Bigquery credentials
2. Create a dataset
3. Set execution mode to "Continue on Fail"
4. Paste the following code:
```
CREATE OR REPLACE TABLE `PROJECT_ID.DATASET_ID.test_table`
  (
    id INTEGER OPTIONS(description=""),
   not_in_select INTEGER OPTIONS(description="Issue wrong number of results but no error, runs forever"),
  )
AS
  SELECT
    id,
  FROM 
    UNNEST([1, 2, 3]) AS id
```
5. Execute the node
6. It should fail and return error object

## Related Linear tickets, Github issues, and Community forum posts

closes #17095
https://linear.app/n8n/issue/NODE-3277/community-issue-bigquery-node-can-run-endless-and-workflow-timeout-is

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

---

> [!NOTE]
> Prevents endless polling by marking failed/completed BigQuery jobs as settled and stopping when execution is canceled; adds tests covering continue-on-fail behavior.
> 
> - **Google BigQuery V2 `executeQuery`**:
>   - Replace `completedJobs` with `settledJobs` to remove jobs on success or error, preventing infinite polling.
>   - Add `abortSignal` check to break the polling loop when execution is canceled.
>   - When `continueOnFail` is enabled, push error items and mark jobs as settled.
> - **Tests**:
>   - Add `test/v2/node/executeQueryContinueOnJobFail.test.ts` with nock mocks to simulate a job error.
>   - Add workflow fixture `test/v2/node/executeQueryContinueOnJobFail.workflow.json` exercising continue-on-fail path.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 2d048d268a504b03e551ed00192c069e5db18449. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by michael-radency** [comment]
@claude review

File: packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts [hunk 1]
```diff
@@ -449,9 +451,12 @@ export async function execute(this: IExecuteFunctions): Promise<INodeExecutionDa
 			}
 		}
 
-		jobs = jobs.filter((job) => !completedJobs.includes(job.jobId));
+		jobs = jobs.filter((job) => !settledJobs.includes(job.jobId));
 
 		if (jobs.length > 0) {
+			if (abortSignal?.aborted) {
+				break;
+			}
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts]: should we fail earlier at the beginning of for loop?
```
for (const job of jobs) {
	if (abortSignal?.aborted) break;

	...
}
```

File: packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts [hunk 2]
```diff
@@ -401,7 +402,10 @@ export async function execute(this: IExecuteFunctions): Promise<INodeExecutionDa
 
 	let waitTime = 1000;
 	while (jobs.length > 0) {
-		const completedJobs: string[] = [];
+		if (abortSignal?.aborted) {
+			break;
+		}
+		const settledJobs: string[] = [];
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts]: I will still suggest to do this in `for` loop to catch `aborted` during iteration
you could name outer `while` loop and break it in `for` loop
```
outerLoop: while (

...
in for
break outerLoop;
```

**Review by michael-radency — APPROVED** [review]
thanks for updating 👍 , LGTM
