### PR TITLE
fix(core): Proxy all HTTP traffic instead of only axios

### LINKED ISSUE #17495: RSS and Gemini Model module is not using proxy
### Bug Description

docker  n8n version 1.102.4

proxy setting:
      - HTTP_PROXY=http://192.168.123.170:20170
      - HTTPS_PROXY=http://192.168.123.170:20170
      - http_proxy=http://192.168.123.170:20170
      - https_proxy=http://192.168.123.170:20170
      - ALL_PROXY=http://192.168.123.170:20170

http request is ok。  RSS node 、Google Gemni Model not valid

### To Reproduce

Create Credential for Ollama
Deploy a AI Agent
Use Google Gemni Model as Chat Model

### Expected behavior

use Google Gemni Model with http proxy

### Operating System

docker

### n8n Version

1.102.4

### Node.js Version

v22.17.0

### Database

SQLite (default)

### Execution mode

main (default)

### LINKED ISSUE #19652: RSS Read node is not using HTTP_PROXY / HTTPS_PROXY
### Bug Description

I am using HTTP_PROXY / HTTPS_PROXY environment variables in my n8n instance.

But the RSS nodes do no pass the request through HTTP_PROXY / HTTPS_PROXY 

When I tried the same request using HTTP node, it went through the proxy I configured. Upon inspecting further, it seems the rss-parser library which the RSS node doesn't use proxy environment variables. 

### To Reproduce

1. Configure a proxy values in your n8n environment file
2. Make request using RSS Read node to an rss feed. Check the logs of your proxy endpoint, indicating that proxy was not used.
3. Make request using HTTP node. You will see the request in proxy endpoint logs. 

### Expected behavior

RSS Node to use proxy for making request

### Debug Info

# Debug info

## core

- n8nVersion: 1.107.3
- platform: docker (self-hosted)
- nodeJsVersion: 22.17.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/140.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-09-17T12:17:14.087Z

### Operating System

Ubuntu 24.04.2 LTS

### n8n Version

1.107.3

### Node.js Version

22.17.0

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by elsmr**
## Summary

Implements HTTP proxy support for all Node.js HTTP traffic using `HTTP_PROXY`, `HTTPS_PROXY`, `ALL_PROXY`, and `NO_PROXY` environment variables.

**Previous implementation**: Proxy support was limited to n8n's request utilities (`httpRequest`) and axios requests via interceptors.

**This PR**: Extends proxy support to all native Node.js `http`/`https` requests by configuring global agents, including third-party libraries like `rss-parser` used by the RSS Read node.

- Configures global `http.globalAgent` and `https.globalAgent` with proxy support
- Respects standard proxy environment variables and `NO_PROXY` exclusions

### Limitations

Some requests may still bypass the proxy:
- Libraries using alternative HTTP clients (e.g., `undici`)
- Libraries explicitly overriding the default agent

### Testing

1. Set up local proxy (e.g., tinyproxy)
2. Test with various combinations of `HTTP_PROXY`, `HTTPS_PROXY`, `ALL_PROXY`, `NO_PROXY`
3. Verify RSS Read node and other HTTP-dependent nodes respect proxy settings
4. Confirm `NO_PROXY` patterns work correctly

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-3666/community-issue-rss-read-node-is-not-using-http-proxy-https-proxy
fixes #19652 
fixes #17495

### CODE REVIEW

File: packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts [hunk 1]
```diff
@@ -89,109 +87,71 @@ axios.defaults.proxy = false;
...
-): AxiosRequestConfig => {
-	if (protocol === 'http') {
-		config.httpAgent = agent;
-	} else {
-		config.httpsAgent = agent;
-	}
+	agentOptions?: AgentOptions,
+	proxyConfig?: IHttpRequestOptions['proxy'] | string,
+): void {
+	if (config.httpAgent || config.httpsAgent) return;
```
Comment (RomanDavydchuk) [inline packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:136]: Looks like if only one of the agents is set, we don't do anything even if the other agent is not set, is this behavior expected?

File: packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts [hunk 2]
```diff
@@ -89,109 +87,71 @@ axios.defaults.proxy = false;
...
-	return config;
-};
+	const customProxyUrl = getUrlFromProxyConfig(proxyConfig);
+
+	const targetUrl = buildTargetUrl(config.url, config.baseURL);
+
+	if (!targetUrl) return;
+
+	config.httpAgent = createHttpProxyAgent(customProxyUrl, targetUrl, agentOptions);
+	config.httpsAgent = createHttpsProxyAgent(customProxyUrl, targetUrl, agentOptions);
```
Comment (RomanDavydchuk) [inline packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:145]: Is it okay to set both agents here? In the previous implementation there was a check for the protocol

File: packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts [hunk 3]
```diff
@@ -230,22 +190,21 @@ const getBeforeRedirectFn =
...
-		}
+		// Create both agents and set them
+		const targetUrl = redirectedRequest.href;
+		const httpAgent = createHttpProxyAgent(customProxyUrl, targetUrl, redirectAgentOptions);
+		const httpsAgent = createHttpsProxyAgent(customProxyUrl, targetUrl, redirectAgentOptions);
 
+		redirectedRequest.agent = redirectedRequest.href.startsWith('https://')
+			? httpsAgent
+			: httpAgent;
+		redirectedRequest.agents = { http: httpAgent, https: httpsAgent };
```
Comment (RomanDavydchuk) [inline packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:205]: Same here, is it okay to set both agents?

**Review by RomanDavydchuk — COMMENTED** [review]
Tested manually with all env vars in different combinations, works as expected 🎉 

Have a few small questions regarding implementation, not something that should be changed, just wanted to clear things out

File: packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts (hunk 1 above)
Comment (elsmr) [reply packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:136]: Yes, if either agent is explicitly set, we assume the caller knows what they're doing and don't override it. I don't think we ever set this in the codebase though

File: packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts (hunk 2 above)
Comment (elsmr) [reply packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts:145]: Yes, `axios` automatically uses the correct agent based on the protocol. Setting both handles redirects that change protocols (http → https or reverse).

**Review by RomanDavydchuk — APPROVED** [review]
LGTM

**Comment by Joffcom** [comment]
Got released with [`n8n@1.117.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.117.0)
