### PR TITLE
fix(HTTP Request Node): Cleanup circular references in response

### LINKED ISSUE #6046: Execute Workflow Node : Converting circular structure to JSON
**Describe the bug**
I have a workflow running a subprocess (using Execute workflow) which use to run fine for over a year.
Since latests update (can't tell which one as I made a jump from 210 to 224) this workflow throws a "Converting circular structure to JSON"
The sub process does not produce any error.

Here is the full error thrown : 
`TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Object'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at process.target._send (node:internal/child_process:847:17)
    at process.target.send (node:internal/child_process:747:19)
    at /usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:257:17
    at new Promise (<anonymous>)
    at sendToParentProcess (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:256:12)
    at Object.additionalData.executeWorkflow (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:169:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/ExecuteWorkflow/ExecuteWorkflow.node.js:172:34)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:653:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:592:53`

**To Reproduce**
Not sure how to reproduce.
The sub process may produce different output (some of them are HTTP request)

**Expected behavior**
No error ?

**Environment (please complete the following information):**

- OS: Official Docker image n8nio/n8n:0.224.1
- n8n Version : 0.224.1
- Node.js Version : v16.19.1
- Database system : mysql
- Operation mode: own

### PR DESCRIPTION
**Pull request by airmoi**
fix #6046: cleanup response.reason from any circular reference before returning data

### CODE REVIEW

**Comment by airmoi** [comment]
This fix incorporates two functions, 'removeCircularRefs' and 'isTraversableObject,' sourced from 'workflow/src/NodeErrors.ts.' While I initially defined them in '@utils/utilities,' I am considering the possibility of moving them to 'n8n-workflow/utilities' to enable code sharing between 'NodeErrors' and other affected nodes dealing with circular conversion issues.

File: packages/nodes-base/utils/utilities.ts [hunk 1]
```diff
@@ -234,3 +235,37 @@ export function getResolvables(expression: string) {
 
 	return resolvables;
 }
+
+export const isTraversableObject = (value: any): value is JsonObject => {
```
Comment (netroy) [inline packages/nodes-base/utils/utilities.ts:239]: instead of duplicating these, I'd recommend extracting `isTraversableObject`/`removeCircularRefs` out from `packages/workflow/src/NodeErrors.ts` into `packages/workflow/src/utils.ts`.
Either that, or we need to make sure that `response.reason` is always a `NodeApiError` (which should automatically take care of circular references, instead of having to manually do this in every node).

**Review by netroy — CHANGES_REQUESTED** [review]

File: packages/nodes-base/utils/utilities.ts (hunk 1 above)
Comment (airmoi) [reply packages/nodes-base/utils/utilities.ts:239]: Ok that's what I suggested too.
In that particular case, the `response.reason` is not converted to a `NodeApiError` because of the `continueOnFail` options. It is passed directly as a node item. That's why it is not cleaned up.
I think converting `response.reason` to `NodeApiError` may leads to a lots of side effects, but we could a least "clean" the circular references at source

**Review by netroy — DISMISSED** [review]
👍🏽

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@0.236.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.236.1)

**Comment by bramkn** [comment]
Hi @netroy 

I am still getting the circular references error after this update. Is there anything I can do to fix this issue?

**Comment by netroy** [comment]
@bramkn are you able to reproduce this in a minimal workflow that you could share with us?

**Comment by bramkn** [comment]
@netroy I was able to reproduce in a workflow with just this node, but sadly it is an api call of a client which I cannot share.
As the response format being text for a json response was the cause of it (changing the response format fixed it)
It was a json with a few nested objects and such, so maybe that would be what is causing it. Hope it helps
