### PR TITLE
fix: Admin should be able to install community nodes

### LINKED ISSUE #24797: Cant install community node as admin
## Describe the problem/error/question
Cant install community node as admin in enterprise edition 

## What is the error message (if any)?
Contact System Admin to install community node

## Please share your workflow/screenshots/recording

Image

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
⚠️ WARNING ⚠️ If you have sensitive data in your workflow (like API keys), please remove it before sharing.
```

### core

- n8nVersion: 2.4.5
- platform: docker (cloud)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: 200
- license: enterprise (production)

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 720 hours
- maxCount: 25000 executions

### client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/144.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2026-01-23T18:34:42.362Z}

### PR DESCRIPTION
**Pull request by dlavrenuek**
## Summary

Fixes a bug that prevented instance admin from installing community packages. The admin role already had the permissions (scope) to install packages but it was not reflected in the UI

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-4258/community-issue-cant-install-community-node-as-admin
Fixes #24797

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/features/settings/communityNodes/composables/useInstallNode.ts [hunk 1]
```diff
@@ -56,7 +57,7 @@ export function useInstallNode() {
 	};
 
 	const installNode = async (props: InstallNodeProps): Promise<InstallNodeResult> => {
-		if (!isOwner.value) {
+		if (!canInstallNodes.value) {
 			const error = new Error('User is not an owner');
```
Comment (RomanDavydchuk) [inline packages/frontend/editor-ui/src/features/settings/communityNodes/composables/useInstallNode.ts]: I think we should update the error message to be in line with new behavior:
```suggestion
			const error = new Error('User is not an owner or an admin');
```

**Review by RomanDavydchuk — CHANGES_REQUESTED** [review]
Mostly looks good, left one small comment about the error message. More importantly, for the state when the community node is not installed in the node creator, I still don't see the install button, although the banner to contact the admin has disappeared. I think we should also update `CommunityNodeDetails.vue`

Viewing as instance owner:
Image

Viewing as admin:
Image

File: packages/frontend/editor-ui/src/features/settings/communityNodes/composables/useInstallNode.ts (hunk 1 above)
Comment (dlavrenuek) [reply packages/frontend/editor-ui/src/features/settings/communityNodes/composables/useInstallNode.ts]: @RomanDavydchuk I did search through the code base and found/updated more places with owner checks related to node installation/management. Now the admin will also see the buttons to manage and update nodes - they already had the rights to do so (in the backend/role/scope), it was only not displayed.

File: packages/frontend/editor-ui/src/features/settings/communityNodes/composables/useInstalledCommunityPackage.ts [hunk 2]
```diff
@@ -51,7 +51,7 @@ export function useInstalledCommunityPackage(nodeTypeName?: MaybeRefOrGetter<str
 	const isUpdateCheckAvailable = computed(() => {
 		return (
 			isCommunityNode.value &&
-			usersStore.isInstanceOwner &&
+			usersStore.isAdminOrOwner &&
```
[the remark this answers is not in the document]
Comment (dlavrenuek) [reply packages/frontend/editor-ui/src/features/settings/communityNodes/composables/useInstalledCommunityPackage.ts:54]: This suggestion is wrong. `usersStore` is a reactive object, but it's not a ref, neither is `isAdminOrOwner`. `isAdminOrOwner` will always have the correct/updated value when used directly from `usersStore.isAdminOrOwner` but not when using f.e. destructuring

File: packages/frontend/editor-ui/src/features/shared/nodeCreator/components/Modes/ActionsMode.vue [hunk 3]
```diff
@@ -44,7 +44,7 @@ const emit = defineEmits<{
 const telemetry = useTelemetry();
 const i18n = useI18n();
 
-const { userActivated, isInstanceOwner } = useUsersStore();
+const usersStore = useUsersStore();
```
Comment (dlavrenuek) [inline packages/frontend/editor-ui/src/features/shared/nodeCreator/components/Modes/ActionsMode.vue:47]: With destructuring these values did lose reactivity, so it's possible that they are updated after the view was rendered, which was not reflected in the view

**Review by RomanDavydchuk — APPROVED** [review]
LGTM

**Review by reseteo152-stack — COMMENTED** [review]
ok
