### PR TITLE
fix(editor): Polyfill crypto.randomUUID

### LINKED ISSUE #12051: Error Message window.crypto.randomUUID
### Bug Description

I updated to the new latest which appeared as a popup (1.70.2) and now every click I do in workflows produces a popup message with: window.crypto.randomUUID is not a function. I am using the latest docker image.

CleanShot 2024-12-04 at 17 24 59

NodeViewSwitcher-BXWGR8PZ.js:33469 TypeError: window.crypto.randomUUID is not a function
    at Object.assignNodeId (index-BT7276bJ.js:205848:31)
    at resolveNodeData (NodeViewSwitcher-BXWGR8PZ.js:33643:41)
    at addNode (NodeViewSwitcher-BXWGR8PZ.js:33513:22)
    at addNodes2 (NodeViewSwitcher-BXWGR8PZ.js:33453:25)
    at async onAddNodesAndConnections (NodeViewSwitcher-BXWGR8PZ.js:35077:26)
addNodes2 @ NodeViewSwitcher-BXWGR8PZ.js:33469
await in addNodes2
onAddNodesAndConnections @ NodeViewSwitcher-BXWGR8PZ.js:35077
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
emit @ index-BT7276bJ.js:7027
nodeTypeSelected @ NodeCreation-CrD-YRlw.js:292
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
emit @ index-BT7276bJ.js:7027
selectNodeType @ NodeCreator-_l4IOkdC.js:1700
onSelected @ NodeCreator-_l4IOkdC.js:1735
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
emit @ index-BT7276bJ.js:7027
wrappedEmit @ NodeCreator-_l4IOkdC.js:1100
onClick @ NodeCreator-_l4IOkdC.js:1171
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
invoker @ index-BT7276bJ.js:9277
index-BT7276bJ.js:2227 TypeError: Cannot read properties of undefined (reading 'id')
    at onAddNodesAndConnections (NodeViewSwitcher-BXWGR8PZ.js:35115:54)

### To Reproduce

Go to workflow
Create a new workflow
Add first step
Choose any available

Popup message appears in the bottom right corner

### Expected behavior

Every step works

### Operating System

MacOS 15.1.1 Build: 24B91

### n8n Version

1.70.2

### Node.js Version

Node from Docker Image

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by netroy**
## Summary
When n8n is used in an insecure context, `window.crypto` is an empty object, because crypto API is only available in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).
This PR uses the `uuid` package to polyfill `crypto.randomUUID` for such cases.

## Related Linear tickets, Github issues, and Community forum posts

CAT-398
Fixes #12051

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by alexgrozav — APPROVED** [review]

File: packages/editor-ui/src/App.vue [hunk 1]
```diff
@@ -17,6 +18,11 @@ import { useSettingsStore } from '@/stores/settings.store';
 import { useHistoryHelper } from '@/composables/useHistoryHelper';
 import { useStyles } from './composables/useStyles';
 
+// Polyfill crypto.randomUUID
+if (!('randomUUID' in crypto)) {
+	Object.defineProperty(crypto, 'randomUUID', { value: uuid });
+}
```
Comment (alexgrozav) [inline packages/editor-ui/src/App.vue:24]: Just to be sure. The `window.crypto` object is always defined, and it's just `randomUUID` that's missing?

**Comment by janober** [comment]
Got released with [`n8n@1.70.3`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.70.3)
