### PR TITLE
fix(core): Fix task runner logging to browser console

### LINKED ISSUE #14815: After enabling Task runner, the code node console.log can only output strings, not objects/array structures
### Bug Description

After enabling Task runner, the code node console.log can only output strings, not objects/array structures.
Because debugging js is inconvenient, I set N8N_RUNNERS_ENABLED to false and it recovered.

Is there any way to enable it to output object and array type data normally after enabling it?

### To Reproduce

1. Enable task runner and set environment variable N8N_RUNNERS_ENABLED=true
2. Create a workflow and create a code node
3. Try to use console.log in the code node to print a deep object or a copied array
4. View the print result in the console

### Expected behavior

I hope that after starting Task Runner, I can use console.log to output objects and array structured data normally.

### Operating System

docker

### n8n Version

1.89.0

### Node.js Version

20.19.0

### Database

PostgreSQL

### Execution mode

queue

### PR DESCRIPTION
**Pull request by ivov**
## Summary

See story

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/CAT-770
Fix #14815

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Cadiac** [comment]
At this branch, locally with `N8N_RUNNERS_ENABLED=true` I'm seeing this only log `true` for simple primitive strings passed to console.log, did that break here?

image

File: packages/core/src/execution-engine/node-execution-context/execute-context.ts [hunk 1]
```diff
@@ -183,7 +184,10 @@ export class ExecuteContext extends BaseExecuteContext implements IExecuteFuncti
 
 	logNodeOutput(...args: unknown[]): void {
 		if (this.mode === 'manual') {
-			this.sendMessageToUI(...args);
+			const parsedLogArgs = args.map((arg) =>
+				typeof arg === 'string' ? jsonParse(arg, { fallbackValue: true }) : arg,
```
Comment (Cadiac) [inline packages/core/src/execution-engine/node-execution-context/execute-context.ts:188]: I think the fallback value "true" is coming from here when logging strings, see comment https://github.com/n8n-io/n8n/pull/15111#issuecomment-2851135734

Comment (ivov) [reply packages/core/src/execution-engine/node-execution-context/execute-context.ts]: Fat-fingered the arg :facepalm:

Added a test, thanks for catching this!

**Review by Cadiac — COMMENTED** [review]
Seems to now fix the original issue without breaking other stuff 👍 
While testing this I did notice that the following symbols fail logging with this logic:
- `undefined`
- `null`
- `NaN`
- `Infinity`

Especially the `null` and `undefined` are something that I think our users would like to see logged, any chance in supporting them here?

When these values are logged the following is seen on the console
```
There was a problem sending message to UI: Cannot read properties of null (reading 'isLuxonDateTime')
There was a problem sending message to UI: Cannot read properties of undefined (reading 'isLuxonDateTime')
```

and NaN and Infinity get logged as `null` 🤔

**Comment by ivov** [comment]
> Seems to now fix the original issue without breaking other stuff 👍 While testing this I did notice that the following symbols fail logging with this logic:
> 
>     * `undefined`
> 
>     * `null`
> 
>     * `NaN`
> 
>     * `Infinity`
> 
> 
> Especially the `null` and `undefined` are something that I think our users would like to see logged, any chance in supporting them here?
> 
> When these values are logged the following is seen on the console
> 
> ```
> There was a problem sending message to UI: Cannot read properties of null (reading 'isLuxonDateTime')
> There was a problem sending message to UI: Cannot read properties of undefined (reading 'isLuxonDateTime')
> ```
> 
> and NaN and Infinity get logged as `null` 🤔

Is that also supported in the legacy Code node? I'll take a look

**Comment by ivov** [comment]
These args are eventually passed to WS/SSE which [JSON stringify the args](https://github.com/n8n-io/n8n/blob/7d05cb2a37c0da3f42d859bd31d7c1f2dc6dcacd/packages/cli/src/push/abstract.push.ts#L77) that we push to the client, which is why `undefined` and `Infinity` and `NaN` all end up as `null`. 

This applies to both Code node and task runner. Since it has been like this for years in the legacy setup, I'd say let's keep unsupported symbols out of scope of this PR.

**Review by Cadiac — APPROVED** [review]
Fair enough, LGTM!

**Comment by janober** [comment]
Got released with [`n8n@1.93.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.93.0)
