### PR TITLE
fix(IMAP Node): Fix out-of-memory crash after ECONNRESET on reconnect

### LINKED ISSUE #26226: Out of Memory Crash after IMAP Trigger gets ECONNRESET
### Bug Description

The Imap Server we use occasionally breaks off the connection, probably because of a restart on their end, this causes a crash of the entire n8n instance.

The n8n instance crashes shortly after this log.

25.2.2026, 00:42:46.507
The trigger node "Email Trigger (IMAP)" of workflow "E-Mail Reader" failed with the error: "read ECONNRESET". Will try to reactivate.

25.2.2026, 00:43:18.347
<--- Last few GCs --->
[7:0x75dbf0dac000] 48652935 ms: Mark-Compact 1495.8 (1511.0) -> 1495.8 (1511.2) MB, pooled: 0 MB, 377.35 / 0.00 ms (average mu = 0.494, current mu = 0.019) allocation failure; scavenge might not succeed
[7:0x75dbf0dac000] 48653326 ms: Mark-Compact 1497.3 (1512.1) -> 1497.3 (1516.9) MB, pooled: 0 MB, 382.98 / 0.00 ms (average mu = 0.307, current mu = 0.020) allocation failure; scavenge might not succeed
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

### To Reproduce

1. Make a workflow with E-Mail Trigger node
2. Connect to an Imap Server that can send ECONNRESET
3. Activate Workflow

### Expected behavior

No crash, it should simply retry the connection. In a custom implementation outside of n8n using the idle on this imap server, this is a non issue.

### Debug Info

# Debug info

## core

- n8nVersion: 2.7.2
- platform: docker (self-hosted)
- nodeJsVersion: 22.22.0
- nodeEnv: production
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 9c80cd72-5050-4a10-847b-f6898c18fe9b

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 720 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64; rv:148.0) gecko/20100101 firefox/148.0
- isTouchDevice: false

Generated at: 2026-02-25T09:39:17.074Z

### Operating System

Ubuntu Linux

### n8n Version

2.7.2

### Node.js Version

22.22.0

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by BerniWittmann**
## Summary

Fixes an out-of-memory crash in the IMAP trigger node that occurred after an ECONNRESET. Three compounding issues caused the OOM:

1. **searchCriteria mutation leak** — The `searchCriteria` array was mutated on every `onMail` call, accumulating UID filter entries indefinitely. Fixed by creating a shallow copy per invocation.
2. **Event listener leak** — Listeners on the ImapSimple wrapper were never cleaned up on reconnect. Fixed by calling `removeAllListeners()` in `ImapSimple.end()` and in the connection close handler.
3. **Duplicate error reporting** — ECONNRESET fired both `error` and `close` events, causing duplicate `emitError` calls. Fixed with a per-connection `errorReported` flag.

## Testing

I used the following workflow for testing: [IMAP Test.json](https://github.com/user-attachments/files/26623768/IMAP.Test.json)
and used a local IMAP/SMTP Server using Greenmail via
`docker run -p 3143:3143 -p 3025:3025 -p 8080:8080 greenmail/standalone`

## Related Linear tickets, Github issues, and Community forum posts

- https://linear.app/n8n/issue/NODE-4710
- closes https://github.com/n8n-io/n8n/issues/26226

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
- [ ] PR Labeled with `Backport to Beta`, `Backport to Stable`, or `Backport to v1` (if the PR is an urgent fix that needs to be backported)
- [x] I have seen this code, I have run this code, and I take responsibility for this code.

### CODE REVIEW

File: packages/@n8n/imap/src/imap-simple.ts [hunk 1]
```diff
@@ -20,30 +17,24 @@ export class ImapSimple extends EventEmitter {
...
 		});
 	}
 
 	/** disconnect from the imap server */
 	end(): void {
-		// set state flag to suppress 'ECONNRESET' errors that are triggered when .end() is called.
-		// it is a known issue that has no known fix. This just temporarily ignores that error.
+		// Remove all forwarded event listeners to prevent memory leaks
+		// when connections are replaced (e.g. on reconnect)
+		this.imap.removeAllListeners();
```
Comment (yehorkardash) [inline packages/@n8n/imap/src/imap-simple.ts]: Removing all listeners on end(), introduces a regression in logging.
`Email Read Imap: Connected closed for forced reconnecting` and `Email Read Imap: Shutting down workflow - connected closed` can no longer be logged

File: packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts [hunk 2]
```diff
@@ -464,21 +467,25 @@ export class EmailReadImapV2 implements INodeType {
...
 						this.logger.debug('Email Read Imap: Shutting down workflow - connected closed');
-					} else {
+					} else if (!errorReported) {
 						this.logger.error('Email Read Imap: Connected closed unexpectedly');
 						this.emitError(new Error('Imap connection closed unexpectedly'));
 					}
+					conn.removeAllListeners();
 				});
 				conn.on('error', (error) => {
 					const errorCode = ((error as JsonObject).code as string).toUpperCase();
```
Comment (yehorkardash) [inline packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts]: could you add a validation here, to prevent potential error in case an error without 'code' is thrown?

**Review by yehorkardash — COMMENTED** [review]
Looks good, just two small notes

File: packages/@n8n/imap/src/imap-simple.ts (hunk 1 above)
Comment (BerniWittmann) [reply packages/@n8n/imap/src/imap-simple.ts]: Good catches, thank you 👍

File: packages/@n8n/imap/src/imap-simple.ts [hunk 3]
```diff
@@ -20,30 +17,23 @@ export class ImapSimple extends EventEmitter {
...
```
Comment (yehorkardash) [inline packages/@n8n/imap/src/imap-simple.ts]: I tried setting "force reconnection" to see if logs related to that are printed, but it seems they're still missing, because listener is still not firing

Comment (BerniWittmann) [reply packages/@n8n/imap/src/imap-simple.ts]: you're right, I was a bit to quick now. Adjusted it and also tested it myself, so the debug messages `Forcing reconnect to IMAP server` and `Email Read Imap: Connected closed for forced reconnecting` are both showing for me

File: packages/@n8n/imap/src/imap-simple.ts [hunk 4]
```diff
@@ -20,30 +17,19 @@ export class ImapSimple extends EventEmitter {
...
 		// https://github.com/mscdex/node-imap/issues/395
-		this.ending = true;
-
-		// using 'close' event to unbind ECONNRESET error handler, because the node-imap
-		// maintainer claims it is the more reliable event between 'end' and 'close'.
-		// https://github.com/mscdex/node-imap/issues/394
-		this.imap.once('close', () => {
-			this.ending = false;
-		});
+		this.imap.on('error', () => {});
```
Comment (yehorkardash) [inline packages/@n8n/imap/src/imap-simple.ts:35]: Hey, sorry for commenting once more, just want to make sure
Doesn't removal of removeListeners reintroduce the issue that was mentioned in fixes?

> Event listener leak — Listeners on the ImapSimple wrapper were never cleaned up on reconnect. Fixed by calling removeAllListeners() in ImapSimple.end() and in the connection close handler.

We do need to log, but we still need to remove listeners if that's the real issue

Comment (BerniWittmann) [reply packages/@n8n/imap/src/imap-simple.ts:35]: No you're completely right, I have to put a little more thought into that. Maybe my brain is also just fried today already and will take a look with fresh eyes again :)

**Review by yehorkardash — APPROVED** [review]
LGTM 🚀
