### PR TITLE
fix(core): Ensure tasks timeout even if they don't receive settings

### LINKED ISSUE #12354: Code Node Stopped Working
### Bug Description

Everything was working until a few hours ago and now none of the code nodes seem to be working.  Gets stuck on executing!

Code note in other Workflows have also stopped working

I did the following to try to fix the issue...

1) I duplicated the Code node

2) I copy/pasted the code into a new code node

3) I duplicated the entire workflow

4) I redid the code from scratch.

None of the above worked.

image

### To Reproduce

1) Add Code Node
2) Add some simple code
3) Test

My Code:
`
if (!items[0]?.json?.data) {
    throw new Error("Input data is missing or invalid.");
}

let jsonData;
try {
    jsonData = JSON.parse(items[0].json.data);
} catch (error) {
    throw new Error("Failed to parse JSON: " + error.message);
}

// Extract the link to the .vtt file or provide a fallback
const vttLink = jsonData.link || "Link not available";

// Return the link as output
return [
    {
        json: {
            vttLink: vttLink,
        }
    }
];

`

### Expected behavior

Code node should execute the code.

### Operating System

Online Version

### n8n Version

Running version n8n@1.72.1

### Node.js Version

Online Version

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by tomi**
## Summary

If the n8n instance happens to crash on a specific time, task runner task
might not receive a response to e.g. settings or data request. In cases like
this the task runner was left hanging forever. This PR makes sure the tasks
get aborted correctly.

Also refactors the task execution lifecycle to be explicit which states the task
might have and how different events are handled in different states.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/CAT-459/community-issue-code-node-stopped-working

https://community.n8n.io/t/code-nodes-stopped-working/67141

fixes #12354

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/@n8n/task-runner/src/task-state.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+	private timeoutTimer: NodeJS.Timeout;
+
+	constructor(opts: TaskStateOpts) {
+		this.taskId = opts.taskId;
+		this.timeoutTimer = setTimeout(opts.onTimeout, opts.timeoutInS * 1000);
+	}
+
+	/** Cleans up any resources before the task can be removed */
+	cleanup() {
+		clearTimeout(this.timeoutTimer);
```
Comment (ivov) [inline packages/@n8n/task-runner/src/task-state.ts:76]: Do we need to set `this.timeoutTimer` to `undefined` as well?

File: packages/@n8n/task-runner/src/task-runner.ts [hunk 2]
```diff
@@ -284,111 +286,116 @@ export abstract class TaskRunner extends EventEmitter {
...
-	taskErrored(taskId: string, error: unknown) {
-		this.send({
-			type: 'runner:taskerror',
-			taskId,
-			error,
-		});
-		this.runningTasks.delete(taskId);
-		this.sendOffers();
-	}
+			// This should never happen, the time out timer should only fire once
```
Comment (ivov) [inline packages/@n8n/task-runner/src/task-runner.ts:346]:
```suggestion
			// This should never happen, the timeout timer should only fire once
```

File: packages/@n8n/task-runner/src/task-runner.ts [hunk 3]
```diff
@@ -284,111 +286,116 @@ export abstract class TaskRunner extends EventEmitter {
...
+			waitingForSettings: async () => {
+				taskState.status = 'running';
+
+				await this.executeTask(
+					{
+						taskId,
+						settings,
+					},
+					taskState.abortController.signal,
+				)
```
Comment (ivov) [inline packages/@n8n/task-runner/src/task-runner.ts:385]: Transitions aren't atomic - what if a cancellation arrives at L378? Too unlikely?

File: packages/@n8n/task-runner/src/task-runner.ts [hunk 4]
```diff
@@ -284,111 +286,116 @@ export abstract class TaskRunner extends EventEmitter {
...
+				this.send({
+					type: 'runner:taskerror',
+					taskId,
+					error: new TimeoutError(this.taskTimeout),
+				});
 
-		this.sendOffers();
-	}
+				this.finishTask(taskState);
+			},
```
Comment (ivov) [inline packages/@n8n/task-runner/src/task-runner.ts:344]: If `this.send` throws because e.g. the websocket connection closed, we won't clean up in `finishTask`?

File: packages/@n8n/task-runner/src/task-state.ts [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+ * - waitingForSettings: The task is waiting for settings from the broker
+ * - running: The task is currently running
+ * - aborting:cancelled: The task was canceled by the broker and is being aborted
+ * - aborting:timeout: The task took too long to complete and is being aborted
+ *
+ * The task is discarded once it reaches an end state.
+ *
+ * The class only holds the state, and does not have any logic.
+ *
+ * The task has the following lifecycle:
```
Comment (ivov) [inline packages/@n8n/task-runner/src/task-state.ts:26]: Thanks for diagramming this!

**Review by ivov — COMMENTED** [review]
We were slowly moving to a state machine with so many booleans :)

File: packages/@n8n/task-runner/src/task-runner.ts [hunk 6]
```diff
@@ -284,111 +286,116 @@ export abstract class TaskRunner extends EventEmitter {
...
-		if (controller) {
-			controller.abort();
-			this.taskCancellations.delete(taskId);
+			running: () => {
+				taskState.status = 'aborting:cancelled';
+				taskState.abortController.abort('cancelled');
+				this.cancelTaskRequests(taskId, reason);
+			},
+		});
+	}
```
[the remark this answers is not in the document]
Comment (tomi) [reply packages/@n8n/task-runner/src/task-runner.ts:325]: That is because when the task is in:
- `waitingForSettings` state : it hasn't been executed yet, so it can't have any in-flight requests
- `running` : The task is currently executing, so we have to wait until the control comes back from the task (i.e. the task execution promise resolves/rejects). We don't want to release a new "slot" for next task until that. This happens concurrently (but in parallel!). Hopefully this image clarifies it:

image

File: packages/@n8n/task-runner/src/task-state.ts [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+
+	/** Signal for aborting the execution of the task */
+	readonly abortController = new AbortController();
+
+	/** Timeout timer for the task */
+	private timeoutTimer: NodeJS.Timeout;
+
+	constructor(opts: TaskStateOpts) {
+		this.taskId = opts.taskId;
+		this.timeoutTimer = setTimeout(opts.onTimeout, opts.timeoutInS * 1000);
```
[the remark this answers is not in the document]
Comment (tomi) [reply packages/@n8n/task-runner/src/task-state.ts:71]: That is correct. This was the bug here. If we never receive the task settings, it would never timeout and wait forever. The other option would be to add a separate timeout for this case, but that would add more complexity. It shouldn't take seconds to receive the settings from the main, so it should be fine to eat that from the timeout budget. You can always increase the timeout if that is a concern

File: packages/@n8n/task-runner/src/task-runner.ts (hunk 3 above)
Comment (tomi) [reply packages/@n8n/task-runner/src/task-runner.ts:385]: That is not possible, since Nodejs is single threaded

File: packages/@n8n/task-runner/src/task-runner.ts (hunk 4 above)
Comment (tomi) [reply packages/@n8n/task-runner/src/task-runner.ts:344]: Good catch! I'll wrap it in try..finally

**Comment by tomi** [comment]
Thank you for the comments  @ivov 🙇  Addressed them

File: packages/@n8n/task-runner/src/task-runner.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (ivov) [reply packages/@n8n/task-runner/src/task-runner.ts:325]: Thank you, I misremembered and thought we requested node types as preparation rather than as part of the task.

File: packages/@n8n/task-runner/src/task-state.ts [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+
+export type TaskStateOpts = {
+	taskId: string;
+	timeoutInS: number;
+	onTimeout: () => void;
+};
+
+/**
+ * The state of a task. The task can be in one of the following states:
+ * - waitingForSettings: The task is waiting for settings from the broker
```
[the remark this answers is not in the document]
Comment (ivov) [reply packages/@n8n/task-runner/src/task-state.ts:17]: Thank you, I misremembered about this: https://github.com/n8n-io/n8n/pull/12431#discussion_r1901557065

**Review by ivov — APPROVED** [review]
Tested manually and working well, thanks for the fix!

**Comment by tomi** [comment]
@ivov had to merge master to fix an e2e test, could you reapprove 🙏

**Review by ivov — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)
