### PR TITLE
fix(core): Fix supportedNodes for non-lazy loaded community packages (no-changelog)

### LINKED ISSUE #5501: Reinstall missing packages with N8N_REINSTALL_MISSING_PACKAGES is messing up the node type and causing workflows to stop
First, thank you for building this great tool, I'm having a lot of fun! 😇 

**Describe the bug**
Community nodes are not being reinstalled after a redeployment of a new docker instance.

My setup is using a modified version of this template: https://github.com/railwayapp-templates/n8n

**To Reproduce**

My `Dockerfile`:

```dockerfile
FROM n8nio/n8n:latest

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER

ARG USERNAME
ARG PASSWORD

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$USERNAME
ENV N8N_BASIC_AUTH_PASSWORD=$PASSWORD

# Reinstall missing packages: https://docs.n8n.io/integrations/community-nodes/troubleshooting/
ENV N8N_REINSTALL_MISSING_PACKAGES=true

CMD ["n8n", "start"]
```

1. Set up an instance of Railway using this template: https://github.com/railwayapp-templates/n8n
2. Install a community node. In my case: `n8n-nodes-discord` from here: https://www.npmjs.com/package/n8n-nodes-discord
3. Add node to a workflow
4. Redeploy
5. Reload the browser
6. Workflow is now deactivated, and old node is not found, but I can create new nodes.
    1. `Workflow could not be activated: Node not found: n8n-nodes-discord.discord` 
8. _Sometimes uninstalling and reinstalling works, but it might cause more problems_
    1. After a couple of times this stops working and the node is not found even after reinstalling.

The package shows up as installed, but the workflows can't find the nodes.

Screenshot 2023-02-17 at 10 52 57

**Expected behavior**
Missing packages should reinstall and workflows should be running and detecting the nodes after a docker instance redeploy. I expect the env variable `N8N_REINSTALL_MISSING_PACKAGES` would reinstall all packages. 

**Environment (please complete the following information):**

- OS: Docker using `n8nio/n8n:latest`
- n8n Version: Version 0.216.0
- Database system: Postgres
- Operation mode: `own`

**Additional context**
Railway deploys do not allow me to persist the nodes directory mentioned here: https://docs.n8n.io/integrations/community-nodes/troubleshooting/

I will add more of my findings in this issue. Thank you! 😄

### LINKED ISSUE #8188: No testing function found for this credential (non-versioned node)
**Describe the bug**

The problem is described here: https://community.n8n.io/t/couldn-t-connect-with-these-settings-no-testing-function-found-for-this-credential/33558/1

Code: https://github.com/NguyeNgocPhus/n8n-test-node

**Environment (please complete the following information):**

n8n version: 1.17.1
Database: Postgres
Running n8n via: desktop app
Operating system: Windows

**Additional context**

There are multiple reports of this problem, and no solution provided yet.

### PR DESCRIPTION
**Pull request by netroy**
## Summary
We had an inconsistency in how and when we prefixed `packageName` on nodes. This was causing `supportedNodes` referring to invalid node names.
This PR moves all `packageName` prefixing code to `LoadNodesAndCredentials`, which ensures that lazy-loading has no effect on node-names anywhere.

Extracted out of #9874.
[E2E Tests](https://github.com/n8n-io/n8n/actions/runs/12246693568)
[Workflow Tests](https://github.com/n8n-io/n8n/actions/runs/12246671270)

## Related Linear tickets, Github issues, and Community forum posts
* Fixes #8188
* Fixes #5501
* https://community.n8n.io/t/community-node-become-unrecognized-every-time-i-restart-n8n-container/52095
* https://community.n8n.io/t/community-node-is-no-longer-visible/46665

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/cli/src/load-nodes-and-credentials.ts [hunk 1]
```diff
@@ -307,22 +307,28 @@ export class LoadNodesAndCredentials {
 
 		for (const loader of Object.values(this.loaders)) {
 			// list of node & credential types that will be sent to the frontend
-			const { known, types, directory } = loader;
-			this.types.nodes = this.types.nodes.concat(types.nodes);
+			const { known, types, directory, packageName } = loader;
+			this.types.nodes = this.types.nodes.concat(
+				types.nodes.map(({ name, ...rest }) => ({
+					...rest,
+					// TODO: check if CUSTOM nodes should also be prefixed or not
```
Comment (netroy) [inline packages/cli/src/load-nodes-and-credentials.ts:314]: TODO

Comment (tomi) [reply packages/cli/src/load-nodes-and-credentials.ts]: Is this addressed in a follow-up or?

File: packages/cli/src/load-nodes-and-credentials.ts [hunk 2]
```diff
@@ -307,22 +307,28 @@ export class LoadNodesAndCredentials {
...
+					name: `${packageName}.${name}`,
+				})),
+			);
 			this.types.credentials = this.types.credentials.concat(types.credentials);
 
 			// Nodes and credentials that have been loaded immediately
-			for (const nodeTypeName in loader.nodeTypes) {
-				this.loaded.nodes[nodeTypeName] = loader.nodeTypes[nodeTypeName];
+			for (const type in loader.nodeTypes) {
```
Comment (tomi) [inline packages/cli/src/load-nodes-and-credentials.ts:320]: nit: IMHO this was more readable before. Type is very ambiguous name (is it an object or string or what?), where as nodeTypeName was explicit. Or could also be `typeName` if you want to make it shorter

File: packages/cli/src/load-nodes-and-credentials.ts [hunk 3]
```diff
@@ -307,22 +307,28 @@ export class LoadNodesAndCredentials {
...
+				this.loaded.nodes[`${packageName}.${type}`] = loader.nodeTypes[type];
 			}
 
-			for (const credentialTypeName in loader.credentialTypes) {
-				this.loaded.credentials[credentialTypeName] = loader.credentialTypes[credentialTypeName];
+			for (const type in loader.credentialTypes) {
+				this.loaded.credentials[type] = loader.credentialTypes[type];
```
Comment (tomi) [inline packages/cli/src/load-nodes-and-credentials.ts:325]: Credentials don't need to be prefixed with the `packageName`?

File: packages/core/src/DirectoryLoader.ts [hunk 4]
```diff
@@ -34,6 +30,16 @@ function toJSON(this: ICredentialType) {
 	};
 }
 
+type Codex = {
```
Comment (tomi) [inline packages/core/src/DirectoryLoader.ts:33]: What's a `Codex`? Could we add some description for it

File: packages/core/src/DirectoryLoader.ts [hunk 5]
```diff
@@ -139,121 +149,124 @@ export abstract class DirectoryLoader {
...
+					(version) => version.description.credentials ?? [],
+				),
+				'name',
+			);
+		}
+
+		return object.description.credentials ?? [];
+	}
+
+	getVersionedNodeTypeAll(object: IVersionedNodeType | INodeType): INodeType[] {
```
Comment (tomi) [inline packages/core/src/DirectoryLoader.ts:220]: This is not very clear what this does. Could we add documentation?

**Review by tomi — DISMISSED** [review]
Can't say that I 100% understood everything that changed here. The code and tests look solid and if you tested that it works I'm happy. Couple questions / comments but no blockers 🚀

File: packages/cli/src/load-nodes-and-credentials.ts (hunk 3 above)
Comment (netroy) [reply packages/cli/src/load-nodes-and-credentials.ts:325]: unfortunately not. I've wanted to prefix credentials since 2022, but doing so will be a breaking change.

File: packages/core/src/DirectoryLoader.ts (hunk 4 above)
Comment (netroy) [reply packages/core/src/DirectoryLoader.ts:33]: TBH, I still don't know for sure. These lines were moved from [here](https://github.com/n8n-io/n8n/blob/master/packages/core/src/DirectoryLoader.ts#L212-L220).

File: packages/core/src/DirectoryLoader.ts (hunk 5 above)
Comment (netroy) [reply packages/core/src/DirectoryLoader.ts:220]: I also don't know. These were moved from [here](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/NodeHelpers.ts#L1969-L1986).
This code (and this PR in general) could definitely benefit from better docs, and more tests.

**Review by tomi — DISMISSED** [review]
🚀

**Review by elsmr — DISMISSED** [review]
LGTM

I only found this change in the output of `known/credentials.json`. AFAIK this will not have any effect because these credentials are never used directly, only extended. But maybe you know a case where this could break things.

image

**Review by elsmr — APPROVED** [review]
Nice! so many added tests and simpler code + 1 less script 😄

**Comment by janober** [comment]
Got released with [`n8n@1.72.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.72.0)
