### PR TITLE
fix(core): Fix waiting webhooks validation when n8n is behind proxy

### LINKED ISSUE #18610: sendAndWait Broken with missing/invalid token
### Bug Description

I think this broke sendAndWait webhooks (at least for Telegram and Slack)

https://github.com/n8n-io/n8n/pull/17566

After upgrading my sendAndWait actions all return {“error”:“Invalid token”}

I tried in a clean setup and still got the same error, but when trying it in 1.103.2 it works

### To Reproduce

Install 1.107.4
Add a Telegram bot credentials
Add a Send message and wait for a response, and set the From id
Set the response type to Approval
Add an approve button
Then trigger the node, and you should get an approval request in telegram
When you click on the button yo should get `{"error":"Invalid token"}`

### Expected behavior

When the above buttn is cliked the node should be triggerd

### Debug Info

# Debug info

## core

- n8nVersion: 1.107.4
- platform: npm
- nodeJsVersion: 22.18.0
- database: postgres
- executionMode: regular
- concurrency: 1
- license: enterprise (production)
- consumerId: c365a869-660e-48e1-837e-6e4f6a4ea111

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 900 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/139.0.0.0 safari/537.36
- isTouchDevice: false

## security

- secureCookie: false

Generated at: 2025-08-20T17:13:11.994Z

### Operating System

Debian

### n8n Version

1.107.4

### Node.js Version

22.18.0

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by tomi**
## Summary

We were using the host incorrectly from the `host` header, which might be the reverse proxy's hostname when n8n is behind a reverse proxy. Using `req.hostname` works correctly as long as `N8N_PROXY_HOPS` is set correctly and the reverse proxy sends the correct headers.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/CAT-1252/community-issue-sendandwait-broken-with-missinginvalid-token

Resolves #18610

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/cli/src/webhooks/waiting-webhooks.ts [hunk 1]
```diff
@@ -89,22 +90,23 @@ export class WaitingWebhooks implements IWebhookManager {
...
+	validateSignatureInRequest(req: express.Request) {
 		try {
 			const actualToken = req.query[WAITING_TOKEN_QUERY_PARAM];
 
 			if (typeof actualToken !== 'string') return false;
 
-			const parsedUrl = new URL(req.url, `http://${req.headers.host}`);
+			// req.hostname is set correctly even when n8n is behind a reverse proxy
+			// as long as N8N_PROXY_HOPS is set correctly
+			const parsedUrl = new URL(req.url, `http://${req.hostname}`);
```
Comment (Joffcom) [inline packages/cli/src/webhooks/waiting-webhooks.ts]: Why was/is this `http`?

Comment (tomi) [reply packages/cli/src/webhooks/waiting-webhooks.ts]: it's what `URL` expects but it doesn't matter in practice as we are not using the protocol for the signature

Comment (Joffcom) [reply packages/cli/src/webhooks/waiting-webhooks.ts]: Ah perfect.

**Review by michael-radency — APPROVED** [review]
LGTM

**Comment by janober** [comment]
Got released with [`n8n@1.108.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.108.2)
