### PR TITLE
fix(n8n Form Node): Redirection update (no-changelog)

### LINKED ISSUE #12632: Race condition in next form page?
### Bug Description

I want to load a 2nd form, but get this error when I try to upload multiple (heavier - 1MB in total) files. 

This is the error I get:

Image

The image is uploaded however. So I would expect the flow to continue. 

Image

In the logs, I have this:
```
n8n-1       | 2025-01-16T10:48:39.091Z | debug | Executing hook (hookFunctionsSave) {"executionId":"144315","workflowId":"mZ8SjEZ4v4dZTxBT","file":"workflow-execute-additional-data.js","function":"workflowExecuteAfter"}
n8n-1       | 2025-01-16T10:48:39.092Z | debug | Save execution data to database for execution ID 144315 {"executionId":"144315","workflowId":"mZ8SjEZ4v4dZTxBT","finished":false,"stoppedAt":"2025-01-16T10:48:39.090Z","file":"shared-hook-functions.js","function":"updateExistingExecution"}
n8n-1       | 2025-01-16T10:48:39.095Z | debug | Received waiting-form "GET" for execution "144315" {"file":"waiting-forms.js","function":"logReceivedWebhook"}
n8n-1       | 2025-01-16T10:48:39.133Z | debug | Error in handling webhook request GET /form-waiting/144315: Cannot read properties of undefined (reading 'pop') {"stacktrace":"TypeError: Cannot read properties of undefined (reading 'pop')\n    at WaitingForms.getWebhookExecutionData (/usr/local/lib/node_modules/n8n/dist/webhooks/waiting-webhooks.js:132:61)\n    at WaitingForms.executeWebhook (/usr/local/lib/node_modules/n8n/dist/webhooks/waiting-forms.js:118:27)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at WebhookRequestHandler.handleRequest (/usr/local/lib/node_modules/n8n/dist/webhooks/webhook-request-handler.js:61:30)\n    at /usr/local/lib/node_modules/n8n/dist/webhooks/webhook-request-handler.js:120:9","file":"webhook-request-handler.js","function":"handleRequest"}
n8n-1       | 2025-01-16T10:48:39.183Z | debug | Executing hook (hookFunctionsPush) {"executionId":"144315","pushRef":"o60zpg3xib","workflowId":"mZ8SjEZ4v4dZTxBT","file":"workflow-execute-additional-data.js","function":"workflowExecuteAfter"}
```

### To Reproduce

1. The flow:

```{
  "nodes": [
    {
      "parameters": {
        "formTitle": "Test form",
        "formFields": {
          "values": [
            {
              "fieldLabel": "Upload some files",
              "fieldType": "file",
              "requiredField": true
            }
          ]
        },
        "options": {
          "respondWithOptions": {
            "values": {
              "formSubmittedText": "Received"
            }
          }
        }
      },
      "type": "n8n-nodes-base.formTrigger",
      "typeVersion": 2.2,
      "position": [
        -400,
        160
      ],
      "id": "f5487102-ec25-4a0f-a492-d1dc3885e4cc",
      "name": "On form submission",
      "webhookId": "0c961fbc-a4a3-44d7-a926-fef2257ace89"
    },
    {
      "parameters": {
        "conditions": {
          "options": {
            "caseSensitive": true,
            "leftValue": "",
            "typeValidation": "strict",
            "version": 2
          },
          "conditions": [
            {
              "id": "39e9dc4f-d7a8-4059-9dd5-4c2d69fade55",
              "leftValue": "={{ Object.keys($input.item.binary).length }}",
              "rightValue": 1,
              "operator": {
                "type": "number",
                "operation": "equals"
              }
            },
            {
              "id": "cac4f1fc-fafb-4d5e-9fe2-58720a1af416",
              "leftValue": "={{$input.item.binary[Object.keys($input.item.binary)[0]].fileExtension}}",
              "rightValue": "json",
              "operator": {
                "type": "string",
                "operation": "equals",
                "name": "filter.operator.equals"
              }
            }
          ],
          "combinator": "and"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.if",
      "typeVersion": 2.2,
      "position": [
        -200,
        160
      ],
      "id": "2b4212f3-1486-4849-8b69-f4f54615e8b2",
      "name": "Some test"
    },
    {
      "parameters": {
        "formFields": {
          "values": [
            {
              "fieldLabel": "Extra info",
              "fieldType": "textarea"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.form",
      "typeVersion": 1,
      "position": [
        20,
        180
      ],
      "id": "ff00320e-f372-4395-aefe-7e819461d8ee",
      "name": "Extra form",
      "webhookId": "88644b89-0a75-478a-abad-c10d67becaff"
    }
  ],
  "connections": {
    "On form submission": {
      "main": [
        [
          {
            "node": "Some test",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Some test": {
      "main": [
        [],
        [
          {
            "node": "Extra form",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

2. The image I'm trying to upload, for which for sure it doesn't work: https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg

### Expected behavior

The 2nd form should be shown instead of an error. 

### Operating System

Linux: Ubuntu 24.04 LTS

### n8n Version

1.75.0

### Node.js Version

official n8n Docker image

### Database

PostgreSQL

### Execution mode

main (default)

### LINKED ISSUE #12668: n8n Form Ending node execution continues forever when using "Redirect to URL" as form submission type
## Describe the problem/error/question

n8n Form Ending node execution continues to run in the background indefinitely when using "Redirect to URL" as form submission type even when the user has finished redirecting into the specified URL.

## What is the error message (if any)?

None, just the node continuing to execute without end.

## Please share your workflow/screenshots/recording

Image

Image

```
{
  "nodes": [
    {
      "parameters": {
        "formTitle": "Test",
        "formDescription": "Test Form",
        "formFields": {
          "values": [
            {
              "fieldLabel": "Name"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.formTrigger",
      "typeVersion": 2.2,
      "position": [
        -300,
        -120
      ],
      "id": "b83ba96b-f5aa-4295-8bf0-bacf500b5282",
      "name": "On form submission",
      "webhookId": "a3fe0923-4b77-401c-b9d8-bae9b0a7e8b4"
    },
    {
      "parameters": {
        "operation": "completion",
        "respondWith": "redirect",
        "redirectUrl": "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.form/"
      },
      "type": "n8n-nodes-base.form",
      "typeVersion": 1,
      "position": [
        -60,
        -120
      ],
      "id": "1e9eb7a8-cc35-47c1-a913-570e7ae8160b",
      "name": "Form1",
      "webhookId": "1d5dfae7-9700-4629-a3b4-b794bd33ded4"
    }
  ],
  "connections": {
    "On form submission": {
      "main": [
        [
          {
            "node": "Form1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "231f378c4c7b1146da93039922ac754a09136b02f6c77143d6f57f43c55f66e4"
  }
}
```

## Share the output returned by the last node

Image

### core

- n8nVersion: 1.74.2
- platform: npm
- nodeJsVersion: 20.18.1
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-01-17T11:03:58.734Z}

### LINKED ISSUE #12925: Next Form Page loading issue
## Describe the problem/error/question
I am uploading  .csv file via n8n form and extracting its data with extract from file node. Once extraction gets completed i am checking if .csv file  rows should not exceed 10 rows. I am using IF command to check if {{ $("Extract from File").all().length }} Greater than 10 then navigate to n8n form to ask for resubmission of file again. if I try to upload .csv file continuously for  2 -3 times , n8n form gets stuck.

## What is the error message (if any)?
No message. Stead of n8n form displaying normal fields that asks user to upload .csv file it says form submitted successfully.

## Please share your workflow/screenshots/recording

Image

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
```{
  "nodes": [
    {
      "parameters": {
        "binaryPropertyName": "Import_File____csv___xlsx_",
        "options": {
          "headerRow": true,
          "includeEmptyCells": true
        }
      },
      "type": "n8n-nodes-base.extractFromFile",
      "typeVersion": 1,
      "position": [
        -20,
        440
      ],
      "id": "2dcacb42-6c46-498e-bbfd-ef93a5cdf8fd",
      "name": "Extract from File",
      "executeOnce": false
    },
    {
      "parameters": {
        "conditions": {
          "options": {
            "caseSensitive": true,
            "leftValue": "",
            "typeValidation": "strict",
            "version": 2
          },
          "conditions": [
            {
              "id": "dccd3f29-74df-48e0-a5e1-5c7dc2be9d1f",
              "leftValue": "={{ $(\"Extract from File\").all().length }}",
              "rightValue": 10,
              "operator": {
                "type": "number",
                "operation": "gt"
              }
            }
          ],
          "combinator": "and"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.if",
      "typeVersion": 2.2,
      "position": [
        160,
        440
      ],
      "id": "9449aed0-9257-4416-bd33-db3cb84d80f2",
      "name": "If",
      "executeOnce": false
    },
    {
      "parameters": {
        "formFields": {
          "values": [
            {
              "fieldLabel": "Import File  (.csv, .xlsx)",
              "fieldType": "file",
              "multipleFiles": false,
              "acceptFileTypes": ".csv, .xlsx",
              "requiredField": true
            }
          ]
        },
        "options": {
          "formTitle": "Import Your Questions (Max 10 Questions)",
          "buttonLabel": "Import"
        }
      },
      "type": "n8n-nodes-base.form",
      "typeVersion": 1,
      "position": [
        -300,
        440
      ],
      "id": "125e88b0-a7d0-4df8-8c02-ac1e608b8e22",
      "name": "ImportFile1",
      "webhookId": "6473ce4d-a0a8-4926-8ad7-c697b886e4d9"
    },
    {
      "parameters": {
        "formFields": {
          "values": [
            {
              "fieldLabel": "Import File  (.csv, .xlsx)",
              "fieldType": "file",
              "multipleFiles": false,
              "acceptFileTypes": ".csv, .xlsx",
              "requiredField": true
            }
          ]
        },
        "options": {
          "formTitle": "Please Import Your Questions Again (Max 10 Questions)",
          "buttonLabel": "Import"
        }
      },
      "type": "n8n-nodes-base.form",
      "typeVersion": 1,
      "position": [
        140,
        700
      ],
      "id": "d1af959f-f2a1-457b-93a7-1035f6e36f58",
      "name": "ImportFile",
      "webhookId": "6473ce4d-a0a8-4926-8ad7-c697b886e4d9",
      "executeOnce": false
    }
  ],
  "connections": {
    "Extract from File": {
      "main": [
        [
          {
            "node": "If",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "If": {
      "main": [
        [
          {
            "node": "ImportFile",
            "type": "main",
            "index": 0
          }
        ],
        []
      ]
    },
    "ImportFile1": {
      "main": [
        [
          {
            "node": "Extract from File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ImportFile": {
      "main": [
        [
          {
            "node": "Extract from File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "fb0330c12168d8986a25e32969e039658f672faf5d3467655ca2db5a9ecea7e5"
  }
}


## Share the output returned by the last node
<!-- If you need help with data transformations, please also share your expected output. -->


## Debug info

### core

- n8nVersion: 1.75.2
- platform: npm
- nodeJsVersion: 20.18.1
- database: sqlite
- executionMode: regular
- concurrency: 20
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 720 hours
- maxCount: 25000 executions

### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/132.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-01-29T15:10:03.772Z}

### PR DESCRIPTION
**Pull request by michael-radency**
## Summary

update redirection mechanism to use `responseNode` mode
should fix issue with duplicate form pages and completion page

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-2352/form-completion-stuck-in-waiting
fixes https://github.com/n8n-io/n8n/issues/12668
fixes https://github.com/n8n-io/n8n/issues/12632
fixes https://github.com/n8n-io/n8n/issues/12925

### CODE REVIEW

**Review by dana-gill — CHANGES_REQUESTED** [review]
Just some cleanup suggestions :)

File: packages/cli/src/webhooks/webhook-helpers.ts [hunk 1]
```diff
@@ -101,6 +103,73 @@ export function getWorkflowWebhooks(
...
+	if (
+		[FORM_NODE_TYPE, FORM_TRIGGER_NODE_TYPE, WAIT_NODE_TYPE].includes(workflowStartNode.type) &&
+		(data?.headers as IDataObject)?.location &&
+		String(data?.responseCode).startsWith('3')
+	) {
+		data.responseCode = 200;
+		data.data = {
+			redirectURL: (data?.headers as IDataObject)?.location,
+		};
+		(data.headers as IDataObject).location = undefined;
```
[the remark this answers is not in the document]
Comment (michael-radency) [reply packages/cli/src/webhooks/webhook-helpers.ts:160]: I'm not sure, but this is form specific setup of dealing with redirection from` Respon to Webhook` node, it will reload window based on `redirectURL` in `json`, location not needed in this case
```
							if (json?.redirectURL) {
									const url = json.redirectURL.includes("://") ? json.redirectURL : "https://" + json.redirectURL;
									window.location.replace(url);
```

File: packages/cli/src/active-executions.ts [hunk 2]
```diff
@@ -170,6 +170,7 @@ export class ActiveExecutions {
 	finalizeExecution(executionId: string, fullRunData?: IRun) {
 		if (!this.has(executionId)) return;
 		const execution = this.getExecutionOrFail(executionId);
+		execution?.responsePromise?.resolve({});
```
Comment (netroy) [inline packages/cli/src/active-executions.ts:173]: This should be removed, and we should call `resolveResponsePromise` from a relevant place in `webhook-helpers.ts` instead.

File: packages/cli/src/webhooks/waiting-forms.ts [hunk 3]
```diff
@@ -39,25 +38,6 @@ export class WaitingForms extends WaitingWebhooks {
 		});
 	}
 
-	private async reloadForm(req: WaitingWebhookRequest, res: express.Response) {
-		try {
-			await sleep(1000);
-
-			const url = `${req.protocol}://${req.get('host')}${req.originalUrl}`;
-			const page = await axios({ url });
```
Comment (netroy) [inline packages/cli/src/webhooks/waiting-forms.ts:47]: Thanks for removing this. Code scanners have been complaining about this.

File: packages/cli/src/webhooks/webhook-helpers.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (netroy) [reply packages/cli/src/webhooks/webhook-helpers.ts:160]: why can we not use a 3xx redirect instead of redirecting this in html/js ?

File: packages/cli/templates/form-trigger-completion.handlebars [hunk 4]
```diff
@@ -73,9 +75,40 @@
...
 			</div>
 		{{/if}}
-		<script>
-			fetch('', { method: 'POST', body: {}, }).catch(() => {});
-		</script>
+		{{#if redirectUrl}}
+			<a id='redirectUrl' href='{{redirectUrl}}' style='display: none;'></a>
+		{{/if}}
+	<script>
+			fetch('', {
```
Comment (netroy) [inline packages/cli/templates/form-trigger-completion.handlebars:82]: could we not submit a html form, and let the http headers take care of the redirect here?

File: packages/workflow/src/Interfaces.ts [hunk 5]
```diff
@@ -2031,7 +2031,7 @@ export interface IWebhookResponseData {
 }
 
 export type WebhookResponseData = 'allEntries' | 'firstEntryJson' | 'firstEntryBinary' | 'noData';
-export type WebhookResponseMode = 'onReceived' | 'lastNode' | 'responseNode' | 'formPage';
```
Comment (netroy) [inline packages/workflow/src/Interfaces.ts:2034]: Could this break any existing workflows out there that still have the response mode set to `formPage` ?

File: packages/cli/src/active-executions.ts (hunk 2 above)
Comment (michael-radency) [reply packages/cli/src/active-executions.ts:173]: @netroy 
yes, after more testing this is not fixes all issues, but I don't think we could do this from `webhook-helpers.ts`

we need to resolve `responsePromise`, if there is any, once, after workflow finishes, as a clean up, if some page waits for response

do you have some ideas how it could be done?

this [workflow](https://test-fru.stage-app.n8n.cloud/workflow/0J7HbnPWmvfCSBFM) demonstrate issue

File: packages/workflow/src/Interfaces.ts (hunk 5 above)
Comment (michael-radency) [reply packages/workflow/src/Interfaces.ts:2034]: it should not, this was assigned dynamically in form trigger if form node in connected nodes
```
	if (hasNextPage) {
			responseMode = 'formPage';
		}
```

File: packages/cli/templates/form-trigger-completion.handlebars (hunk 4 above)
Comment (michael-radency) [reply packages/cli/templates/form-trigger-completion.handlebars:82]: this for consistency with form-trigger.handlebars

File: packages/cli/src/webhooks/webhook-helpers.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (michael-radency) [reply packages/cli/src/webhooks/webhook-helpers.ts:160]: we could not this would break old form triggers that are using `respondeNode` mode

File: packages/cli/src/active-executions.ts (hunk 2 above)
Comment (netroy) [reply packages/cli/src/active-executions.ts:173]: We don't need to block this change. 
I unfortunately don't have enough time or context to provide a solution here. I can try to fix this in another PR.

Comment (netroy) [reply packages/cli/src/active-executions.ts:173]: just FYI: this change might end up calling the `responsePromise.resolve` multiple times. once from this line, and another from any code calling `resolveResponsePromise`

**Review by dana-gill — APPROVED** [review]

File: packages/cli/src/active-executions.ts [hunk 6]
```diff
@@ -174,6 +174,22 @@ export class ActiveExecutions {
 		this.logger.debug('Execution finalized', { executionId });
 	}
 
+	/** Resolve the response promise in an execution. */
+	resolveExecutionResponsePromise(executionId: string) {
```
Comment (netroy) [inline packages/cli/src/active-executions.ts:178]: could we use the existing `resolveResponsePromise` method? I'm just wondering if we can avoid the duplication here.

**Comment by janober** [comment]
Got released with [`n8n@1.81.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.81.0)
