### PR TITLE
fix(editor): Correctly display trigger nodes without actions and with related regular node in the "On App Events" category

### LINKED ISSUE #4952: RabbitMQ Trigger does not appear in On App Events listing
**Describe the bug**

RabbitMQ Trigger does not appear in On App Events listing

**To Reproduce**

a2056cce-26b5-475f-a3be-0dee25af3303

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version 0.208.0
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

### PR DESCRIPTION
**Pull request by OlegIvaniv**
For the "On App Events" category we merge trigger and regular nodes. We then filter-out regular nodes without actions. But if in the merging function, the regular node would appear first we'd use it as the merge baseline. So if it has a trigger counterpart without actions, it would get filtered out. To solve this, we simply sort the nodes before merging, to make sure trigger nodes are always on top.

The affected nodes were:
1. AMQP Trigger
2. Kafka Trigger
3. RabbitMQ Trigger
4. MQTT Trigger

Closes #4952

### CODE REVIEW

File: packages/editor-ui/src/stores/nodeCreator.ts [hunk 1]
```diff
@@ -305,31 +305,40 @@ export const useNodeCreatorStore = defineStore(STORES.NODE_CREATOR, {
...
-						acc[normalizedName].actions || [],
-					);
-					return acc;
-				},
-				{},
-			);
+			const mergedNodes = [...this.visibleNodesWithActions]
+				// Sort triggers so they are always on top and when later get merged
+				// they won't be disacrded if they have the same name as a core node which doesn't contain actions
+				.sort((a, b) => {
```
Comment (netroy) [inline packages/editor-ui/src/stores/nodeCreator.ts:311]: should we move this sort to `filteredMergedAppNodes` in `TriggerHelperPanel.vue` instead? that way the sort happens only before the actual rendering.

Comment (OlegIvaniv) [reply packages/editor-ui/src/stores/nodeCreator.ts:311]: The sort needs to happen before the nodes are merged. But in `filteredMergedAppNodes` we're already using merged nodes to do the filtering.

**Review by mutdmour — APPROVED** [review]

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.209.0`
