### PR TITLE
fix(editor): Ignore required module type declaration error in code node

### LINKED ISSUE #13094: n8n Linter highlight error
## Describe the problem/error/question

The n8n linter shows via require that the package can not found ("Cannot find module 'jsdom' or its corresponding type declarations.")
- n8n built in package "jsdom" is activated via follwing environment variable: NODE_FUNCTION_ALLOW_BUILTIN=*
- jsdom works without issues but the linter says "Cannot find module 'jsdom' or its corresponding type declarations."
- the same issue for NODE_FUNCTION_ALLOW_EXTERNAL=*

expected behavior: 
- npm package are activated via environment variables: NODE_FUNCTION_ALLOW_BUILTIN / NODE_FUNCTION_ALLOW_EXTERNAL
- the n8n linter works without issues

## What is the error message (if any)?
"Cannot find module 'jsdom' or its corresponding type declarations."

## Please share your workflow/screenshots/recording

Image

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
⚠️ WARNING ⚠️ If you have sensitive data in your workflow (like API keys), please remove it before sharing.
```

### core

- n8nVersion: 1.76.2
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.2
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

### pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

### client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-02-05T08:26:07.500Z}

### PR DESCRIPTION
**Pull request by elsmr**
## Summary

**Before**
image

**After**
image

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-2369/community-issue-n8n-linter-highlight-error
fixes #13094

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/linter.ts [hunk 1]
```diff
@@ -49,8 +49,15 @@ function isDiagnosticWithLocation(
 }
 
 function isIgnoredDiagnostic(diagnostic: ts.Diagnostic) {
-	// No implicit any
-	return diagnostic.code === 7006;
+	switch (diagnostic.code) {
```
Comment (dana-gill) [inline packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/linter.ts:52]: Is there any possibility that we can test this? :D

Comment (elsmr) [reply packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/linter.ts:52]: Sure do you mind if it's in my next PR? I'm adding tests to related code there

**Review by dana-gill — APPROVED** [review]

**Review by dana-gill — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.83.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.83.0)
