### PR TITLE
fix: Form trigger and Wait Form mode basic authentication fix for form POST request

### LINKED ISSUE #23262: Form trigger always looping
### Bug Description

When I click on the next form, an infinite loop appears, and it does not proceed to the next form.

before n8n version 2.0, it can load properly.

### To Reproduce

Just make node "On form submission" and make switch node and node "next from page"

Image

Image

### Expected behavior

Can load to the next form like before version 2.0

### Debug Info

# Debug info

## core

- n8nVersion: 2.1.0
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: b40e5767-9497-41ce-b2ba-9283c4a530c1

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-12-16T07:08:23.471Z

### Operating System

Windows 11

### n8n Version

2.1.0

### Node.js Version

22.21.1

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### LINKED ISSUE #23602: basic auth, n8n form. Problem submitting response
### Bug Description

N8n Form has basic auth enabled and a Next Form Page. When I go to it, I get "Problem submitting response. Please try again or contact support if the problem persists."

### To Reproduce

basic auth enabled
1)Trigger n8n form
2)Next Form Page
Error Problem submitting response Please try again or contact support if the problem persists"
 

### Expected behavior

Go to Next Form Page after Trigger n8n form

### Debug Info

# Debug info

## core

- n8nVersion: 2.1.4
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 8d8a6ebe-5108-4de5-9092-7812ec4b393a

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-12-24T05:49:57.291Z

### Operating System

Ubuntu 22.04

### n8n Version

2.1.4

### Node.js Version

22.21.1

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

### LINKED ISSUE #24198: Form submissions fail when Basic Authentication is enabled with no error logs
### Bug Description

When using n8n Forms with Basic Authentication enabled, form submissions consistently fail with the generic UI error:

> Problem submitting response
> Please try again or contact support if the problem persists.

Image

However, no error is logged or displayed in the n8n execution logs, making it impossible to diagnose the issue.

If Basic Authentication is disabled, the same form works correctly and submissions are processed as expected.

This suggests a problem specifically related to form handling when Basic Authentication is enabled.

### To Reproduce

1. Create a new workflow in n8n.
2. Add a Form Trigger node.
3. Configure the form normally (any simple field is enough).
4. Enable Basic Authentication on the form.
5. Set a username and password.
6. Activate the workflow.
7. Open the form URL.
8. Authenticate using the configured Basic Auth credentials.
9. Fill out the form and submit it

### Expected behavior

The form submission fails

The UI shows the message:

> “Problem submitting response. Please try again or contact support if the problem persists.”

No error appears in:

- Workflow execution history
- Server logs
- Browser console (no meaningful error)

---

Expected behavior

The form submission should succeed when valid Basic Auth credentials are provided
If authentication or processing fails, a clear and actionable error should be logged, either:
- In the workflow execution
- Or in the n8n server logs
- At minimum, the UI error should provide more context (e.g. authentication failure, permission issue, internal error)

### Debug Info

# Debug info

## core

- n8nVersion: 2.2.6
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: postgres
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (x11; linux x86_64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

## security

- secureCookie: false

Generated at: 2026-01-12T18:57:50.588Z

### Operating System

Debian 13

### n8n Version

2.2.6

### Node.js Version

22.21.1

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by michael-radency**
## Summary

Basic authentication was broken due to the CSP sandbox. To fix this, we now validate it only on GET requests. If the authentication type is Basic Auth, we generate a token and embed it in the form. This token is then used for form's POST requests and is validated within the node's webhook method.

Affected nodes are Form Trigger node and Wain node (in form mode)

## Related Linear tickets, Github issues, and Community forum posts

- https://linear.app/n8n/issue/NODE-4155/form-trigger-stopped-working-correctly-on-the-internal-instance-since
- https://linear.app/n8n/issue/NODE-4140/community-issue-basic-auth-n8n-form-problem-submitting-response
- fixes #23262, fixes #24198, fixes #23602

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by michael-radency** [comment]
closed in favor of https://github.com/n8n-io/n8n/pull/23910

File: packages/cli/src/webhooks/waiting-webhooks.ts [hunk 1]
```diff
@@ -54,6 +54,14 @@ export class WaitingWebhooks implements IWebhookManager {
 
 	// TODO: implement `getWebhookMethods` for CORS support
 
+	async findAccessControlOptions() {
```
Comment (dlavrenuek) [inline packages/cli/src/webhooks/waiting-webhooks.ts:57]: The webhook request handler uses this method to enable CORS in https://github.com/n8n-io/n8n/blob/master/packages/cli/src/webhooks/webhook-request-handler.ts#L211, when it's missing the OPTIONS request fails due to missing cors headers. The preflight (OPTIONS) request is only called when the request contains any extra headers, see [spec](https://fetch.spec.whatwg.org/#cors-safelisted-request-header), since we now pass the auth token via headers real cors is required

File: packages/cli/src/webhooks/webhook.types.ts [hunk 2]
```diff
@@ -21,7 +21,7 @@ export interface IWebhookManager {
 	getWebhookMethods?: (path: string) => Promise<IHttpRequestMethods[]>;
 
 	/** Find the CORS options matching a path and method */
-	findAccessControlOptions?: (
+	findAccessControlOptions: (
```
Comment (dlavrenuek) [inline packages/cli/src/webhooks/webhook.types.ts:24]: Made the type non-optional so all classes implementing this interface must implement this method.

**Comment by dlavrenuek** [comment]
I've changed the implementation to use `x-auth-token` header rather than passing the token via query param.

**Review by yehorkardash — APPROVED** [review]
Tested, works as expected ✅
Thanks for providing e2e tests!
