### PR TITLE
fix(core): Refresh OAuth2 tokens on 401 during MCP tool calls

### LINKED ISSUE #22893: N8n not refreshing oauth tokens!
### Bug Description

Having a big issue with an MCP server that uses custom OAuth2 tokens for halo PSA.
The tokens keep breaking. I am guessing N8N is not refreshing them when they expire or something?

It just starts breaking.
The tool gets a response like
Details: Token not found

text:Error: Bad request - please check your parameters\n\nDetails: Token not found

Image

### To Reproduce

Use http tools with an MCP server and have an OAuth2 credential setup to connect with HaloPSA.
It works when you have done some manual queries and it works with teh AI agent for about an hour and then it stops working.

Looking at the credential is currently 3:29pm 7/12/25. it shows last updated at
"updatedAt":"2025-12-05T04:05:40.280Z"

And the MCP has been failing since 4/12 23:38 which is just over an hour after I last manually ran one of the http tools in the MCP server.

Why are the custom credentials not updating hte auth token when the tools are being called by the ai agent? 

Additionally its showing all of these as successful runs, but the tools failed with token issues!

Running a normal HTTP code manually. Its refreshed the token prior to running.
updatedAt":"2025-12-07T15:40:19.580Z

I am trying a workaround with a schedule trigger to run a http get every 55mins to try and keep the token valid!

### Expected behavior

The token should refresh when its expired and it should use a valid token in the http tool calls!

The oauth2 credential is client credentials so it does not need a refresh token, but the refresh token is in the response as well so there is zero reason this should not be keeping up to date.

### Debug Info

# Debug info

## core

- n8nVersion: 1.122.4
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: c4b8d293-4d76-478f-9247-30ae5e7e8dbb

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 15000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36 edg/142.0.0.0
- isTouchDevice: true

Generated at: 2025-12-07T15:44:53.587Z

### Operating System

Ubuntu 24.04

### n8n Version

1.122.4

### Node.js Version

22.21.0

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by elsmr**
## Summary

The MCP Client Tool passed OAuth2 tokens as static headers to MCP SDK transports at connection time. When tokens expired during a session, or for a tool call, the token was never refreshed.

This PR introduces a `createAuthFetch()` wrapper that:
- On 401 response, calls the existing `onUnauthorized` handler (refreshing the token)
- Retries the failed request once with the refreshed token

## Related Linear tickets, Github issues, and Community forum posts

- https://linear.app/n8n/issue/NODE-4487
- Fixes #22893

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/@n8n/nodes-langchain/nodes/mcp/shared/utils.ts [hunk 1]
```diff
@@ -153,34 +139,19 @@ export async function connectMcpClient({
 		const sseTransport = new SSEClientTransport(endpoint.result, {
 			eventSourceInit: {
 				fetch: async (url, init) =>
-					await proxyFetch(url, {
+					await authFetch(url, {
 						...init,
 						headers: {
-							...headers,
+							...init?.headers,
```
Comment (ShireenMissi) [inline packages/@n8n/nodes-langchain/nodes/mcp/shared/utils.ts]: should this be ...headersToRecord(init?.headers)?

**Review by ShireenMissi — COMMENTED** [review]
The fix looks good, only left one comment 👍

**Review by ShireenMissi — APPROVED** [review]
LGTM 🎉
