### PR TITLE
fix(Perplexity Node): Update model from 'r1-1776' to 'sonar' in API and tests

### LINKED ISSUE #19438: Perplexity Credentials page always fails to verify
Cross-ref to community topics:
https://community.n8n.io/t/perplexity-ai-credential-error-bad-request-please-check-your-parameters/178058
https://community.n8n.io/t/perplexity-node-credential-test-fails-but-node-executes-successfully/174721
https://community.n8n.io/t/perplexity-api-key-not-working-in-n8n/182053

## Describe the problem/error/question

When adding Perplexity node and configuring its credentials, verification always fails.

## Please share your workflow/screenshots/recording

Credentials verification always fails with the following error:
"Could not connect with these settings"

Image

No workflow example needed.

## Share the output returned by the last node

While credentials page fails to verify, if ignored, the node itself works with appropriate models.

### core

- n8nVersion: 1.110.1
- platform: docker (self-hosted)
- nodeJsVersion: 22.19.0
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

### client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/140.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-09-11T18:35:17.090Z

### PR DESCRIPTION
**Pull request by jabbson**
## Summary

Perplexity [deprecated and removed](https://docs.perplexity.ai/changelog/changelog?utm_source=chatgpt.com#august-2025) `r1-1776` model. This PR updates the Perplexity node to use supported models - defaulting to sonar - so that:
- Credential tests succeed again.
- New Perplexity “Chat Completions” executions use a current model by default.
- The model dropdown reflects Perplexity’s currently available choices.

## Related Linear tickets, Github issues, and Community forum posts

Cross-ref to community topics:
https://community.n8n.io/t/perplexity-ai-credential-error-bad-request-please-check-your-parameters/178058
https://community.n8n.io/t/perplexity-node-credential-test-fails-but-node-executes-successfully/174721
https://community.n8n.io/t/perplexity-api-key-not-working-in-n8n/182053

fixes #19438

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created (no documents are affected).
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @jabbson,

Thank you for your contribution. We appreciate the time and effort you’ve taken to submit this pull request.

Before we can proceed, please ensure the following:
	•	Tests are included for any new functionality, logic changes or bug fixes.
	•	The PR aligns with our contribution guidelines.

Regarding new nodes:
We no longer accept new nodes directly into the core codebase. Instead, we encourage contributors to follow our Community Node Submission Guide to publish nodes independently.

If your node integrates with an AI service that you own or represent, please email nodes@n8n.io and we will be happy to discuss the best approach.

About review timelines:
This PR has been added to our internal tracker as "GHC-4343". While we plan to review it, we are currently unable to provide an exact timeframe. Our goal is to begin reviews within a month, but this may change depending on team priorities. We will reach out when the review begins.

Thank you again for contributing to n8n.

File: packages/nodes-base/nodes/Perplexity/descriptions/chat/complete.operation.ts [hunk 1]
```diff
@@ -6,10 +6,9 @@ const properties: INodeProperties[] = [
 		displayName: 'Model',
 		name: 'model',
 		type: 'options',
-		default: 'r1-1776',
+		default: 'sonar',
```
Comment (mutdmour) [inline packages/nodes-base/nodes/Perplexity/descriptions/chat/complete.operation.ts:9]: Usually changing the default value of a parameter is not a backward compatible change. 
In this case, since the model is completely deprecated and would just cause an error, it's okay to make this change

**Review by mutdmour — APPROVED** [review]
Thanks for the fix 🙏🏽

**Comment by Joffcom** [comment]
Got released with [`n8n@1.112.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.112.0)
