### PR TITLE
fix(core): AugmentObject should check for own propeties correctly

### LINKED ISSUE #12521: Overwritting the "toString" field in the JSON
### Bug Description

It seems that n8n is omitting the field named `toString` when parsing the data.

For example, given an object like:
```
{
    from: 123,
    fromString: "Some from string",
    to: 456,
    toString: "Some to string"
}
```
the n8n is parsing it into:
```
{
    from: 123,
    fromString: "Some from string",
    to: 456
}
```

I assume this is happening because there is also a JS built-in `toString` function so it gets overwritten or omitted.

### To Reproduce

We're facing this issue as we're trying to consume Jira's API, specifically this API endpoint: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-changelog-get

which in its response is returning an object similar to the one from the bug description above.

### Expected behavior

n8n shouldn't omit the `toString` field from the JSON object.

### Operating System

MacOS 14.4.1

### n8n Version

1.72.1

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by netroy**
## Summary
This updates `AugmentObject` to check for own properties using `hasOwnProperty` instead of the `in` operator.

## Related Linear tickets, Github issues, and Community forum posts
CAT-498
closes #12521

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/workflow/src/AugmentObject.ts [hunk 1]
```diff
@@ -102,11 +105,11 @@ export function augmentObject<T extends object>(data: T): T {
...
 			return value;
 		},
-		deleteProperty(target, key: string) {
-			if (key in newData) {
+		deleteProperty(_target, key: string) {
+			if (hasOwnProperty.call(newData, key)) {
 				delete newData[key];
 			}
-			if (key in target) {
+			if (hasOwnProperty.call(data, key)) {
```
Comment (tomi) [inline packages/workflow/src/AugmentObject.ts:112]: This now uses `data` instead of `target`. Is that change intentional? I assume they should refer to the same object, right?

**Review by tomi — APPROVED** [review]
🚀

File: packages/workflow/src/AugmentObject.ts (hunk 1 above)
Comment (netroy) [reply packages/workflow/src/AugmentObject.ts:112]: yeah. I found using `data` and `newData` less confusing than `target` and `newData`.

**Comment by janober** [comment]
Got released with [`n8n@1.75.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.75.0)
