### PR TITLE
fix(editor): Fix empty credential translation

### LINKED ISSUE #19625: n8n API credential missing fields like: Base URL, API KEY
### Bug Description

When creating a new predefined credential (n8n API), the fields that need to be filled in do not appear. In version 1.110.1 it is working normally.

### To Reproduce

1. Go to create credential
2. select n8n API app
3. Image
4. Image

### Expected behavior

Image

### Debug Info

# Debug info

## core

- n8nVersion: 1.112.0
- platform: docker (self-hosted)
- nodeJsVersion: 22.19.0
- database: postgres
- executionMode: scaling (single-main)
- concurrency: -1
- license: enterprise (production)
- consumerId: fafdd528-2e4a-49ca-868f-fd6433945ec3

## storage

- success: none
- error: all
- progress: true
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/140.0.0.0 safari/537.36 edg/140.0.0.0
- isTouchDevice: false

Generated at: 2025-09-17T03:13:50.117Z

### Operating System

Linux n8n 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 Linux

### n8n Version

1.112.0

### Node.js Version

v22.19.0

### Database

PostgreSQL

### Execution mode

queue

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by afitzek**
## Summary

When n8n executed with locale different to `en` we support translating the credential fields in the UI. If these translations are missing, a null reference in the i18n module leads to credential fields not being shown. This avoid overwriting the credential field names with a null value if these are not available.

## Related Linear tickets, Github issues, and Community forum posts

closes https://linear.app/n8n/issue/PAY-3865/community-issue-n8n-api-credential-missing-fields-like-base-url-api
closes https://github.com/n8n-io/n8n/issues/19625

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/components/CredentialEdit/CredentialConfig.vue [hunk 1]
```diff
@@ -92,6 +92,8 @@ onBeforeMount(async () => {
 		props.credentialType.name,
 	);
 
+	if (!credTranslation) return;
```
Comment (MarcL) [inline packages/frontend/editor-ui/src/components/CredentialEdit/CredentialConfig.vue:95]: Should we have tests for it?

Comment (afitzek) [reply packages/frontend/editor-ui/src/components/CredentialEdit/CredentialConfig.vue:95]: @MarcL good point. added 👍

**Review by cstuncsik — APPROVED** [review]

**Comment by Joffcom** [comment]
Got released with [`n8n@1.114.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.114.0)
