### PR TITLE
Fix migrations on non-public Postgres schema

### LINKED ISSUE #3325: Postgres migrations are inconsistent on alternate schema
**Describe the bug**
The current migrations are inconsistent, which means that there is no way to start a new n8n instance on a clean Postgres DB with an alternate schema. Following your docker-compose example produces the following output:

```
Initializing n8n process
UserSettings were generated and saved to: /root/.n8n/config
query is slow: SELECT * FROM "n8n"."migrations" "migrations"  ORDER BY "id" DESC
execution time: 3234
There was an error initializing DB: "relation "credentials_entity" does not exist"

Stopping n8n...
```

**To Reproduce**
1. Follow the docker-compose example for Postgres by using a schema other than `public`

**Expected behavior**
All migrations should run as expected and the application should startup

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version: docker digest 403a10ae480e18502eb80ca6490a5ba54555251911ff91c1766dd6c30987fdaa
 - Node.js Version: the container's
 - Database system: Postgres
 - Operation mode: own

**Recommendations**
- [ ] Provide an extra cli command to run only the migrations 
- [ ] Introduce an extra CI check to ensure the all migrations for all db engines are working as expected

### PR DESCRIPTION
**Pull request by ivov**
Close #3325

### CODE REVIEW

File: packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts [hunk 1]
```diff
@@ -14,6 +14,8 @@ export class InitialMigration1587669153312 implements MigrationInterface {
 			tablePrefix = schema + '.' + tablePrefix;
 		}
 
+		await queryRunner.query(`SET search_path TO ${schema};`);
```
Comment (BHesseldieck) [inline packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts:17]: don't we have to do this in every migration?

File: packages/cli/test/integration/shared/testDb.ts [hunk 2]
```diff
@@ -35,21 +40,42 @@ export async function init() {
...
 		const testDbName = `pg_${randomString(6, 10)}_${Date.now()}_n8n_test`;
 		await bootstrapPostgres.query(`CREATE DATABASE ${testDbName};`);
 
+		try {
+			const schema = config.getEnv('database.postgresdb.schema');
+			await exec(`psql -d ${testDbName} -c "CREATE SCHEMA IF NOT EXISTS ${schema}";`);
+		} catch (error) {
+			if (error instanceof Error && error.message.includes('command not found')) {
+				console.error('psql command not found. Make sure psql is installed and added to your PATH.');
+			}
```
Comment (BHesseldieck) [inline packages/cli/test/integration/shared/testDb.ts:75]: hmmm so we now add `psql` as a dependency for the `test:postgres` command?

**Review by BHesseldieck — APPROVED** [review]

File: packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts (hunk 1 above)
Comment (ivov) [reply packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts:17]: That's the beauty of it :)

File: packages/cli/test/integration/shared/testDb.ts (hunk 2 above)
Comment (ivov) [reply packages/cli/test/integration/shared/testDb.ts:75]: Just like we are depending on the `mysql` command-line client:

https://github.com/n8n-io/n8n/blob/c38f6af4993cd695888ff18b3f95e0d900e65711/packages/cli/test/setup.ts#L22

Is there a way to avoid this?

File: packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts (hunk 1 above)
Comment (BHesseldieck) [reply packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts:17]: but it just gets executed for fresh DBs, am I mistaken?

Comment (ivov) [reply packages/cli/src/databases/postgresdb/migrations/1587669153312-InitialMigration.ts:17]: Good point! Please see latest commits. Re-ran `npm run test:postgres -- integration` and `npm run test:postgres:alt-schema -- integration` and both passing.

File: packages/cli/test/integration/shared/testDb.ts (hunk 2 above)
Comment (ivov) [reply packages/cli/test/integration/shared/testDb.ts:75]: As discussed, `psql` ships with PG.

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.179.0`
