### PR TITLE
fix: Correctly parse curl command with encoding

### LINKED ISSUE #22699: Import cURL: Destroys value of --data
### Bug Description

When trying to import a curl command to a HTTP node it destroys the value of --data.

### To Reproduce

Create a new HTTP node and then Import cURL this:

```console
curl --request POST \
  --url https://example.com/api \
  --header 'content-type: application/json; charset=UTF-8' \
  --data '{"userId":"123","active":false,"visited":false}'
```

It turns the value of --data into "userId" and nothing more:

Image

### Expected behavior

Properly parse cURL commands. In this case especially the --data field

### Debug Info

# Debug info

## core

- n8nVersion: 1.121.3
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- database: sqlite
- executionMode: regular
- concurrency: -1

## storage

- success: none
- error: all
- progress: true
- manual: false
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: true

Generated at: 2025-12-03T20:54:28.626Z

### Operating System

Linux

### n8n Version

1.121.3

### Node.js Version

docker image

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by dlavrenuek**
## Summary

Fixes parsing of CURL command data when content type includes encoding or is not recognized

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-4062/community-issue-import-curl-destroys-value-of-data
Fixes #22699

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/app/composables/useImportCurlCommand.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ interface HttpNodeParameters extends Record<string, unknown> {
 		parameters: Parameter[];
 	};
 	jsonBody?: object;
+	body?: string;
```
Comment (dlavrenuek) [inline packages/frontend/editor-ui/src/app/composables/useImportCurlCommand.ts:32]: The `body` property was missing in the type although it was clearly set on line 337

**Review by michael-radency — APPROVED** [review]
working as  expected, LGTM
