### PR TITLE
fix(Jira Software Node): Get All Issues operation with Return All hangs

### LINKED ISSUE #16493: Jira Node (self hosted): get all issues never ends
### Bug Description

jira node  with:

- Get many issues 
- Return All option 

never ends. 

Memory is growing on workers
(sounds like pagination infinite loop)

Uncheck Return All, it works again (but we are limited)

### To Reproduce

1. Create a jira node with self hosted credentials
2. Get many issues with jql and fields
3. Test it, it never ends

Image

### Expected behavior

Works well in n8n 1.85.4

I suspect this commit to be involved:
[link](https://github.com/n8n-io/n8n/commit/216bdd15fd94f9a427a86aaf0a9291e7d4df4056)

Jira v10.4.1

### Operating System

Docker

### n8n Version

1.97.1

### Node.js Version

20.19.2

### Database

PostgreSQL

### Execution mode

queue

### PR DESCRIPTION
**Pull request by RomanDavydchuk**
## Summary

Fix a bug where when executing `issue:getAll` operation with `returnAll` enabled, the node is stuck in an infinite loop. This was caused by improper handling of offset-based pagination with `POST` requests. The issue is present only on self-hosted

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-3229/community-issue-jira-node-get-all-issues-never-ends
Closes #16493

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Jira/GenericFunctions.ts [hunk 1]
```diff
@@ -76,16 +76,23 @@ export async function jiraSoftwareCloudApiRequest(
...
+				query.startAt = 0;
+				query.maxResults = 100;
+			} else {
+				body.startAt = 0;
+				body.maxResults = 100;
+			}
 		} else {
+			// token pagination is used only in POST requests
 			body.maxResults = 100;
 		}
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Jira/GenericFunctions.ts]: @RomanDavydchuk could you please add comment with link to API documentation page covering this?

**Review by michael-radency — CHANGES_REQUESTED** [review]

File: packages/nodes-base/nodes/Jira/GenericFunctions.ts (hunk 1 above)
Comment (RomanDavydchuk) [reply packages/nodes-base/nodes/Jira/GenericFunctions.ts]: After looking through the docs, looks like there are endpoints that use `token` pagination type with `GET`, so I updated the code to handle that, even though there are no such requests in the node currently

Regarding docs: haven't found any "general" page that has both of these pagination types documented, so I added a link to an example endpoint for each pagination type + request pair, hope this would be helpful

**Review by michael-radency — APPROVED** [review]
LGTM

**Comment by janober** [comment]
Got released with [`n8n@1.107.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.107.0)
