### PR TITLE
fix(core): Add support for .cn Amazon regions

### LINKED ISSUE #14764: Credentials - AWS China is not supported
### Bug Description

Cannot use AWS China region since all the URL generated for AWS services are wrong.

### To Reproduce

1. Create a new Credential, AWS account, on China region.
2. On save, an error will appear on screen, and the following log will be recorded:
_The connection cannot be established, this usually occurs due to an incorrect host (domain) value
getaddrinfo ENOTFOUND sts.cn-north-1.amazonaws.com_

### Explanation

The reason is that n8n use ".amazonaws.com" hardcoded in all the URL for STS (and other services). But the URL in AWS china is ".amazonaws.com.**cn**".

A quick & dirty solution is to replace all ".amazonaws.com" by ".amazonaws.com.cn" in the files "node_modules/n8n-nodes-base/dist/credentials/Aws.credentials.js" and "node_modules/n8n-nodes-base/dist/credentials/Aws.credentials.js.map" if you only need support of China region.

A good solution will be to append .cn suffix when the selected region is AWS China.

The best solution will be to use [AWS SDK regional](https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html) to retrieve the full URL instead of relying on hardcoded values.

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.88

### Node.js Version

22

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by yehorkardash**
## Summary

This PR adds support of AWS China credentials. The issue happened because AWS china used `.amazon.com.cn` instead of `amazon.com`

It also fixes invalid order of ifs. `service === 'ssm'` was condition was unreachable
```
else if (service) {
  endpointString = `https://${service}.${region}.amazonaws.com`;
} else if (service === 'ssm' && credentials.ssmEndpoint) {
  endpointString = credentials.ssmEndpoint;
}				
```
On master:
image

On current branch:
image

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/NODE-2888/community-issue-credentials-aws-china-is-not-supported
closes #14764 

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/credentials/Aws.credentials.ts [hunk 1]
```diff
@@ -211,12 +223,19 @@ export type AwsCredentialsType = {
...
 // Some AWS services are global and don't have a region
 // https://docs.aws.amazon.com/general/latest/gr/rande.html#global-endpoints
 // Example: iam.amazonaws.com (global), s3.us-east-1.amazonaws.com (regional)
 function parseAwsUrl(url: URL): { region: AWSRegion | null; service: string } {
-	const [service, region] = url.hostname.replace('amazonaws.com', '').split('.');
-	return { service, region: region as AWSRegion };
+	const hostname = url.hostname;
+	// Handle both .amazonaws.com and .amazonaws.com.cn domains
+	const [service, region] = hostname.replace(/\.amazonaws\.com.*$/, '').split('.');
+	console.log('parse AwsUrl', { service, region, hostname });
```
Comment (michael-radency) [inline packages/nodes-base/credentials/Aws.credentials.ts]: please remove this console.log

**Review by michael-radency — CHANGES_REQUESTED** [review]
LGTM, added single comment

**Review by michael-radency — APPROVED** [review]
LGTM

**Comment by Joffcom** [comment]
Got released with [`n8n@1.112.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.112.0)
