### PR TITLE
fix(Gmail Node): Use Reply-To header when replying to a message

### LINKED ISSUE #20837: Replying to Gmail message doesn't send it to "reply-to" email address
## Describe the problem/error/question

I've set up a workflow that is triggered by new emails in a specific Gmail label. I'm facing an issue when an incoming email is sent via a proxy email address, which results in the email having different From and Reply-To headers.

My workflow's Slack action is supposed to reply to the sender, but it's defaulting to the From address and completely ignoring the Reply-To address. This causes the reply to be sent to the proxy instead of the original sender.

> from: | 'user' via Data Protection Officer <dpo@mycompany.com>
> reply-to: | user <user@email.com>
> to: | "dpo@musixmatch.com" <dpo@mycompany.com>

 

## Please share your workflow/screenshots/recording

{
  "nodes": [
    {
      "parameters": {
        "operation": "reply",
        "messageId": "={{ $('Normalize data for flow execution').item.json['gmail-id'] }}",
        "message": "=Dear user,\n<br><br>\nWe have received your request to delete your personal data associated to email address {{ $('Normalize data for flow execution').item.json['email-address'] }}, but could not find it in our database.\n<br><br>\nThis could be for one of the following reasons:\n<br>\n<ul>\n<li>A Musixmatch account was never registered using this specific email address. If you believe you signed up with a different address, please resubmit your request from that email account for verification.</li>\n  <li>The account associated with this email address has already been deleted in the past.</li>\n  <li>The account was created using the Sign in with Apple feature with the \"Hide My Email\" privacy option enabled.</li>\n</ul>\nIf the third option applies to you, please note that Musixmatch does not have access to your real email address, only a unique, anonymized one created by Apple.\n<br>\nIn this case, the procedure to delete your personal data requires you to log in to your Musixmatch account using your Apple ID and delete the account directly from your settings.\n<br><br>\nBest regards,<br>\nMusixmatch Security Team",
        "options": {}
      },
      "type": "n8n-nodes-base.gmail",
      "typeVersion": 2.1,
      "position": [
        1168,
        272
      ],
      "id": "d1e9cdf7-d0d3-4f8b-95a4-0aee07c7269f",
      "name": "Sorry can't find you in the database",
      "webhookId": "fbeba61d-5b77-4430-8b0b-1f73c2ed2497",
      "credentials": {
        "gmailOAuth2": {
          "id": "4TIXFcbt3VHRdZ2A",
          "name": "Leonardo Preti Gmail"
        }
      }
    }
  ],
  "connections": {
    "Sorry can't find you in the database": {
      "main": [
        []
      ]
    }
  },
  "pinData": {},
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "eccd5f8d0e25825ef869dca09b16bc7e765031254ace9787df2b117e38cd2f23"
  }
}

### core

- n8nVersion: 1.112.3
- platform: docker (self-hosted)
- nodeJsVersion: 20.19.4
- database: postgres
- executionMode: scaling (single-main)
- concurrency: -1
- license: enterprise (production)

### storage

- success: all
- error: all
- progress: true
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 720 hours
- maxCount: 50000 executions

### client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/141.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-10-15T10:04:19.905Z}

### PR DESCRIPTION
**Pull request by RomanDavydchuk**
## Summary

An email contains a `From` header, which has sender's email address, but it also _may_ contain a `Reply-To` header. It specifies which email address to send a reply to, when replying to this message. The Gmail node did not respect this header before, but now it does

Steps to manually test:
1. Set up a workflow with a Gmail trigger and a Gmail node with "Reply to a message" operation right after it. Sample workflow:
```json
{
  "nodes": [
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        },
        "simple": false,
        "filters": {},
        "options": {}
      },
      "type": "n8n-nodes-base.gmailTrigger",
      "typeVersion": 1.3,
      "position": [
        0,
        0
      ],
      "id": "649a5b60-76eb-4d29-b1ec-9b5e54c1ebdd",
      "name": "Gmail Trigger",
      "credentials": {
        "gmailOAuth2": {
          "id": "CAEKyK4ibfYyUuQb",
          "name": "Gmail (throwaway)"
        }
      }
    },
    {
      "parameters": {
        "operation": "reply",
        "messageId": "={{ $json.id }}",
        "message": "This is a reply",
        "options": {}
      },
      "type": "n8n-nodes-base.gmail",
      "typeVersion": 2.1,
      "position": [
        208,
        0
      ],
      "id": "931126fa-13f9-4823-9806-f8a393815879",
      "name": "Reply to a message",
      "webhookId": "3b67034b-14ff-4a4b-b4fa-bfb9c22b0a09",
      "credentials": {
        "gmailOAuth2": {
          "id": "CAEKyK4ibfYyUuQb",
          "name": "Gmail (throwaway)"
        }
      }
    }
  ],
  "connections": {
    "Gmail Trigger": {
      "main": [
        [
          {
            "node": "Reply to a message",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "eeda9e3069aca300d1dfceeb64beb5b53d715db44a50461bbc5cb0cf6daa01e3"
  }
}
```
2. Send an email from address A to the address that the trigger is listening on (address B). Verify that you receive a reply to the same address that you sent the original email from (address A)
3. Set a `Reply-To` option for your sender address (address A) to a different one (address C) ([example guide](https://mailmeteor.com/blog/how-to-send-emails-with-reply-to-gmail))
4. Send an email from address A to address B. Verify that you receive a reply to the **address C**, since it's the one that is in `Reply-To` header

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-3976/community-issue-replying-to-gmail-message-doesnt-send-it-to-reply-to
Closes #20837

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Google/Gmail/utils/replyToEmail.ts [hunk 1]
```diff
@@ -97,14 +97,17 @@ export async function replyToEmail(
 		}
 	};
 
+	const replyToHeaderName = payload.headers.find((h) => h.name.toLowerCase() === 'reply-to')
```
[the remark this answers is not in the document]
Comment (RomanDavydchuk) [reply packages/nodes-base/nodes/Google/Gmail/utils/replyToEmail.ts]: There is a test for this

Comment (yehorkardash) [inline packages/nodes-base/nodes/Google/Gmail/utils/replyToEmail.ts]: I think some user might rely on this behavior, would it be better to version the change?

Comment (RomanDavydchuk) [reply packages/nodes-base/nodes/Google/Gmail/utils/replyToEmail.ts]: true, that is possible. added a new light version

**Review by yehorkardash — APPROVED** [review]
