### PR TITLE
fix(Google Sheets Node): Include all headers

### LINKED ISSUE #16923: “Set Outputs” overwrites header row whenever the triggering row has empty cells
### Bug Description

Any workflow that relies on **Evaluation Trigger ➜ Set Outputs ➜ Google Sheets**
can silently corrupt the sheet:

* Columns that are **empty in the triggering row disappear** from the header.
* Newly emitted keys are **inserted in the middle**, shifting every subsequent
  value one column to the left.
* Google Sheets then auto-adds fresh columns for the leftovers, so the damage
  grows with every run.

This makes it nearly impossible to build reliable automated tests, because a
single blank cell—or a typo you notice only after the run—ruins the entire
table.

> **See also:** previously reported issue *#16915* (positional mapping bug).  
> Delivering mission-critical nodes that can rewrite a sheet’s schema on accident is not the robustness we expect from n8n.

### To Reproduce

1. Create a Google Sheet with the following headers:

   input_a, expected_a, actual_a, expected_b, actual_b, expected_c, actual_c

2. Add a row with only these values:

   input_a = foo  
   expected_a = expected_a  
   (leave all other fields blank)

  Or use this: https://docs.google.com/spreadsheets/d/10BEgQOESk2vKlAkKhG1RMn82lqy7LgObuxZVDRTMCzA/edit?usp=sharing

3. Create a workflow:
   - Evaluation Trigger (triggering on that row)
   - Set Outputs with:
     - actual_a = "✔ ok"
     - actual_b = ""
     - actual_c = ""
   - Google Sheets node (Update)
  
  Or use this: [workflow-corrupting-sheet-with-empty-cells.json](https://github.com/user-attachments/files/21017960/workflow-corrupting-sheet-with-empty-cells.json)

4. Run the workflow from the Evaluation Trigger

5. After the run, observe the header has changed to:

   input_a, expected_a, actual_a, actual_b, actual_c, expected_b, expected_c

The expected_* columns disappeared from the middle and were recreated at the end. All values are now misaligned.

### Expected behavior

Expected Behavior

- The header row must never change as a side-effect of a blank value.
- The column structure should be treated as sacred — especially during test-related operations.
- New keys should:
  - Be validated against the actual header row
  - Or raise a clear error if they don’t match
  - Never silently mutate the sheet

At the absolute minimum, users deserve a toggle like "Strict mode" or "Fail if key not in header".

This needs fixing urgently — because right now, **we are forced to hack around this with placeholder dashes in every column**, just to stop the system from damaging itself. That’s not automation. That’s babysitting.

### Operating System

k8s

### n8n Version

latest

### Node.js Version

v22+

### Database

PostgreSQL

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by dana-gill**
## Summary

When the number of headers in a sheet is more than the number of items
in a row, this causes values to be missing. This was causing the evaluation trigger to return an inaccurate number columns, which cause the evaluation node to overwrite.

To test:

1. Setup a Google Sheet like this. Note that Column C, first row has a value but the other rows in Column C are empty.
Screenshot 2025-07-02 at 17 02 16

2. Use this workflow

```
{
  "nodes": [
    {
      "parameters": {
        "documentId": {
          "__rl": true,
          "value": "1oqFpPgEPTGDw7BPkp1SfPXq3Cb3Hyr1SROtf-Ec4zvA",
          "mode": "list",
          "cachedResultName": "my sheet",
          "cachedResultUrl": "https://docs.google.com/spreadsheets/d/1oqFpPgEPTGDw7BPkp1SfPXq3Cb3Hyr1SROtf-Ec4zvA/edit?usp=drivesdk"
        },
        "sheetName": {
          "__rl": true,
          "value": 1944804301,
          "mode": "list",
          "cachedResultName": "davidbug",
          "cachedResultUrl": "https://docs.google.com/spreadsheets/d/1oqFpPgEPTGDw7BPkp1SfPXq3Cb3Hyr1SROtf-Ec4zvA/edit#gid=1944804301"
        },
        "limitRows": true
      },
      "type": "n8n-nodes-base.evaluationTrigger",
      "typeVersion": 4.6,
      "position": [
        -480,
        160
      ],
      "id": "3a1f0a22-a0d8-4026-8ccd-1c348daf7dd0",
      "name": "When fetching a dataset row",
      "credentials": {
        "googleSheetsOAuth2Api": {
          "id": "jxkDDD4FYFxW5o7W",
          "name": "Google Sheets account 2"
        }
      }
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "1a586375-0f84-4992-98f5-081b87e472fd",
              "name": "message.content.category",
              "value": "err",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        32,
        160
      ],
      "id": "9889f1db-60de-427d-bbe6-a9b1233981d7",
      "name": "Edit Fields"
    },
    {
      "parameters": {
        "documentId": {
          "__rl": true,
          "value": "1oqFpPgEPTGDw7BPkp1SfPXq3Cb3Hyr1SROtf-Ec4zvA",
          "mode": "list",
          "cachedResultName": "my sheet",
          "cachedResultUrl": "https://docs.google.com/spreadsheets/d/1oqFpPgEPTGDw7BPkp1SfPXq3Cb3Hyr1SROtf-Ec4zvA/edit?usp=drivesdk"
        },
        "sheetName": {
          "__rl": true,
          "value": 1944804301,
          "mode": "list",
          "cachedResultName": "davidbug",
          "cachedResultUrl": "https://docs.google.com/spreadsheets/d/1oqFpPgEPTGDw7BPkp1SfPXq3Cb3Hyr1SROtf-Ec4zvA/edit#gid=1944804301"
        },
        "outputs": {
          "values": [
            {
              "outputName": "classification_test",
              "outputValue": "={{ $json.message.content.category.concat(\"50\") }}"
            }
          ]
        }
      },
      "type": "n8n-nodes-base.evaluation",
      "typeVersion": 4.6,
      "position": [
        352,
        160
      ],
      "id": "16cadd36-49c2-4cff-aaa2-414370e52dcd",
      "name": "Set output",
      "credentials": {
        "googleSheetsOAuth2Api": {
          "id": "jxkDDD4FYFxW5o7W",
          "name": "Google Sheets account 2"
        }
      }
    }
  ],
  "connections": {
    "When fetching a dataset row": {
      "main": [
        [
          {
            "node": "Edit Fields",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields": {
      "main": [
        [
          {
            "node": "Set output",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "instanceId": "ee90fdf8d57662f949e6c691dc07fa0fd2f66e1eee28ed82ef06658223e67255"
  }
}
```
3. Observe that the `rating` column does not get overwritten

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-3200/bug-evals-set-output-op-overwrites-wrong-column
fixes [16923](https://github.com/n8n-io/n8n/issues/16923)

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Google/Sheet/v2/actions/utils/readOperation.ts [hunk 1]
```diff
@@ -33,6 +33,9 @@ export async function readSheet(
 		dataLocationOnSheetOptions.rangeDefinition = 'detectAutomatically';
 	}
 
+	const includeHeadersWithEmptyCells =
+		(additionalOptions?.includeHeadersWithEmptyCells as boolean) ?? false;
+
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Google/Sheet/v2/actions/utils/readOperation.ts:38]: we may want to expose this in options, or add explanation why it is here and not in parameters

**Review by michael-radency — APPROVED** [review]
LGTM

**Comment by janober** [comment]
Got released with [`n8n@1.101.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.101.1)
