### PR TITLE
fix(Postgres Node): Enable non-numeric comparisons for WHERE clause operators

### LINKED ISSUE #14971: Postgres node not properly working with date comparison
### Bug Description

```
Operator in entry 1 of 'Select Rows' works with numbers, but value 2025-04-28 is not a number
```

### To Reproduce

https://github.com/n8n-io/n8n/blob/d2178a13b17ac3c63e402c2a995de155b0fa9eb8/packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts#L159

PostgreSQL type is `TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP` (`timestamp with time zone`)

### Expected behavior

Change condition

### Operating System

123

### n8n Version

123

### Node.js Version

123

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by ongdisheng**
## Summary

This PR fixes an issue where the Postgres node threw "not a number" errors when using comparison operators (`>`, `>=`, `<`, `<=`) with dates or strings in WHERE clauses. The fix removes the numeric-only restriction while maintaining performance by converting numeric strings to numbers and leaving other values as strings for PostgreSQL's native type handling. This enables essential database operations like date comparisons (`created_at >= '2025-04-28'`) and string comparisons (`name > 'M'`).

### Screenshot
image

## Related Linear tickets, Github issues, and Community forum posts

Closes #14971 

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @ongdisheng,

Thank you for your contribution. We appreciate the time and effort you’ve taken to submit this pull request.

Before we can proceed, please ensure the following:
	•	Tests are included for any new functionality, logic changes or bug fixes.
	•	The PR aligns with our contribution guidelines.

Regarding new nodes:
We no longer accept new nodes directly into the core codebase. Instead, we encourage contributors to follow our Community Node Submission Guide to publish nodes independently.

If your node integrates with an AI service that you own or represent, please email nodes@n8n.io and we will be happy to discuss the best approach.

About review timelines:
This PR has been added to our internal tracker as "GHC-3869". While we plan to review it, we are currently unable to provide an exact timeframe. Our goal is to begin reviews within a month, but this may change depending on team priorities. We will reach out when the review begins.

Thank you again for contributing to n8n.

File: packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts [hunk 1]
```diff
@@ -154,21 +154,12 @@ export function addWhereClauses(
...
-					node,
-					`Operator in entry ${index + 1} of 'Select Rows' works with numbers, but value ${
-						clause.value
-					} is not a number`,
-					{
-						itemIndex,
-					},
-				);
-			}
+			const numericValue = Number(clause.value);
```
[the remark this answers is not in the document]
Comment (ongdisheng) [reply packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts:156]: Fix in https://github.com/n8n-io/n8n/pull/18544/commits/7ed3ea662c6ae908ea513ce57cced5612c3ecca0

File: packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts [hunk 2]
```diff
@@ -153,21 +153,17 @@ export function addWhereClauses(
...
+			const numericValue =
+				typeof clause.value === 'string' &&
+				clause.value.trim() !== '' &&
+				!Number.isNaN(Number(clause.value))
+					? Number(clause.value)
+					: NaN;
+
+			// Convert to number if numeric, otherwise keep as string for dates/text
+			if (!Number.isNaN(numericValue)) {
+				clause.value = numericValue;
```
Comment (dlavrenuek) [inline packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts]: The code here and the checks are quite complex for something that should be easy (inline condition with 3 operators, two times `Number.isNaN()`, two times conversion via `Number(clause.value)`). I suggest simplifying it to something like:

```js
const numericValue = Number(clause.value);
if (clause.value.trim() !== '' && !Number.isNaN(numericValue)) {
  clause.value = numericValue;
}
```

**Review by dlavrenuek — CHANGES_REQUESTED** [review]
Thank you for your contribution! The code looks quite complex to me, I've added a suggestion on how to improve it. Since it has been a long time since the PR was opened I am happy to add the changes myself if you prefer.

File: packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts (hunk 2 above)
Comment (ongdisheng) [reply packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts]: Hi @dlavrenuek, thanks for the review! Really appreciate it, just wondering if is it alright for me to fix this in a few days time?

Comment (dlavrenuek) [reply packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts]: @ongdisheng sure, that would be awesome. Thank's a lot!

**Review by dlavrenuek — APPROVED** [review]
Perfect 🚀
