### PR TITLE
fix(AI Agent Node): Allow removal of system message

### LINKED ISSUE #13710: Cannot use o1-mini, because the Agent uselessly adds "System: You are a helpful assistant"
### Bug Description

Hey. 

o1-mini does not support "system" message. So the workaround would be to put all prompts in the user message. But the AI Agent node automatically adds, for no reason, "You are a helpful assistant" as a system message.

### To Reproduce

1. Create a new Workflow
2. Add a manual Trigger
3. Add an AI Agent node
4. Connect the AI Agent node to a OpenAI o1-mini model
5. Configure the AI Agent node as follow: 
- Source for Prompt = Define Bellow
- Prompt = Hello
6. Click Test Workflow
The following error shows:

> Error in sub-node ‘OpenAI Chat Model‘
> Unsupported value: 'messages[0].role' does not support 'developer' with this model.

7. Open the AI Agent node, click on Logs
The "OpenAi Chat Model Input" displays:

> System: You are a helpful assistant
> Human: Hello

### Expected behavior

The node should not add a System message when there is no reason for it (such as an output parser, tools ...)

### Operating System

Linux 24.04

### n8n Version

1.81.4

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

own (deprecated)

### PR DESCRIPTION
**Pull request by schrothbn**
## Summary
Removes the default system message that is passed when using ToolsAgent if no system message was setup by the user. Only happens for newest node version.
This should prevent blocking models like o1-mini that don't support system messages.

## Related Linear tickets, Github issues, and Community forum posts

fixes #13710 

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts [hunk 1]
```diff
@@ -346,11 +346,17 @@ export async function prepareMessages(
...
 	},
 ): Promise<BaseMessagePromptTemplateLike[]> {
-	const messages: BaseMessagePromptTemplateLike[] = [
-		['system', `{system_message}${options.outputParser ? '\n\n{formatting_instructions}' : ''}`],
-		['placeholder', '{chat_history}'],
-		['human', '{input}'],
-	];
+	const messages: BaseMessagePromptTemplateLike[] =
+		(options.systemMessage ?? ctx.getNode().typeVersion < 1.9)
+			? [
```
Comment (OlegIvaniv) [inline packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts:351]: This would also remove `formatting_instructions` from the system message if output parser is provided but while using the default systemMessage. Might also be worth writing a test for this :P

**Review by OlegIvaniv — CHANGES_REQUESTED** [review]

File: packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts [hunk 2]
```diff
@@ -346,11 +346,20 @@ export async function prepareMessages(
...
-		['human', '{input}'],
-	];
+	const useSystemMessage = options.systemMessage ?? ctx.getNode().typeVersion < 1.9;
+
+	const messages: BaseMessagePromptTemplateLike[] = [];
+
+	if (useSystemMessage) {
+		messages.push([
+			'system',
+			`{system_message}${options.outputParser ? '{formatting_instructions}' : ''}`,
```
Comment (OlegIvaniv) [inline packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts:356]: Let's keep the new-lines from the original version here. Otherwise the formatting_instructions are merged together with the system message:
CleanShot 2025-04-07 at 15 15 30

**Review by OlegIvaniv — CHANGES_REQUESTED** [review]

**Review by OlegIvaniv — DISMISSED** [review]
Thanks for addressing my comments, LGTM!

**Review by OlegIvaniv — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.89.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.89.0)

**Comment by LuukFYI** [comment]
This PR removed the System Message field from all AI Agent Nodes for me, and does not allow me to view, edit or add them anymore.
