### PR TITLE
fix(editor): Implement distance threshold for the Draggable component

### LINKED ISSUE #15155: Drag and Drop Folder/Workflow Issues
### Bug Description

After upgrading to the 1.91.2, I am have issues trying to click on/navigate to my existing workflows. See video for details.

https://github.com/user-attachments/assets/2a32f2fc-00be-47c5-836b-d25e0fbd5ccf

### To Reproduce

1. Go to N8N.
2. Unable to click into workflows and workflows in folders.

### Expected behavior

Easily access workflows with the drag and drop folders.

### Operating System

Cloud

### n8n Version

1.91.2

### Node.js Version

n/a

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by MiloradFilipovic**
## Summary
Introduce distance-based drag threshold for the `Draggable` component.

## Related Linear tickets, Github issues, and Community forum posts
Fixes ADO-4651
Fixes #15155

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/app/components/Draggable.vue [hunk 1]
```diff
@@ -79,6 +83,16 @@ const onDrag = (event: MouseEvent) => {
 	}
 
 	if (!isDragging.value && draggingElement.value) {
+		if (dragStartPosition.value && props.dragThreshold > 0) {
+			const dx = event.pageX - dragStartPosition.value[0];
+			const dy = event.pageY - dragStartPosition.value[1];
+			const distance = Math.sqrt(dx * dx + dy * dy);
+
+			if (distance < props.dragThreshold) {
```
[the remark this answers is not in the document]
Comment (MiloradFilipovic) [reply packages/frontend/editor-ui/src/app/components/Draggable.vue:92]: Ah true, will update

File: packages/frontend/editor-ui/src/app/components/Draggable.vue [hunk 2]
```diff
@@ -11,6 +11,7 @@ type Props = {
 	disabled?: boolean;
 	canDrop?: boolean;
 	stickyPosition?: XYPosition | null;
+	dragThreshold?: number;
```
Comment (dariacodes) [inline packages/frontend/editor-ui/src/app/components/Draggable.vue:15]: Do you think it would be valuable to add a description?
Something like `Minimum distance in pixels the mouse must move before drag operation starts. Prevents accidental drags.`

**Review by dariacodes — DISMISSED** [review]
Great changes! 🚢

File: packages/frontend/editor-ui/src/app/components/Draggable.vue (hunk 2 above)
Comment (MiloradFilipovic) [reply packages/frontend/editor-ui/src/app/components/Draggable.vue:15]: Yup, makes sense

**Review by dariacodes — APPROVED** [review]
