### PR TITLE
fix(YouTube Node): Chunk file content before uploading

### LINKED ISSUE #15270: Error in youtube upload video node (By Docker-compose)
### Bug Description

Error in youtube upload video node
logs:
```
n8n version

1.91.3 (Self Hosted)

Stack trace

AxiosError: Request failed with status code 400 at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:19:12) 
at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:599:11) 
at IncomingMessage.emit (node:events:536:35) at endReadableNT (node:internal/streams/readable:1698:12) 
at processTicksAndRejections (node:internal/process/task_queues:82:21) at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41) at processTicksAndRejections
 (node:internal/process/task_queues:95:5) 
at invokeAxios (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/node-execution-context/utils/request-helper-functions.js:173:16) 
at Object.httpRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/node-execution-context/utils/request-helper-functions.js:669:20) 
at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/YouTube/YouTube.node.js:768:34) 
at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:687:27) 
at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:921:51 
at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:1257:20
```

### To Reproduce

My n8n's Youtube-Node(upload model)
Image
Youtube Channel Manger:
Image
My Docker-Compose.yaml
```
version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    ports:
      - 5442:5432      
    volumes:
      - C:\Users\huang\Documents\Github\n8n-hosting\docker-compose\withPostgres\data\db:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PAYLOAD_SIZE_MAX=1600
      - N8N_FORMDATA_FILE_SIZE_MAX=3000
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem     
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - C:\Users\huang\Documents\Github\n8n-hosting\docker-compose\withPostgres\data\n8n:/home/node/.n8n
      - C:\Users\huang\Documents\Github\n8n-hosting\docker-compose\withPostgres\data\share:/home/node/share
    depends_on:
      postgres:
        condition: service_healthy
```

### Expected behavior

Upload video By n8n's YouTube node, it is not normal.
I search all issues, just set  "N8N_DEFAULT_BINARY_DATA_MODE=filesystem",but it not work too.

### Operating System

Windows（Docker）

### n8n Version

1.91.3

### Node.js Version

v20.19.0

### Database

PostgreSQL

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by michael-radency**
## Summary

in case when N8N_DEFAULT_BINARY_DATA_MODE="default" we need to chunk file content before uploading

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-2967/community-issue-error-in-youtube-upload-video-node-by-docker-compose
closes https://github.com/n8n-io/n8n/issues/15270

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Google/YouTube/GenericFunctions.ts [hunk 1]
```diff
@@ -63,3 +66,17 @@ export async function googleApiRequestAllItems(
...
 	return returnData;
 }
+
+async function* bufferToChunks(buffer: Buffer) {
+	for (let j = 0; j < buffer.length; j += UPLOAD_CHUNK_SIZE) {
+		yield Buffer.from(buffer.subarray(j, j + UPLOAD_CHUNK_SIZE));
+	}
+}
+
+export function getChunkedFileContent(
```
Comment (netroy) [inline packages/nodes-base/nodes/Google/YouTube/GenericFunctions.ts:76]: This feels like we are re-implementing streaming.
Maybe we can do something like [this](https://github.com/n8n-io/n8n/compare/proposal-for-15405?expand=1) instead?

**Review by dana-gill — DISMISSED** [review]
If it's possible to implement adi's request, that would be great :)

**Review by ShireenMissi — APPROVED** [review]
Tested manually and it works 🎉
