### PR TITLE
fix: Bring back TidyUp button's icon and fix Easy AI button size

### LINKED ISSUE #14805: Tidy up icon is gone
### Bug Description

Updated to PreRelease 1.90.1 and since then I am missing the Icon of the "Tidy Up" button on the bottom left of the canvas. The button itself works though.

Image

### To Reproduce

Open any workflow. Look at the bottom left of the canvas.

### Expected behavior

Restore missing icon.

### Operating System

Docker on Ubuntu 20.04

### n8n Version

1.90.1

### Node.js Version

n/a

### Database

PostgreSQL

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by r00gm**
## Summary

image

Remove button padding, so the svg is within bounds

## Related Linear tickets, Github issues, and Community forum posts

fixes #14805

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideButton.vue [hunk 1]
```diff
@@ -20,7 +20,9 @@ const emit = defineEmits<{
 			data-test-id="from-ai-override-button"
 			@click="emit('click')"
 		>
-			<AiStarsIcon size="large" />
+			<span>
```
Comment (CharlieKolb) [inline packages/frontend/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideButton.vue:23]:
```suggestion
<!-- This centers the icon due to reliance on legacy behavior -->
<span>
```

**Review by CharlieKolb — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.90.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.90.2)
