### PR TITLE
Fixes #1364 - Incorrect mouse selection when zoomed in or out

### LINKED ISSUE #1364: Selection offset
**Describe the bug**
Multiple node selection has an offset if the workspace is zoomed.

**To Reproduce**
1. Open any workflow
2. Zoom Out or Zoom In
3. Click and hold on any empty space and select with drag drop (rectangle selection)

**Expected behavior**
Scale selection with the workspace zooming. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version:  0.102.0 
 - Node.js Version: v14.15.1

**Additional context**
Another useful thing would be zooming with ctrl and the mouse wheel.

Here is the function for the selection that needed to be fixed.: https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/mixins/mouseSelect.ts#L89

### PR DESCRIPTION
**Pull request by jonmbake**
Prior to this change, the mouse selection box had a fixed position on the page. Nodes have absolute
position within `NodeView`. This inconsistency in positioning caused issues when calculating
if a node was positioned within the mouse selection. This solution makes both nodes
and mouse selection have consistent positioning, along with correctly calculating the
mouse click position within `NodeView` when making a selection.

### CODE REVIEW

**Comment by janober** [comment]
Wow so cool! Thanks a lot!

That annoyed me for a long time.

We will review very soon and then merge and release with the next version.

File: packages/editor-ui/src/views/NodeView.vue [hunk 1]
```diff
@@ -2139,6 +2139,7 @@ export default mixins(
 	position: relative;
 	width: 100%;
 	height: 100%;
+	transform-origin: 0 0;
```
Comment (jonmbake) [inline packages/editor-ui/src/views/NodeView.vue:2142]: One side effect of this styling change is that it zooms from upper left instead of center (which I personally prefer). I couldn't find an implementation solution to #getMousePositionWithinNodeView w/o this change. Related SO answer: https://stackoverflow.com/a/15521750.

Comment (janober) [reply packages/editor-ui/src/views/NodeView.vue:2142]: Just tested. Also seems OK to me.

**Comment by janober** [comment]
Just tested. Works now perfectly for me. Thanks again. Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.110.0
