### PR TITLE
fix(editor): Sort start start nodes for manual execution by Y position

### LINKED ISSUE #15042: Bug when chat bot and if node connected, response of the chat bot
### Bug Description

Not sure if this is a bug or intented functionality. 

When i connect a chat node to an if node and an ai chat bot. It seems to matter what node i connect first if i want a response from the chat bot. In my understanding of n8n, it works top to bottem, left to right, so the order of connecting nodes shouldn't be an influencing factor of output. But in this case it seems to be 

# Debug info

## core

- n8nVersion: 1.90.2
- platform: docker (cloud)
- nodeJsVersion: 20.19.0
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community
- consumerId: 00000000-0000-0000-0000-000000000000

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/135.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-05-01T14:24:36.811Z

### To Reproduce

1: Create a work flow with three components
- chat trigger node 
- if node connected on the top side directly to the chat node
- ai agent connected on the bottem side directly to the chat node
2: to test, disconnect them both, then first connect the if node and then de ai agent. try to chat with the ai agent, didnt work i then got this error message: [No response. Make sure the last executed node outputs the content to display here]
3: Disconnect them both, then first connect the ai agent and then the if node, then you should get a response from the agent. 

Image

### Expected behavior

I was expecting it to work both ways around.

### Operating System

See first block

### n8n Version

See first block

### Node.js Version

See first block

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by OlegIvaniv**
## Summary

This PR fixes an issue where the order of connecting nodes to chat trigger affects manual workflow execution results. By implementing Y-position sorting for nodes, we ensure consistent execution flow from top to bottom, regardless of connection order.

https://github.com/user-attachments/assets/be818d3a-6057-4e81-8e89-91334975f2d3

## Related Linear tickets, Github issues, and Community forum posts

fixes #15042

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/composables/useRunWorkflow.ts [hunk 1]
```diff
@@ -60,6 +60,20 @@ export function useRunWorkflow(useRunWorkflowOpts: { router: ReturnType<typeof u
...
 
+	function sortNodesByYPosition(nodes: string[]) {
+		return [...nodes].sort((a, b) => {
+			const nodeA = workflowsStore.getNodeByName(a)?.position ?? [0, 0];
+			const nodeB = workflowsStore.getNodeByName(b)?.position ?? [0, 0];
+
+			const nodeAYPosition = nodeA[1];
+			const nodeBYPosition = nodeB[1];
+
+			if (nodeAYPosition === nodeBYPosition) return 0;
```
Comment (ggozad) [inline packages/frontend/editor-ui/src/composables/useRunWorkflow.ts:71]: I would sort by X in this case. This is nitpicking so feel free to ignore :)

**Review by ggozad — APPROVED** [review]
Awesome 🤩

**Comment by janober** [comment]
Got released with [`n8n@1.93.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.93.0)
