### PR TITLE
fix(MCP Client Tool Node): DCR not working on cloud

### LINKED ISSUE #21791: OAuth2 for MCP connection sends incorrect redirect_uri when using dynamic client registration
## Describe the problem/error/question

When attempting to connect n8n to our MCP Gateway via OAuth2 with Dynamic Client Registration, we observed an error on our Node based OAuth2 client library ([@badgateway/oauth2-client](https://github.com/badgateway/oauth2-client)) stating that the redirect_uri was invalid.

Upon investigation we determined that the `redirect_uri` provided during Dynamic Client Registration does not match the `redirect_uri` during the authentication flow, resulting in the error above.

During Dynamic Client Registration we are provided the following redirect URI:

`https://visor.app.n8n.cloud/rest/oauth2-credential/callback`

And during the authentication flow, a different URI is provided:

`https://oauth.n8n.cloud/oauth2/callback`

I'm not sure which one is correct, but I am certain that these must match, otherwise the authorization flow will fail.

Our instance URL is `https://visor.app.n8n.cloud` in case that's helpful.

## What is the error message (if any)?

```
Client authentication failed: Invalid redirect_uri
OAuthException: Client authentication failed: Invalid redirect_uri
```

## Please share your workflow/screenshots/recording

OAuth Connection Details:

Image

Resulting database entry from the Dynamic Client Registration:

|id                                  |name|secret|redirectUris                                                 |createdAt              |updatedAt              |logoUri|uri            |allowedGrants                                        |
|------------------------------------|----|------|-------------------------------------------------------------|-----------------------|-----------------------|-------|---------------|-----------------------------------------------------|
|7a57810c-a56a-40ae-9447-13e37f756584|n8n |      |{https://visor.app.n8n.cloud/rest/oauth2-credential/callback}|2025-11-12 03:29:30.592|2025-11-12 03:29:30.592|       |https://n8n.io/|{authorization_code,refresh_token,client_credentials}|

Image

Resulting error on MCP Manager:

Image

### core

- n8nVersion: 1.119.1
- platform: docker (cloud)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-11-12T21:30:22.900Z}

### PR DESCRIPTION
**Pull request by RomanDavydchuk**
## Summary

Dynamic client registration does not work on n8n cloud because the list of allowed redirect URIs does not contain `https://oauth.n8n.cloud/oauth2/callback`, which is used for cloud. That special URI is overridden using an external hook specific to cloud

Call new `oauth2.dynamicClientRegistration` external hook before performing dynamic client registration to modify `redirect_uris` parameter for n8n cloud version. This is similar to how we handle `redirectUri` by using `oauth2.authenticate` and `oauth2.callback` hooks.

PR with the new hook: https://github.com/n8n-io/n8n-cloud/pull/2693

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-3870/community-issue-oauth2-for-mcp-connection-sends-incorrect-redirect-uri
Closes #21791

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

---

> [!NOTE]
> Introduces `oauth2.dynamicClientRegistration` hook and switches OAuth2 DCR to use `${this.baseUrl}/callback` for `redirect_uris`, removing UrlService/GlobalConfig dependency.
> 
> - **Backend (OAuth2)**
>   - Build `registerPayload` for dynamic client registration with `redirect_uris: [\`${this.baseUrl}/callback\`]` and call `externalHooks.run('oauth2.dynamicClientRegistration', [registerPayload])` before registration.
>   - Replace previous URL construction using `UrlService`/`GlobalConfig` with `this.baseUrl`.
> - **External Hooks**
>   - Add new hook: `oauth2.dynamicClientRegistration` with signature `[registerPayload: { redirect_uris: string[] }]`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 69a9d4743b2d1fbc767ee4a16761573dbf04b61a. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by RomanDavydchuk** [comment]
@yehorkardash once you review it, please don't merge until I have the confirmation that [my PR for cloud repo](https://github.com/n8n-io/n8n-cloud/pull/2693) looks good too 🙏

File: packages/cli/src/controllers/oauth/oauth2-credential.controller.ts [hunk 1]
```diff
@@ -90,23 +87,25 @@ export class OAuth2CredentialController extends AbstractOAuthController {
...
 				grantType,
 				authentication,
 			);
-			const { data: registerResult } = await axios.post<{
-				client_id: string;
-				client_secret?: string;
-			}>(registration_endpoint, {
-				redirect_uris: [`${instanceBaseUrl}/${restEndpoint}/oauth2-credential/callback`],
+			const registerPayload = {
+				redirect_uris: [`${this.baseUrl}/callback`],
```
Comment (yehorkardash) [inline packages/cli/src/controllers/oauth/oauth2-credential.controller.ts:95]: will it work with self-hosted? Is `${this.baseUrl}/callback` same as `${instanceBaseUrl}/${restEndpoint}/oauth2-credential/callback`?

Comment (RomanDavydchuk) [reply packages/cli/src/controllers/oauth/oauth2-credential.controller.ts:95]: Yes, `this.baseUrl` is a getter defined on the abstract OAuth controller, and here's it's code:
```typescript
	get baseUrl() {
		const restUrl = `${this.urlService.getInstanceBaseUrl()}/${this.globalConfig.endpoints.rest}`;
		return `${restUrl}/oauth${this.oauthVersion}-credential`;
	}
```
so the end result is identical

I refactored this to simplify the code and because `this.baseUrl` [is already used in this method too](https://github.com/n8n-io/n8n/blob/c8d604d2c466dd84ec24f4f092183d86e43f2518/packages/cli/src/controllers/oauth/oauth2-credential.controller.ts#L243)

**Review by yehorkardash — APPROVED** [review]

**Review by yehorkardash — APPROVED** [review]
