### PR TITLE
fix: Empty onclick breaks range parser in HTML editor

### LINKED ISSUE #16618: onclick="" in 'Generate HTML Template'
### Bug Description

When writing an HTML element with an empty onclick attribute, the editor resets.
This is particularly confusing when copying in an entire chunk of code and nothing is inserted.

Furthermore, if you managed to insert the faulty tag (e.g. <button onclick=""></button>), no changes in the editor are possible until you delete the problematic part.

### To Reproduce

- Open a node "Generate HTML Template"
- Try to copy in `<button onclick=""></button>`

(I was not able to reproduce how I got this code to be saved in the editor. But any changes made to the code were then underlaid with a faint turquoise background, and deleted when I moved the cursor away)

### Expected behavior

Either insert the code as it is not categorically wrong in HTML, or throw a clear error for the offending part.

### Operating System

Arch Linux

### n8n Version

1.98.2

### Node.js Version

?

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by michael-radency**
## Summary

Fix for empty `onclick` as it breaks range parser in HTML editor

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/NODE-3172/community-issue-onclick=-in-generate-html-template
closes https://github.com/n8n-io/n8n/issues/16618

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/frontend/editor-ui/src/components/HtmlEditor/utils.ts [hunk 1]
```diff
@@ -38,3 +40,25 @@ export function nonTakenRanges(fullRange: Range, takenRanges: Range[]) {
...
+	const htmlData = event.clipboardData?.getData('text/html') ?? '';
+	const textData = event.clipboardData?.getData('text/plain') ?? '';
+
+	const content = htmlData || textData;
+	if (!content) return false;
+
+	// Replace onclick="" with onclick=" " as empty onclick breaks range parser
+	if (/onclick=""/.test(content)) {
+		event.preventDefault();
+		const sanitized = content.replace(/onclick=""/g, 'onclick=" "');
```
Comment (elsmr) [inline packages/frontend/editor-ui/src/components/HtmlEditor/utils.ts:54]: Is this bug only for onclick? or any empty attribute?

Comment (michael-radency) [reply packages/frontend/editor-ui/src/components/HtmlEditor/utils.ts:54]: I did try several other, looks like only applies to onclick

**Review by elsmr — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.107.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.107.0)
