### PR TITLE
fix(core): Apply correct hostname to redirected requests

### LINKED ISSUE #8668: OneDrive Node SSL Error
### Bug Description

Updated to V1.27.3 and I get this error using OneDrive now, was working in V1.18.0 but now can't revert back :(

ERROR: SSL Issue: consider using the 'Ignore SSL issues' option
Hostname/IP does not match certificate's altnames: Host: graph.microsoft.com. is not in the cert's altnames: DNS:*.media.microsoftstream.com, DNS:*.azureedge.net, DNS:*.origin.mediaservices.windows.net, DNS:*.streaming.mediaservices.windows.net

### To Reproduce

Use OneDrive Node

### Expected behavior

Works and connects

### Operating System

Docker

### n8n Version

1.27.3

### Node.js Version

?

### Database

PostgreSQL

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by elsmr**
## Summary

Broken in https://github.com/n8n-io/n8n/pull/8562

`servername` set on the httpsAgent was also being used for redirected requests. When redirected to another domain this breaks. This PR updates the `Agent.servername` when redirected.

workflow test added here: https://github.com/n8n-io/test-workflows/pull/263

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1149/recent-change-to-host-header-breaks-redirect-downloads
fixes https://github.com/n8n-io/n8n/issues/8668
https://community.n8n.io/t/ignore-ssl-setting-isnt-working-error-ssl-issue-consider-using-the-ignore-ssl-issues-option/40492

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

File: packages/core/src/NodeExecuteFunctions.ts [hunk 1]
```diff
@@ -502,6 +486,22 @@ export async function parseRequestObject(requestObject: IRequestOptions) {
 	}
 	axiosConfig.httpsAgent = new Agent(agentOptions);
 
+	axiosConfig.beforeRedirect = (redirectedRequest) => {
```
Comment (netroy) [inline packages/core/src/NodeExecuteFunctions.ts:489]: The two code blocks are identical. Can we extract this into a function like this
```typescript
const getBeforeRedirectFn =
	(agentOptions: AgentOptions, axiosConfig: AxiosRequestConfig<any>) =>
	(redirectedRequest: Record<string, any>) => {
		const redirectAgent = new Agent({
			...agentOptions,
			servername: redirectedRequest.hostname,
		});
		redirectedRequest.agent = redirectAgent;
		redirectedRequest.agents.https = redirectAgent;

		if (axiosConfig.headers?.Authorization) {
			redirectedRequest.headers.Authorization = axiosConfig.headers.Authorization;
		}
		if (axiosConfig.auth) {
			redirectedRequest.auth = `${axiosConfig.auth.username}:${axiosConfig.auth.password}`;
		}
	};
```

Comment (netroy) [inline packages/core/src/NodeExecuteFunctions.ts:489]:
```suggestion
	axiosConfig.beforeRedirect = getBeforeRedirectFn(agentOptions, axiosConfig);
```

File: packages/core/src/NodeExecuteFunctions.ts [hunk 2]
```diff
@@ -894,6 +894,22 @@ function convertN8nRequestToAxios(n8nRequest: IHttpRequestOptions): AxiosRequest
 	}
 	axiosRequest.httpsAgent = new Agent(agentOptions);
 
+	axiosRequest.beforeRedirect = (redirectedRequest) => {
```
Comment (netroy) [inline packages/core/src/NodeExecuteFunctions.ts:897]:
```suggestion
	axiosRequest.beforeRedirect = getBeforeRedirectFn(agentOptions, axiosRequest);
```

**Review by netroy — CHANGES_REQUESTED** [review]

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.30.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.30.0)
