### PR TITLE
fix(Google Sheets Node): Add a warning about using expressions

### LINKED ISSUE #17261: Google Sheets node does not iterate on sheets
## Describe the problem/error/question

When sending multiple items to a Google Sheets node (each with a different sheet ID), the node only reads data from the first sheet and returns that same data for all subsequent items, ignoring the other sheet IDs.

This has been an issue for a while (as far as I know) and requires using a Loop node as a workaround to process sheets individually. So I thought I'd take the time to test it properly.

## What is the error message (if any)?

No error message - the workflow executes successfully but returns incorrect data.

## Please share your workflow
```json
{
  "nodes": [
    {
      "parameters": {
        "jsCode": "// n8n Code Node\n// This node returns two items with table and sheet fields\n\nconst items = [\n  {\n    json: {\n      table: \"1p0hQ2leTkNBZVaScgVVKhVZFa5y_J9QkdPRmTVll48k\",\n      sheet: \"972949726\"\n    }\n  },\n  {\n    json: {\n      table: \"1p0hQ2leTkNBZVaScgVVKhVZFa5y_J9QkdPRmTVll48k\",\n      sheet: \"1959137189\"\n    }\n  }\n];\n\nreturn items;"
      },
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        224,
        0
      ],
      "id": "4212c926-2199-4526-9df1-00200e7f2812",
      "name": "dummy"
    },
    {
      "parameters": {},
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        0,
        0
      ],
      "id": "a90c2cf1-7657-41d8-afe1-1e9f73ec84dc",
      "name": "trigger"
    },
    {
      "parameters": {},
      "type": "n8n-nodes-base.limit",
      "typeVersion": 1,
      "position": [
        464,
        -176
      ],
      "id": "6a192cbb-a7a0-45c6-878a-1aa8debe1b32",
      "name": "test_first"
    },
    {
      "parameters": {
        "keep": "lastItems"
      },
      "type": "n8n-nodes-base.limit",
      "typeVersion": 1,
      "position": [
        464,
        0
      ],
      "id": "e0b0a5b1-1e54-4c6d-9e41-604baab5ed5d",
      "name": "test_last"
    },
    {
      "parameters": {
        "maxItems": 2,
        "keep": "lastItems"
      },
      "type": "n8n-nodes-base.limit",
      "typeVersion": 1,
      "position": [
        464,
        192
      ],
      "id": "30bfbb71-d44a-4faa-9ccb-9aadd18b9e72",
      "name": "test_both"
    },
    {
      "parameters": {
        "documentId": {
          "__rl": true,
          "value": "={{ $json.table }}",
          "mode": "id"
        },
        "sheetName": {
          "__rl": true,
          "value": "={{ $json.sheet }}",
          "mode": "id"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 4.6,
      "position": [
        688,
        -176
      ],
      "id": "3026e30e-cabe-4bdc-922f-c7c93b606aba",
      "name": "get_first",
      "credentials": {
        "googleSheetsOAuth2Api": {
          "id": "gM6KPph2WevSgJj6",
          "name": "joachim.brindeau@klarc.com"
        }
      }
    },
    {
      "parameters": {
        "documentId": {
          "__rl": true,
          "value": "={{ $json.table }}",
          "mode": "id"
        },
        "sheetName": {
          "__rl": true,
          "value": "={{ $json.sheet }}",
          "mode": "id"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 4.6,
      "position": [
        688,
        0
      ],
      "id": "fe43b893-7c9e-43e0-bf18-f1608dd3707a",
      "name": "get_last",
      "credentials": {
        "googleSheetsOAuth2Api": {
          "id": "gM6KPph2WevSgJj6",
          "name": "joachim.brindeau@klarc.com"
        }
      }
    },
    {
      "parameters": {
        "documentId": {
          "__rl": true,
          "value": "={{ $json.table }}",
          "mode": "id"
        },
        "sheetName": {
          "__rl": true,
          "value": "={{ $json.sheet }}",
          "mode": "id"
        },
        "options": {}
      },
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 4.6,
      "position": [
        688,
        192
      ],
      "id": "81543ae7-b59d-4c54-902e-9325070880f5",
      "name": "get_both",
      "credentials": {
        "googleSheetsOAuth2Api": {
          "id": "gM6KPph2WevSgJj6",
          "name": "joachim.brindeau@klarc.com"
        }
      }
    }
  ],
  "connections": {
    "dummy": {
      "main": [
        [
          {
            "node": "test_first",
            "type": "main",
            "index": 0
          },
          {
            "node": "test_last",
            "type": "main",
            "index": 0
          },
          {
            "node": "test_both",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "trigger": {
      "main": [
        [
          {
            "node": "dummy",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "test_first": {
      "main": [
        [
          {
            "node": "get_first",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "test_last": {
      "main": [
        [
          {
            "node": "get_last",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "test_both": {
      "main": [
        [
          {
            "node": "get_both",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {
    "get_first": [
      {
        "row_number": 2,
        "columnA": 123,
        "columnB": "abc"
      },
      {
        "row_number": 3,
        "columnA": 456,
        "columnB": "def"
      },
      {
        "row_number": 4,
        "columnA": 789,
        "columnB": "ghy"
      }
    ],
    "get_last": [
      {
        "row_number": 2,
        "columnA": "alpha",
        "columnB": "blue"
      },
      {
        "row_number": 3,
        "columnA": "bravo",
        "columnB": "orange"
      },
      {
        "row_number": 4,
        "columnA": "charlie",
        "columnB": "red"
      }
    ],
    "get_both": [
      {
        "row_number": 2,
        "columnA": 123,
        "columnB": "abc"
      },
      {
        "row_number": 3,
        "columnA": 456,
        "columnB": "def"
      },
      {
        "row_number": 4,
        "columnA": 789,
        "columnB": "ghy"
      },
      {
        "row_number": 2,
        "columnA": 123,
        "columnB": "abc"
      },
      {
        "row_number": 3,
        "columnA": 456,
        "columnB": "def"
      },
      {
        "row_number": 4,
        "columnA": 789,
        "columnB": "ghy"
      }
    ]
  },
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "2039b9ae6bdd2cfe7f6a132b7dee66390e92afbc2ec29f67cafa1edf6cad8d55"
  }
}
```

## Share the output returned by the last node

**Expected output:**
- 3 rows from sheet "972949726" (first sheet)
- 3 rows from sheet "1959137189" (second sheet)

**Actual output:**
```json
[
  {"row_number": 2, "columnA": 123, "columnB": "abc"},
  {"row_number": 3, "columnA": 456, "columnB": "def"},
  {"row_number": 4, "columnA": 789, "columnB": "ghy"},
  {"row_number": 2, "columnA": 123, "columnB": "abc"},  // Duplicate from first sheet
  {"row_number": 3, "columnA": 456, "columnB": "def"},  // Duplicate from first sheet
  {"row_number": 4, "columnA": 789, "columnB": "ghy"}   // Duplicate from first sheet
]
```

The node reads the first sheet twice instead of reading both sheets.

### core
- n8nVersion: 1.102.0
- platform: docker (self-hosted)
- nodeJsVersion: 22.17.0
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
### storage
- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory
### pruning
- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions
### client
- userAgent: mozilla/5.0 (macintosh; intel mac os x 10.15; rv:140.0) gecko/20100101 firefox/140.0
- isTouchDevice: false

### LINKED ISSUE #19551: [Bug] Google Sheets Node: Dynamic sheet name ignored — all rows go to the same sheet (affects "Append Row" and "Append or Update")
### Bug Description

When using the Google Sheets node with either Append Row or Append or Update, and setting the sheet dynamically with {{ $json.sheet_name }}, the node does not respect the sheet name **for each incoming item**.

Instead, all rows are written to the **same sheet**, which is determined by the first item in the input.

Image

Behavior:

Image

### To Reproduce

1. Create a Google Spreadsheet with multiple sheets (Sheet1, Sheet2, Sheet3, Sheet4).
2. Build an n8n workflow that:
3. Provides multiple JSON items with different sheet_name values (see example below).
4. Uses the Google Sheets node with operation Append Row or Append or Update.
5. Set Sheet to By Name → {{ $json.sheet_name }}.
6. Execute the workflow.

**Example Input:**
`[
  {
    "pgw_id": -25,
    "sheet_name": "Sheet1",
    "grand_total": 30299900,
    "date": "2025/06/01"
  },
  {
    "pgw_id": -10,
    "sheet_name": "Sheet2",
    "grand_total": 161.64,
    "date": "2025/06/01"
  },
  {
    "pgw_id": -6,
    "sheet_name": "Sheet3",
    "grand_total": 231400,
    "date": "2025/06/01"
  },
  {
    "pgw_id": -5,
    "sheet_name": "Sheet4",
    "grand_total": 46097800,
    "date": "2025/06/01"
  }
]
`

### Expected behavior

Each row should be written (or updated) in the Google Sheet tab corresponding to its sheet_name value:

First row → Sheet1
Second row → Sheet2
Third row → Sheet3
Fourth row → Sheet4

**Actual Behavior**

- All rows are written (or updated) into the same sheet (the sheet name of the first input item).
- If the first item has "sheet_name": "Sheet1", then all items go to Sheet1.
- If the first item has "sheet_name": "Sheet2", then all items go to Sheet2.
- Same behavior occurs for both Append Row and Append or Update.

Image

### Debug Info

# Debug info

## core

- n8nVersion: 1.110.1
- platform: docker (self-hosted)
- nodeJsVersion: 22.19.0
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/139.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-09-15T11:00:48.786Z

### Operating System

macOs 15.6

### n8n Version

1.110.1

### Node.js Version

22.19.0

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by yehorkardash**
## Summary

This PR adds a warning that is show when document or sheet parameter is using expressions. Removing expressions support can be risky because some users may be using expressions in their existing workflows and they can be used for other purposes other than being dynamic for each item.

image

There is a similar warning for ExecuteWorkflow node

image

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/NODE-3660/community-issue-bug-google-sheets-node-dynamic-sheet-name-ignored-all
https://linear.app/n8n/issue/NODE-860/google-sheets-sheet-id-is-not-looped
https://linear.app/n8n/issue/GHC-3068/community-issue-google-sheets-node-does-not-iterate-on-sheets
https://linear.app/n8n/issue/NODE-1573/community-issue-google-sheets-not-inserting-into-correct-sheet-in

closes #17261
closes #19551

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

File: packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts [hunk 1]
```diff
@@ -69,6 +69,24 @@ export const versionDescription: INodeTypeDescription = {
...
 			location: 'outputPane',
 		},
+		{
+			type: 'info',
+			message:
+				'Note on using an expression for Sheet: It will be evaluated only once, so all items will use the <em>same</em> sheet. It will be calculated by evaluating the expression for the <strong>first input item</strong>.',
+			displayCondition:
+				'={{ $rawParameter.sheetName?.startsWith("=") && $input.all().length > 1 }}',
+			whenToDisplay: 'always',
+			location: 'outputPane',
```
Comment (michael-radency) [inline packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts:79]: whenToDisplay: 'always', - probably better to display only before

**Review by michael-radency — CHANGES_REQUESTED** [review]

File: packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts (hunk 1 above)
Comment (yehorkardash) [reply packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts:79]: If a user doesn't have inputs, they may not see the message at all, because before the execution there was no warning and after execution it's not shown

Comment (michael-radency) [reply packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts:79]: make sense, thanks

**Review by michael-radency — APPROVED** [review]
LGTM

**Review by michael-radency — APPROVED** [review]

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Got released with [`n8n@1.113.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.113.0)
